---
- name: Set hostname for RedHat-based OS
  ansible.builtin.include_tasks: el.yml
  when: ansible_facts['os_family'] == 'RedHat'
- name: Set hostname for Debian-based OS
  ansible.builtin.include_tasks: ubuntu.yml
  when: ansible_facts['os_family'] == 'Debian'
