---
- name: Install required packages
  vars: 
    package_name: 
      - python3-click
      - python3-ldap3
    package_state: present
    package_cache: true
  include_role: 
    name: safe_yum

- name: copy cluster cli 
  copy: 
    src: cluster
    dest: /usr/bin/
    owner: root
    group: root
    mode: '0755'