---

- name: Install required packages
  apt:
    name:
      - python3-click
      - python3-ldap3
    state: present
    update_cache: yes

- name: copy cluster cli 
  copy: 
    src: cluster
    dest: /usr/bin/
    owner: root
    group: root
    mode: '0755'