---

- name: install required packages
  vars: 
    package_name: 
      - python36-click
      - python36-ldap3
    package_repo: "epel,ol7_developer_EPEL"
  include_role: 
    name: safe_yum

- name: copy cluster cli 
  copy: 
    src: cluster
    dest: /usr/bin/
    owner: root
    group: root
    mode: '0755'
