---
- name: Install required packages
  vars:
    package_name:
      - python36-click
      - python36-ldap3
    package_repo: "epel,ol7_developer_EPEL"
  include_role:
    name: safe_yum

- name: Copy cluster cli
  template:
    src: cluster.j2
    dest: /usr/bin/cluster
    owner: root
    group: root
    mode: "0755"
