---
- include_tasks: el8.yml
  when: ansible_facts['os_family'] == 'RedHat' and ansible_facts['distribution_major_version'] == '8'

- include_tasks: el9.yml
  when: ansible_facts['os_family'] == 'RedHat' and ansible_facts['distribution_major_version'] == '9'

- include_tasks: debian.yml
  when: ansible_facts['distribution'] == 'Ubuntu'
