---
- block:
  - name: Install limits.conf 
    template: 
      src: "templates/limits.j2" 
      dest: "/etc/security/limits.d/50-hpc-limits.conf" 
      owner: root
      group: root
      mode: 0644
