---
- ansible.builtin.include_tasks: common.yml
  when: ansible_os_family == 'RedHat'

- ansible.builtin.include_tasks: common.yml
  when: ansible_distribution == 'Ubuntu'

- ansible.builtin.include_tasks: common.yml
  when: ansible_distribution == 'Debian'
