---
- name: Update ssh configuration
  copy: 
    src: files/ssh_config
    dest: /etc/ssh/ssh_config
    owner: root
    group: root
    mode: '0644'

- name: Install ssh keys on all nodes
  copy:
    dest: "/home/{{ ansible_user }}/.ssh/id_rsa"
    src: "/home/{{ ansible_user }}/.ssh/{{ item }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0600'
  with_items:
    - cluster.key

- name: Generate an OpenSSL public key in OpenSSH v2 format
  openssl_publickey:
    path: "/home/{{ ansible_user }}/.ssh/id_rsa.pub"
    privatekey_path: "/home/{{ ansible_user }}/.ssh/id_rsa"
    format: OpenSSH
    state: present
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0644'
  register: public_key
