---
- name: Update ssh configuration
  copy: 
    src: files/ssh_config
    dest: /etc/ssh/ssh_config
    owner: root
    group: root
    mode: '0644'

- name: Install private ssh key on all nodes
  copy:
    dest: "/home/{{ ansible_user }}/.ssh/id_rsa"
    src: "/home/{{ bastion_username }}/.ssh/{{ item }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0600'
  with_items:
    - cluster.key

- name: Install public ssh key on all nodes
  copy:
    dest: "/home/{{ ansible_user }}/.ssh/id_rsa.pub"
    src: "/home/{{ bastion_username }}/.ssh/{{ item }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0644'
  with_items:
    - id_rsa.pub