---
- name: Set python version variables
  set_fact:
    python_version: >-
      {% if ansible_distribution == 'OracleLinux' and ansible_distribution_major_version == '8' %}3.8
      {% elif ansible_distribution == 'OracleLinux' and ansible_distribution_major_version == '9' %}3.9
      {% elif ansible_distribution == 'Ubuntu' and ansible_distribution_major_version == '22' %}3.10
      {% elif ansible_distribution == 'Ubuntu' and ansible_distribution_major_version == '24' %}3.12
      {% else %}3{% endif %}
    python_executable: "/usr/bin/python{{ python_version }}"
    pip_executable: "/usr/bin/pip{{ python_version }}"

- name: Install python build dependencies (apt)
  package:
    name:
      - gcc
      - make
      - patch
      - zlib1g-dev
      - libbz2-dev
      - libreadline-dev
      - sqlite3
      - libsqlite3-dev
      - libssl-dev
      - tk-dev
      - libffi-dev
      - xz-utils
      - libjwt-dev
      - libhttp-parser-dev
      - default-jre
      - "python{{ python_version }}"
      - "python{{ python_version }}-dev"
      - python3-pip
    state: present
  become: true
  when: ansible_os_family == "Debian"

- name: Install python build dependencies (dnf)
  dnf:
    name:
      - gcc
      - make
      - patch
      - zlib-devel
      - bzip2
      - bzip2-devel
      - readline-devel
      - sqlite
      - sqlite-devel
      - openssl-devel
      - tk-devel
      - libffi-devel
      - xz-devel
      - libjwt-devel
      - http-parser-devel
      - java-1.8.0-openjdk
      - "python{{ python_version }}"
      - "python{{ python_version }}-devel"
      - "python{{ python_version }}-pip"
    enablerepo: ol8_codeready_builder,ol8_appstream,ol9_codeready_builder,ol9_appstream
    state: present
  become: true
  when: ansible_os_family == "RedHat"
  
- name: Render slurmrestd systemd service file
  become: true
  template: 
    src: slurmrestd.service.j2
    dest: /etc/systemd/system/slurmrestd.service
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0744

- name: start slurmrestd service
  become: true
  service:
    name: slurmrestd
    daemon_reload: true
    state: restarted
    enabled: yes