- name: Render slurm-exporter python script
  template:
    src: slurm-exporter.py.j2
    dest: /usr/local/bin/slurm-exporter.py
    owner: "{{ slurm_user }}"
    group: "{{ slurm_group }}"
    mode: "0744"
  become: true

- name: Render slurm-exporter systemd service
  template:
    src: slurm-exporter.service.j2
    dest: /etc/systemd/system/slurm-exporter.service
    owner: "{{ slurm_user }}"
    group: "{{ slurm_group }}"
    mode: "0644"
  become: true

- name: Start/enable slurm-exporter
  service:
    name: slurm-exporter
    daemon_reload: true
    state: restarted
    enabled: true
  become: true
