---

- name: Edit /etc/security/access.conf
  become: true
  blockinfile:
    dest: /etc/security/access.conf
    block: |
      +:root:ALL
      +:wheel:ALL
      +:opc:ALL
      -:ALL:ALL

- name: Copy sshd file
  become: true
  copy:
    src: sshd
    dest: /etc/pam.d/sshd

- name: Edit slurm.conf to add cgroup to TaskPlugin
  become: true
  lineinfile:
    path: /etc/slurm/slurm.conf
    regexp: "TaskPlugin=task/affinity" 
    line: "TaskPlugin=task/affinity,task/cgroup"
    state: present
  when: ('bastion' in group_names )

- name: Edit slurm.conf to add the PrologFlag
  become: true
  lineinfile:
    path: /etc/slurm/slurm.conf
    line: "PrologFlags=contain"
    state: present
  when: ('bastion' in group_names )

- name: Stop logind
  systemd:
    name: systemd-logind
    state: stopped
    enabled: no
    masked: yes

- name: restart slurm server
  become: true
  service:
    name: '{{ item }}'
    state: restarted
    enabled: true
  with_items:
    - slurmdbd
    - slurmctld
  register: result
  until: result is not failed
  retries: 5
  delay: 5
  when: ('bastion' in group_names )

- name: restart slurm
  become: true
  service: 
    name: '{{ item }}'
    state: restarted
    enabled: true
  with_items: 
    - slurmd
  register: result
  until: result is not failed
  retries: 5
  delay: 5
  when: ('compute' in group_names )
