---
- name: Call oracle cloud agent updater role
  ansible.builtin.include_role:
    name: oci-cloud-agent-updater

- name: Unregister agent
  ansible.builtin.command: osms unregister
  retries: 5
  register: unregister_cloud_agent
  until: unregister_cloud_agent is not failed
  when: ansible_facts['distribution_major_version'] == '8' or ansible_facts['distribution_major_version'] == '7'
  ignore_errors: true

# incase it takes time to get all repo ready after osms unregister
- name: Sleep 5 seconds
  ansible.builtin.pause:
    seconds: 5

# There seem to be a yum process from the cloud-agent that is randomly hanging and is blocking for other tasks.
- name: Make sure the yum process is destroyed.
  ansible.builtin.shell: "ps -ef | grep /v[a]r/lib/oracle-cloud-agent/plugins/unifiedmonitoring/temp-unified-monitoring.rpm | head -n 1 | awk '{print $2}'"
  register: yum_process

- name: Kill Yum Process
  ansible.builtin.command: "sudo kill -9 {{ yum_process.stdout }}"
  when: yum_process.stdout != ""
  ignore_errors: true
