---
- ansible.builtin.include_tasks: el.yml
  when: ansible_os_family == 'RedHat' and ansible_distribution == 'OracleLinux'
- ansible.builtin.include_tasks: ubuntu.yml
  when: ansible_os_family == 'Debian'
