---
- include_tasks: el.yml
  when: ansible_facts['os_family'] == 'RedHat'

- include_tasks: debian.yml
  when: ansible_facts['distribution'] == 'Ubuntu'

- include_tasks: debian.yml
  when: ansible_facts['distribution'] == 'Debian'
