---
ubuntu_repo_dist_name: "{{ ansible_facts['distribution'] | lower }}{{ ansible_facts['distribution_version'] }}"
ubuntu_repo_file_name: "nvidia-container-toolkit.list"
ubuntu_repo_file_path: "/etc/apt/sources.list.d/{{ ubuntu_repo_file_name }}"
