---
# handler file for mariadb

- name: Restart mysqld
  become: true
  service:
    name: mysqld
    state: restarted

- name: Restart mariadb
  become: true
  service:
    name: mariadb
    state: restarted
