---
# handler file for mariadb

- name: restart mysqld
  become: true
  service:
    name: mysqld
    state: restarted

- name: restart mariadb
  become: true
  service:
    name: mariadb
    state: restarted
