---
- name: Check if nvidia drivers are installed
  shell: cat /sys/module/nvidia/version | wc -l
  register: gpu


- name: Check if nvidia_peermem module is loaded
  shell: lsmod | grep nvidia_peermem | wc -l
  register: result
  when: gpu.stdout == '1'


- name: Load nvidia_peermem module
  become: true
  shell: modprobe nvidia_peermem
  when: gpu.stdout == '1' and result.stdout != '3'