---
      
- name: install SLURM server packages
  become: true
  yum:
    enablerepo: "epel,ol7_developer_EPEL"
    name:
      - slurm-pam_slurm
      - slurm-pmi
      - slurm-slurmd

- name: Create systemd unit dirs
  become: true
  file:
    name: '/etc/systemd/system/{{ item }}.service.d'
    state: directory
  with_items:
    - munge

#- name: Modify slurmd.service file
#  become: true
#  replace:
#    path: "/usr/lib/systemd/system/slurmd.service"
#    regexp: 'ExecStart=/usr/sbin/slurmd \$SLURMD_OPTIONS'
#    replace: 'ExecStart=/usr/sbin/slurmd --conf-server bastion:6817 $SLURMD_OPTIONS'

- name: Create munge dir
  become: true
  file:
    name: '{{ munge_conf_path }}'
    state: directory
    owner: munge
    group: munge
    mode: 0700

- name: copy munge.key to tmp
  become: true
  shell:
    cmd: cp /etc/munge/munge.key /tmp/munge.key
    warn: false
  delegate_to: 127.0.0.1
  run_once: true

- name: set permissions
  become: true
  shell:
    cmd: chown opc:opc /tmp/munge.key
    warn: false
  delegate_to: 127.0.0.1
  run_once: true

- name: Copy munge key
  become: true
  copy:
    src: /tmp/munge.key
    dest: /etc/munge/munge.key
    owner: munge
    group: munge
    mode: '0400'
  notify: restart munge

- name: restart munge
  become: true
  service:
    name: munge
    state: restarted
    enabled: true

- name: Create {{ slurm_spool_path }}
  become: true
  file:
    name: "{{ slurm_spool_path }}"
    state: directory
    owner: 'slurm'
    group: 'slurm'
    mode: '0750'
 
- name: Copy configuration files
  become: true
  copy: 
    src: '{{ item }}'
    dest: '{{ slurm_conf_path }}/{{ item }}'
    force: no
    owner: slurm
    group: slurm
  with_items: 
    - cgroup.conf
