- hosts: gluster
  become: true
  tasks:
  - name: mkdir
    file:
      path: /mnt/localdisk/gluster-export
      state: directory
      owner: opc
      group: opc
  - name: Add Gluster Server repository
    yum:
      name: oracle-gluster-release-el7
      state: present
  - name: Run the OL yum script
    script: /usr/bin/ol_yum_configure.sh
  - name: Add Gluster Server repository
    yum:
      name: glusterfs-server
      state: present
  - name: start gluster server
    service:
      name: glusterd
      state: started
      enabled: yes
  - name: Create a trusted storage pool
    gluster_peer:
      state: present
      nodes: "{{ groups.gluster[0]}}"
    ignore_errors: true
- hosts: "{{groups.gluster[0]}}"
  become: true
  tasks:
  - name: Create a trusted storage pool
    gluster_peer:
      state: present
      nodes: "{{ groups.gluster | join(',') }}"
    ignore_errors: true
  - name: restart gluster server
    service:
      name: glusterd
      state: restarted
      enabled: yes
  - name: sleep for 10 seconds before creating the volume
    wait_for:
      timeout: 10 
  - name: create gluster volume
    gluster_volume:
      state: present
      name: gluster-share
      bricks: /mnt/localdisk/gluster-export
      rebalance: yes
      cluster: "{{ groups.gluster | join(',') }}"
      options:
        { ctime: 'off'
        }
    ignore_errors: true 
  - name: start gluster volume
    gluster_volume:
      state: started
      name: gluster-share
- hosts: all
  become: true
  tasks:
  - name: mkdir
    file:
      path: /mnt/gluster-share
      state: directory
      owner: opc
      group: opc
  - name: Add Gluster Client repository
    yum:
      name: glusterfs-client
      state: present
  - name: Ensure the Gluster volume is mounted.
    mount:
      name: /mnt/gluster-share/
      src: "{{ groups.gluster[0] }}:gluster-share"
      fstype: glusterfs
      opts: defaults,noatime
      state: mounted