[controller]
${controller_name} ansible_host=${controller_ip} ansible_user=${controller_username} role=controller ansible_python_interpreter=/config/venv/##VENV_OS_ARCH##/oci/bin/python3
[slurm_backup]
%{ if backup_name !="" }${backup_name} ansible_host=${backup_ip} ansible_user=${compute_username} role=controller%{ endif }
[monitoring]
%{ if monitoring_name !="" }${monitoring_name} ansible_host=${monitoring_ip} ansible_user=${compute_username} role=monitoring%{ endif }
[compute_to_add]
[compute_configured]
[compute_to_destroy]
[nfs]
[compute:children]
compute_to_add
compute_configured
[all:vars]
ansible_connection=ssh
rdma_network=${rdma_network}
rdma_netmask=${rdma_netmask}
public_subnet=${public_subnet} 
private_subnet=${private_subnet}
nvme_path=/mnt/localdisk/
create_fss=${create_fss} 
shared_home=${shared_home}
slurm_nfs_path=${slurm_nfs_path}
rdma_enabled=${rdma_enabled}
slurm=${slurm}
slurm_version=${slurm_version}
rack_aware=${rack_aware}
spack=${spack}
cluster_name=${cluster_name}
shape=${shape}
add_nfs=${add_nfs}
nfs_target_path=${nfs_target_path}
nfs_source_IP=${nfs_source_IP}
nfs_source_path=${nfs_source_path}
nfs_options=${nfs_options}
localdisk=${localdisk}
redundancy=${redundancy}
log_vol=${log_vol}
instance_pool_ocpus=${instance_pool_ocpus}
queue=${queue}
cluster_monitoring=${cluster_monitoring}
hyperthreading=${hyperthreading}
ldap=${ldap}
instance_type=default
enroot=${enroot}
pyxis=${pyxis}
pam=${pam}
privilege_sudo=${privilege_sudo}
privilege_group_name=${privilege_group_name}
compute_username=${compute_username}
controller_username=${controller_username}
region=${region}
tenancy_ocid=${tenancy_ocid}
sacct_limits=${sacct_limits}
zone_name=${zone_name}
vcn_compartment=${vcn_compartment}
healthchecks=${healthchecks}
change_hostname=${change_hostname}
hostname_convention=${hostname_convention}
controller_hostname=${controller_name}
monitoring_hostname=%{ if monitoring_name !="" }${monitoring_name}%{ else }%{ if cluster_monitoring}${controller_name}%{ endif }%{ endif }
slurm_backup_hostname=%{ if backup_name !="" }${backup_name}%{ endif }
http_server_port=9876
db_name=network_scan
collection_name=http_servers
queue_ocid=${queue_ocid}
ons_topic_ocid=${ons_topic_ocid}
ondemand_partition=${ondemand_partition}
ondemand_partition_count=${ondemand_partition_count}
grafana_initial_creds=${grafana_initial_creds}
add_lfs=${add_lfs}
lfs_target_path=${lfs_target_path}
lfs_source_IP=${lfs_source_IP}
lfs_source_path=${lfs_source_path}
lfs_options=${lfs_options}
metrics_stream_ocid=${metrics_stream_ocid}
mysql_admin_username=${mysql_admin_username}
mysql_admin_password=${mysql_admin_password}
mysql_service_host=${mysql_service_host}
wildcard_dns_domain=${wildcard_dns_domain}
use_lets_encrypt_prod_ep=${use_lets_encrypt_prod_ep}