---
title: HPC cluster
description: Oracle Cloud HPC cluster
schemaVersion: 1.1.0
version: "20200825"
logoUrl: >
  https://cloudmarketplace.oracle.com/marketplace/content?contentId=80357668

source:
  type: marketplace
  reference: 67628143
locale: "en"

variableGroups:
  - title: "Cluster configuration"
    variables:
      - ${targetCompartment}
      - ${ad}
      - ${ssh_key}
      - ${use_custom_name}
      - ${cluster_name}
  - title: "Headnode options"
    variables:
      - ${bastion_ad}
      - ${bastion_shape}
      - ${bastion_ocpus}
      - ${use_standard_image}
      - ${custom_bastion_image}
      - ${bastion_boot_volume_size}
  - title: "Compute node options"
    variables:
      - ${cluster_network}
      - ${cluster_network_shape}
      - ${instance_pool_shape}
      - ${instance_pool_ocpus}
      - ${node_count}
      - ${boot_volume_size}
      - ${use_marketplace_image}
      - ${image}
  - title: "Advanced options"
    variables:
      - ${use_advanced}
      - ${use_cluster_nfs}
      - ${cluster_nfs_path}
      - ${use_scratch_nfs}
      - ${scratch_nfs_path}
  - title: "Network options"
    variables:
      - ${use_existing_vcn}
      - ${vcn_compartment}
      - ${vcn_id}
      - ${public_subnet_id}
      - ${private_subnet_id}
      - ${vcn_subnet}
      - ${public_subnet}
      - ${additional_subnet}
      - ${private_subnet}
      - ${ssh_cidr}
  - title: "Software"
    variables:
      - ${slurm}
      - ${spack} 
  - title: "Hidden"
    variables:
      - ${region}
      - ${tenancy_ocid}
      - ${cluster_nfs_mount}
      - ${cluster_nfs_export}
      - ${scratch_nfs_export}
      - ${scratch_nfs_mount}
    visible: false


variables:
  targetCompartment:
    title: "target compartment"
    type: oci:identity:compartment:id
  ad:
    type: oci:identity:availabilitydomain:name
    dependsOn:
      compartmentId: ${targetCompartment}
    visible: complexExpression
    required: true
    description: "Availability Domain"
    title: "Availability Domain"
  ssh_key:
    type: string
    title: "Public SSH key"
    required: true
  use_custom_name:
    type: boolean
    title: "use custom cluster name"
    description: "Use custom name for the cluster"
    required: true
    default: false
  cluster_name:
    title: "Name of the cluster"
    description: "Custom cluster name"
    type: string
    visible:
      and:
        - ${use_custom_name}
  bastion_ad:
    type: oci:identity:availabilitydomain:name
    dependsOn:
      compartmentId: ${targetCompartment}
    visible: complexExpression
    required: true
    description: "Availability Domain for bastion host"
    title: "Availability Domain"
  bastion_shape:
    type: oci:core:instanceshape:name
    dependsOn:
      compartmentId: ${targetCompartment}
  bastion_ocpus:
    type: integer
    description: Number of OCPU's for flex shape
    minimum: 1
    maximum: 64
    default: 2
    visible:
      eq:
        - ${bastion_shape}
        - "VM.Standard.E3.Flex"
    required: false
  use_standard_image:
    type: boolean
    title: "use standard bastion image"
    description: >
      "Use standard bastion image, otherwise provide custom image OCID"
    required: true
    default: true
  custom_bastion_image:
    title: "Bastion Image ID"
    description: "Custom image ID for bastion nodes"
    type: oci:core:image:id
    dependsOn:
      compartmentId: ${targetCompartment}
    visible:
      not:
        - ${use_standard_image}
  bastion_boot_volume_size:
    type: integer
    required: true
    minimum: 50
    title: "Size of the boot volume in GB"
    default: 50
  cluster_network:
    title: Use cluster network
    type: boolean
    description: Use ROCEv2 cluster network
    default: true
  cluster_network_shape:
    type: enum
    enum:
      - "BM.HPC2.36"
    title: "Shape of the Compute Nodes"
    required: true
    visible:
      and:
        - ${cluster_network}
  instance_pool_shape:
    title: "Shape of the Compute Nodes"
    required: true
    type: oci:core:instanceshape:name
    dependsOn:
      compartmentId: ${targetCompartment}
    visible:
      not:
        - ${cluster_network}
  instance_pool_ocpus:
    title: Cores
    type: integer
    description: Number of OCPU's for flex shape
    minimum: 1
    maximum: 64
    default: 2
    visible:
      eq:
        - ${instance_pool_shape}
        - "VM.Standard.E3.Flex"
    required: false
  node_count:
    required: true
    type: integer
    minimum: 2
    title: "Number of Compute Instances"
    default: 2
  boot_volume_size:
    type: integer
    required: true
    minimum: 50
    title: "Size of the boot volume in GB"
    default: 50
  use_marketplace_image:
    type: boolean
    title: "use marketplace image"
    description: "Use marketplace image, otherwise provide custom image OCID"
    required: true
    default: true
  marketplace_listing: 
    type: enum
    title: "Image version" 
    description: "Marketplace listing to use" 
    required: true
    enum: 
      - "Oracle Linux 7.5 OFED4.4" 
      - "Oracle Linux 7.8 OFED5.0" 
    default: 
      - "Oracle Linux 7.8 OFED5.0" 
    visible: 
      and: 
        - ${use_marketplace_image}
  image:
    title: "Image ID"
    description: "Custom image ID for compute nodes"
    type: oci:core:image:id
    default: "ocid1.image.oc1..aaaaaaaa5yxem7wzie34hi5km4qm2t754tsfxrjuefyjivebrxjad4jcj5oa"
    dependsOn:
      compartmentId: ${targetCompartment}
    visible:
      not:
        - ${use_marketplace_image}
  use_advanced:
    type: boolean
    title: "Show advanced options"
    default: false
  use_cluster_nfs:
    type: boolean
    title: "shared NFS volume from bastion"
    visible:
      and:
        - ${use_advanced}
    default: true
  use_scratch_nfs:
    type: boolean
    title: "Shared NFS scratch space from NVME disk"
    visible:
      and:
        - ${use_advanced}
    default: true
  cluster_nfs_path:
    title: "Cluster share mount point"
    description: "Path to NFS share"
    default: "/nfs/cluster"
    type: string
    visible:
      and:
        - ${use_advanced}
        - ${use_cluster_nfs}
  scratch_nfs_path:
    title: "NFS scratch space mount point"
    description: "Path to NFS share"
    default: "/nfs/scratch"
    type: string
    visible:
      and:
        - ${use_advanced}
        - ${use_scratch_nfs}
  use_existing_vcn:
    type: boolean
    title: "Use Existing VCN"
    description: "Use existing VCN or create new one"
    default: false
    required: true
  vcn_compartment:
    title: "VCN compartment"
    type: oci:identity:compartment:id
    visible: ${use_existing_vcn}
    default: ${targetCompartment}
  vcn_id:
    type: oci:core:vcn:id
    visible:
      and:
        - ${use_existing_vcn}
    title: "Existing network"
    default: ''
    required: true
    dependsOn:
      compartmentId: ${vcn_compartment}
  public_subnet_id:
    type: oci:core:subnet:id
    dependsOn:
      compartmentId: ${vcn_compartment}
      vcnId: ${vcn_id}
      hidePrivateSubnet: true
    visible: ${use_existing_vcn}
  private_subnet_id:
    type: oci:core:subnet:id
    dependsOn:
      compartmentId: ${vcn_compartment}
      vcnId: ${vcn_id}
      hidePublicSubnet: true
    visible: ${use_existing_vcn}
  vcn_subnet:
    type: string
    title: "VCN IP range"
    description: "VCN subnet"
    default: "172.16.0.0/21"
    required: true
    visible:
      not:
        - ${use_existing_vcn}
  public_subnet:
    type: string
    title: "Public subnet IP range"
    default: "172.16.0.0/24"
    description: "Must be within VCN subnet"
    required: true
    visible:
      not:
        - ${use_existing_vcn}
  additional_subnet:
    type: string
    title: "Additional subnet IP range"
    default: "172.16.1.0/24"
    description: "Must be within VCN subnet"
    required: true
    visible:
      not:
        - ${use_existing_vcn}
  private_subnet:
    type: string
    title: "Private subnet IP range"
    default: "172.16.4.0/22"
    description: "Must be within VCN subnet"
    required: true
    visible:
      not:
        - ${use_existing_vcn}
  ssh_cidr:
    type: string
    title: "Initial CIDR range allowed to SSH"
    default: "0.0.0.0/0"
    description: "Allowed SSH network in CIDR notation"
    required: true
    visible:
      not:
        - ${use_existing_vcn}
  slurm:
    type: boolean
    title: "Install SLURM"
    default: false
  spack:
    type: boolean
    title: "Install Spack package manager"
    default: false

