variable "ad" {}
variable "ssh_key" {}
variable "use_custom_name" {}
variable "cluster_name" {}
variable "bastion_ad" {}
variable "bastion_shape" {}
variable "use_standard_image" {}
variable "custom_bastion_image" {}
variable "bastion_boot_volume_size" {}
variable "shape" {}
variable "node_count" {}
variable "boot_volume_size" {}
variable "use_marketplace_image" {}
variable "image" {}
variable "use_advanced" {}
variable "use_cluster_nfs" {}
variable "use_scratch_nfs" {}
variable "cluster_nfs_path" {}
variable "cluster_nfs_export" {}
variable "cluster_nfs_mount" {}
variable "scratch_nfs_path" {}
variable "scratch_nfs_export" {}
variable "scratch_nfs_mount" {}
variable "vcn_compartment" {}
variable "vcn_id" {}
variable "use_existing_vcn" {}
variable "public_subnet_id" {}
variable "private_subnet_id" {}
variable "additional_subnet_id" {}
variable "vcn" {}
variable "public_subnet" {}
variable "additional_subnet" {}
variable "private_subnet" {}
variable "ssh_cidr" {}
variable "slurm" {}
