---
- name: Ensure apt process is completed
  become: true
  ansible.builtin.shell: ps aux | grep "apt update" | grep -v grep | wc -l
  register: result
  retries: 30
  delay: 10
  until: result.stdout | int == 0

- name: Wait for any possibly running unattended upgrade to finish
  ansible.builtin.command: systemd-run --property="After=apt-daily.service apt-daily-upgrade.service" --wait /bin/true
  async: 300
  poll: 0
  register: yum_sleeper

- name: Check on an async task
  ansible.builtin.async_status:
    jid: "{{ yum_sleeper.ansible_job_id }}"
  register: job_result
  until: job_result is not failed
  retries: 30
  delay: 10
  ignore_errors: true
  when: yum_sleeper.ansible_job_id is defined

- name: Remove unattended-upgrades
  ansible.builtin.systemd:
    name: unattended-upgrades
    state: stopped
    enabled: false
  ignore_errors: true

- name: Ensure apt process is completed
  become: true
  ansible.builtin.shell: ps aux | grep "apt update" | grep -v grep | wc -l
  register: result
  retries: 30
  delay: 10
  until: result.stdout | int == 0

- name: Purge unattended-upgrades
  vars:
    package_name:
      - unattended-upgrades
    package_state: absent
    package_purge: true
  ansible.builtin.include_role:
    name: safe_yum
  ignore_errors: true

- name: Stop and mask timers
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: stopped
    enabled: false
    masked: true
  with_items:
    - apt-daily-upgrade.timer
    - apt-daily.timer

- name: Ensure apt process is completed
  become: true
  ansible.builtin.shell: ps aux | grep "apt update" | grep -v grep | wc -l
  register: result
  retries: 30
  delay: 10
  until: result.stdout | int == 0

- name: Mark packages
  become: true
  ansible.builtin.dpkg_selections:
    name: "{{ item }}"
    selection: hold
  with_items:
    - linux-oracle
    - linux-headers-oracle
    - linux-image-oracle
  ignore_errors: true

- name: Ensure apt process is completed
  become: true
  ansible.builtin.shell: ps aux | grep "apt update" | grep -v grep | wc -l
  register: result
  retries: 30
  delay: 10
  until: result.stdout | int == 0

- name: Ensure lock file is removed
  become: true
  ansible.builtin.file:
    path: "/var/lib/apt/lists/lock"
    state: absent
  retries: 30
  delay: 10
  until: result.stdout | int == 0

- name: Run apt-get update
  become: true
  ansible.builtin.shell: |
    sudo apt-get update &
    PID1=$!
    wait $PID1
- name: Run fix-broken
  become: true
  ansible.builtin.shell: |
    sudo apt -y --fix-broken install &
    PID1=$!
    wait $PID1
