---
- block:
    - name: Set mydistribution
      ansible.builtin.set_fact:
        mydistribution: "{{ 'rhel' if (ansible_facts['distribution'] == 'OracleLinux') else (ansible_facts['distribution'] | lower) }}{{ ansible_facts['distribution_version'] }}"

    - name: Mydistribution
      ansible.builtin.debug:
        msg: "{{ mydistribution }}"

    - name: Download nvidia-docker.repo.
      ansible.builtin.get_url:
        url: "https://nvidia.github.io/nvidia-docker/{{ mydistribution }}/nvidia-docker.repo "
        dest: "/etc/yum.repos.d/nvidia-docker.repo"
        mode: "0644"
        owner: root
        group: root
        force: true

    - name: Clean
      ansible.builtin.command: yum clean expire-cache
      args:
        warn: false

    - name: Install nvidia-container-toolkit
      vars:
        package_name:
          - nvidia-container-toolkit
        package_state: latest
        package_cache: true
      ansible.builtin.include_role:
        name: safe_yum

    - name: Start Docker
      ansible.builtin.service:
        name: "docker"
        state: restarted
