---

- name: add key
  apt_key:
    url: "{{ libnvidia_container_repo_gpg_url }}"
    state: present

- name: add repo
  get_url:
    url: "{{ libnvidia_container_repo_base_url }}/{{ ubuntu_repo_dist_name }}/{{ ubuntu_repo_file_name }}"
    dest: "{{ ubuntu_repo_file_path }}"
    mode: 0644
    owner: root
    group: root

- name: install packages
  apt:
    name: libnvidia-container-tools{{ libnvidia_container_tools_package_version | ternary("="+libnvidia_container_tools_package_version, "") }}
    state: "{{ libnvidia_container_tools_package_state }}"
    update_cache: yes
  register: result
  until: result is not failed
  retries: 5
  delay: 5

- name: Install nvidia-container-toolkit
  vars:
    package_name:
      - nvidia-container-toolkit
    package_state: latest
    package_cache: true
  include_role:
    name: safe_yum

- name: Start Docker
  ansible.builtin.service:
    name: "docker"
    state: restarted




