---
- name: Set use_nfs_home_dirs if SELINUX is enabled
  vars:
    ansible_python_interpreter: "/usr/bin/python3"
  ansible.posix.seboolean:
    name: use_nfs_home_dirs
    state: true
    persistent: true
  when:
  - ansible_facts['selinux'] is defined
  - ansible_facts['selinux'] != false
  - ansible_facts['selinux']['status'] == 'enabled'
