---
# tasks file for prometheus
- name: Ensure group "{{ prometheus_user }}" exists
  become: true
  ansible.builtin.group:
    name: "{{ prometheus_user }}"
    state: present
  run_once: true
  delegate_to: "{% if groups['monitoring'] | length > 0 %}{{groups['monitoring'][0]}}{% else%}127.0.0.1{% endif %}"

- name: Create user for prometheus
  become: true
  user:
    name: "{{ prometheus_user }}"  # Username
    group: "{{ prometheus_user }}" # Group
    state: present  # Ensure the user is present
    createhome: no  # Create the user's home directory  
    shell: /usr/sbin/nologin
  run_once: true
  delegate_to: "{% if groups['monitoring'] | length > 0 %}{{groups['monitoring'][0]}}{% else%}127.0.0.1{% endif %}"

- name: Create installation folder in etc
  become: true
  file:
    path: "{{ prometheus_dest_dir }}"
    state: directory
    owner: "{{ prometheus_user }}" 
    group: "{{ prometheus_user }}"
    mode: '0775'
    recurse: yes
  run_once: true
  delegate_to: "{% if groups['monitoring'] | length > 0 %}{{groups['monitoring'][0]}}{% else%}127.0.0.1{% endif %}"

- name: Create data folder
  become: true
  file:
    path: "{{ prometheus_data_dir }}"
    state: directory
    owner: "{{ prometheus_user }}" 
    group: "{{ prometheus_user }}"     
    mode: '0775'
    recurse: yes
  run_once: true
  delegate_to: "{% if groups['monitoring'] | length > 0 %}{{groups['monitoring'][0]}}{% else%}127.0.0.1{% endif %}"

- name: Ensuring the prometheus targets dir
  become: true
  file:
    path: "{{ prometheus_targets_dir }}"
    state: directory
    owner: "{{ prometheus_user }}" 
    group: "{{ prometheus_user }}"    
    mode: '0777'
  run_once: true
  delegate_to: "{% if groups['monitoring'] | length > 0 %}{{groups['monitoring'][0]}}{% else%}127.0.0.1{% endif %}"

- name: Download/unarchive Packages for prometheus
  become: true
  unarchive:
    src: "{{ prometheus_download_url }}"
    dest: /tmp
    owner: "{{ prometheus_user }}" 
    group: "{{ prometheus_user }}" 
    remote_src: true
    creates: "{{ prometheus_download_dir }}"
  run_once: true
  delegate_to: "{% if groups['monitoring'] | length > 0 %}{{groups['monitoring'][0]}}{% else%}127.0.0.1{% endif %}"

- name: Copying the service binary for prometheus
  become: true
  copy:
    src: "{{ prometheus_download_dir }}/"
    dest: /usr/local/bin/
    owner: "{{ prometheus_user }}" 
    group: "{{ prometheus_user }}"    
    mode: '0775'
    remote_src: true
  with_items:
   - prometheus
   - promtool 
  run_once: true
  delegate_to: "{% if groups['monitoring'] | length > 0 %}{{groups['monitoring'][0]}}{% else%}127.0.0.1{% endif %}"
     
- name: Copying the console binary
  become: true
  copy:
    src: "{{ prometheus_download_dir }}/"
    dest: "{{ prometheus_dest_dir }}"
    owner: "{{ prometheus_user }}" 
    group: "{{ prometheus_user }}"    
    mode: '0775'
    remote_src: true
  with_items:
   - consoles
   - console_libraries 
  run_once: true
  delegate_to: "{% if groups['monitoring'] | length > 0 %}{{groups['monitoring'][0]}}{% else%}127.0.0.1{% endif %}"

- name: Removing the tar file of prometheus
  become: true
  file:
    path: "{{ prometheus_download_dir }}"
    state: absent
  run_once: true
  delegate_to: "{% if groups['monitoring'] | length > 0 %}{{groups['monitoring'][0]}}{% else%}127.0.0.1{% endif %}"

- name: Create prometheus systemd service file
  become: true
  template:
    src: templates/prometheus.service.j2
    dest: "{{ service_dest_dir }}/prometheus.service"   
  run_once: true
  delegate_to: "{% if groups['monitoring'] | length > 0 %}{{groups['monitoring'][0]}}{% else%}127.0.0.1{% endif %}"

- name: Copying the scrape config
  become: true
  template:
    src: templates/prometheus.yml.j2
    dest: "{{ prometheus_dest_dir }}/prometheus.yml"
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_user }}"
    mode: '0775'
  run_once: true
  delegate_to: "{% if groups['monitoring'] | length > 0 %}{{groups['monitoring'][0]}}{% else%}127.0.0.1{% endif %}"
  
- name: Copying the rules recording file
  become: true
  template:
    src: files/recording_rules.yml
    dest: "{{ prometheus_dest_dir }}/recording_rules.yml"
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_user }}"
    mode: '0775'
  run_once: true
  delegate_to: "{% if groups['monitoring'] | length > 0 %}{{groups['monitoring'][0]}}{% else%}127.0.0.1{% endif %}"

- name: restart prometheus
  become: true
  service: 
    name: prometheus 
    state: restarted
    daemon_reload: yes
    enabled: yes 
  run_once: true
  delegate_to: "{% if groups['monitoring'] | length > 0 %}{{groups['monitoring'][0]}}{% else%}127.0.0.1{% endif %}"
