--- 

- include_tasks: oraclelinux.yml
  when: ansible_os_family == 'RedHat' and ansible_distribution == 'OracleLinux'

#- include_tasks: centos-7.yml
#  when: ansible_os_family == 'RedHat' and ansible_distribution == 'CentOS' and ansible_distribution_major_version == '7'

- include_tasks: ubuntu.yml
  when: ansible_os_family == 'Debian'
