---
- ansible.builtin.include_tasks: oraclelinux.yml
  when: ansible_facts['os_family'] == 'RedHat' and ansible_facts['distribution'] == 'OracleLinux'

#- include_tasks: centos-7.yml
#  when: ansible_facts['os_family'] == 'RedHat' and ansible_facts['distribution'] == 'CentOS' and ansible_facts['distribution_major_version'] == '7'

- ansible.builtin.include_tasks: ubuntu.yml
  when: ansible_facts['os_family'] == 'Debian'
