---
- block:

  - name: Install yum utils
    yum:
      name: yum-utils
      state: latest

  - name: Add centos-extras repo required for docker-ce
    become: true
    yum_repository: 
      name: centos-extras
      description: Centos extras - $basearch
      baseurl: http://mirror.centos.org/centos/{{ ansible_distribution_major_version }}/extras/x86_64
      enabled: 1
      gpgcheck: 0

  - name: Add docker-ce repository
    become: true
    yum_repository: 
      name: docker-ce
      description: Docker CE Stable - $basearch
      baseurl: https://download.docker.com/linux/centos/{{ ansible_distribution_major_version }}/$basearch/stable
      enabled: 1
      gpgcheck: 1
      gpgkey: https://download.docker.com/linux/centos/gpg

  - name: Install Docker
    ansible.builtin.yum:
      name:
        - docker-ce
        - docker-ce-cli
        - containerd.io
      state: latest
      update_cache: true

  - name: Start Docker
    ansible.builtin.service:
      name: "docker"
      enabled: true
      state: started

  - name: Enable service containerd
    ansible.builtin.service:
      name: containerd
      enabled: yes



