---
- name: Get the openmpi version
  ansible.builtin.command:
    cmd: ls /usr/mpi/gcc/
  register: openmpi
  failed_when: false

- name: Check if mpivars.sh exists
  ansible.builtin.stat:
    path: /usr/mpi/gcc/{{ openmpi.stdout_lines[0] }}/bin/mpivars.sh
  register: mpivars
  when: openmpi.stdout_lines | length > 0

- name: Create mpivars.sh
  become: true
  ansible.builtin.template:
    src: mpivars.j2
    dest: /usr/mpi/gcc/{{ openmpi.stdout_lines[0] }}/bin/mpivars.sh
    force: true
    owner: root
    group: root
  when: openmpi.stdout_lines | length > 0 and not mpivars.stat.exists
