---
- name: Create /etc/opt/oci-hpc/passwords/
  become: true
  file:
    path: /etc/opt/oci-hpc/passwords/
    state: directory
    owner: "{{ ansible_user }}"
    mode: 0770
    group: "{{ ansible_user }}"
    recurse: yes
