- include_vars: /opt/oci-hpc/playbooks/roles/openldap/vars/debian_vars.yml
  when: ansible_distribution == 'Ubuntu'

- include: el-7.yml
  when: ansible_os_family == 'RedHat' and ansible_distribution_major_version == '7'

- include: el-8.yml
  when: ansible_os_family == 'RedHat' and ansible_distribution_major_version == '8'

- include: debian.yml
  when: ansible_distribution == 'Ubuntu'