ssl_cert_path: '/etc/ssl/certs'
ssl_cert_group: 'ldap'

openldap_tls_cacrt: '{{ ssl_ca_cert }}'
openldap_tls_crt: '{{ ssl_cert_path }}/{{ ansible_fqdn }}.crt'
openldap_tls_key: '{{ ssl_cert_path }}/{{ ansible_fqdn }}.key'
