- include_tasks: el.yml
  when: ansible_os_family == 'RedHat' and ansible_distribution_major_version == '8'

- include_tasks: ubuntu.yml
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_major_version == "22"
