---
- name: create .oci directory
  become: true
  file:
    path: /home/{{ ansible_user }}/.oci
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0775

- name: Generate config file
  become: true
  template:
    src: 'config.j2'
    dest: '/home/{{ ansible_user }}/.oci/config'
    mode: 0600
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: delete --auth in create_cluster.sh
  become: true
  replace:
    path: /opt/oci-hpc/bin/create_cluster.sh
    regexp: '--auth instance_principal'
    replace: ''