---
- name: Install prometheus_client python package
  ansible.builtin.pip:
    name: prometheus_client 
    executable: /usr/bin/pip3  
  become: yes

- name: Copy service file to scripts directory
  copy:
    src: nvlink_counters_exporter.py
    dest: /usr/local/bin
    mode: 0755
  become: yes

- name: Render systemd service file
  become: true
  template: 
    src: nvlink-exporter.service.j2
    dest: /etc/systemd/system/nvlink-exporter.service
    force: yes
    backup: yes
    owner: prometheus
    group: prometheus
    mode: 0744

- name: Restart nvlink exporter
  become: true
  service:
    name: nvlink-exporter
    state: restarted
    enabled: yes
