---
- name: Create /etc/opt/oci-hpc/passwords/influxdb
  become: true
  file: 
    path: /etc/opt/oci-hpc/passwords/influxdb
    state: directory
    owner: opc
    mode: 0770
    group: opc
    recurse: yes

- name: Generate password for Influx admin and save it to /etc/opt/oci-hpc/passwords
  set_fact:
    tmp_pwd: "{{ lookup('password',
                          '/etc/opt/oci-hpc/passwords/influxdb/root.txt
                          chars=ascii_letters,digits,hexdigits') }}"

- name: Get influx password from /etc/opt/oci-hpc/passwords
  set_fact:
    influx_admin_pwd: "{{ lookup('password',
                          '/etc/opt/oci-hpc/passwords/influxdb/root.txt  
                           chars=ascii_letters,digits,hexdigits') }}"

- name: Add influxdb repository
  become: true
  yum_repository: 
    name: influxdb
    description: InfluxDB Repository - RHEL $releasever
    baseurl: https://repos.influxdata.com/rhel/{{ ansible_distribution_major_version }}/$basearch/stable
    enabled: 1
    gpgcheck: 1
    gpgkey: https://repos.influxdata.com/influxdb.key

- name: Install InfluxDB
  become: true
  yum: 
    name: influxdb
    state: latest

- name: Start InfluxDB
  become: true
  service: 
    name: influxdb
    state: started
    enabled: true

- name: Install any necessary PIP dependencies
  become: true
  yum: 
    name: python-pip
    state: present

- name: Set configuration directory path
  become: true
  file:
    path: "{{ influxdb_configuration_dir }}"
    state: directory

- name: Set templatized InfluxDB configuration
  become: true
  template: 
    src: influxdb.conf.j2 
    dest: "{{ influxdb_configuration_dir }}/influxdb.conf"
    force: yes
    backup: yes
    owner: influxdb
    group: influxdb
    mode: 0744
  register: influx_config
  notify: restart influxdb


