---
- name: Add InfluxData's key
  become: true
  apt_key:
    state: present
    url: https://repos.influxdata.com/influxdata-archive_compat.key

- name: Manage InfluxData APT repositories
  become: true
  apt_repository:
    repo: deb https://repos.influxdata.com/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable
    state: present

- name: Install InfluxDB
  vars: 
    package_name: 
      - influxdb
    package_state: latest
  include_role: 
    name: safe_yum

- name: force influxdb gid 997
  become: true
  lineinfile:
    path: /etc/group
    state: present
    regexp: '^influxdb:x:(.*)$'
    line: 'influxdb:x:997:'
    backrefs: yes

- name: force influxd uid 997
  become: true
  lineinfile:
    path: /etc/passwd
    state: present
    regexp: '^influxdb:x:(.*)$'
    line: 'influxdb:x:997:997::/var/lib/influxdb:/bin/false'
    backrefs: yes

- name: restart influxdb
  become: true
  service:
    name: influxdb
    state: restarted
    enabled: yes

- name: install influx pip
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3
  pip:
    name: influxdb
    executable: pip3
