#%Module
proc ModulesHelp { } {
   puts stderr "This module adds Open MPI/SHMEM v4.0.2 to various paths"
}

set             topdir             /opt/openmpi/4.0.2/
setenv          MPI_ROOT           $topdir
set-alias       mpirun             {/opt/openmpi/4.0.2/bin/mpirun -mca btl self -x UCX_TLS=rc,self,sm -x HCOLL_ENABLE_MCAST_ALL=0 -mca coll_hcoll_enable 0 -x UCX_IB_TRAFFIC_CLASS=105 -x UCX_IB_GID_INDEX=3 }
module-whatis   "Sets up Open MPI/SHMEM v4.0.2 in your enviornment"

prepend-path PATH "/opt/openmpi/4.0.2/bin/"
prepend-path LD_LIBRARY_PATH /opt/openmpi/4.0.2/lib
prepend-path MANPATH /opt/openmpi/4.0.2/man
