---

- name: Add to the gres.conf file on the controller.
  become: true
  blockinfile:
    block: "{{ lookup('template', 'gres.conf.j2') }}"
    path: "{{ slurm_conf_path }}/gres.conf"
    marker: "### {mark} {{new_compute_info[item].hostname}}"
  delegate_to: 127.0.0.1
  when: "'GPU' in new_compute_info[item].shape"
  with_items: "{{ new_compute_info }}"

# - name: Make a list of nodes to add
#   set_fact: nodes_to_add="{{ new_compute_info | map(attribute='hostname') | list }}"
#   run_once: true

- name: Populate nodes_to_add with cluster_name as key and list of hostnames as value
  set_fact:
    nodes_to_add: "{{ nodes_to_add | default({}) | combine({ new_compute_info[item].cluster_name: (nodes_to_add[new_compute_info[item].cluster_name] | default([])) + [new_compute_info[item].hostname] }) }}"
  with_items: "{{ new_compute_info }}"
- name: Get nodes from Cluster Switch
  block:
    - name: Get nodes from topology.conf
      shell: "cat {{ slurm_conf_path }}/topology.conf | grep \"SwitchName={{item}}\""
      register: cluster_switch
    - name: Get cluster_hostlist
      command: "scontrol show hostname {{cluster_switch.stdout.split('Nodes=')[1]}}"
      register: cluster_hostlist
    - name: Create new cluster_hostlist
      command: "scontrol show hostlistsorted {{cluster_hostlist.stdout_lines | union(nodes_to_add[item]) | join(',') }}"
      register: cluster_hostlist_condensed_results
  rescue:
    - name: Create existing cluster list
      command: "scontrol show hostlistsorted {{ nodes_to_add[item] | join(',') }}"
      register: cluster_hostlist_condensed_results
  with_items: nodes_to_add.keys()

- name: add nodes to Switch
  become: true
  lineinfile:
    path: "{{ slurm_conf_path }}/topology.conf"
    regexp: "SwitchName={{item}}\\sNodes.*"
    line: "SwitchName={{item}} Nodes={{ cluster_hostlist_condensed_results.item.stdout }}"
    state: present
  notify: reconfigure slurm
  with_items: nodes_to_add.keys()

- name: run handlers
  meta: flush_handlers