---
- name: Add Grafana repository (EL/OL)
  become: true
  ansible.builtin.yum_repository:
    name: grafana
    description: Grafana
    baseurl: https://rpm.grafana.com
    enabled: 1
    gpgcheck: 1
    repo_gpgcheck: 1
    gpgkey: https://rpm.grafana.com/gpg.key
    sslverify: 1
    sslcacert: /etc/pki/tls/certs/ca-bundle.crt

- name: Install grafana and tempo
  vars:
    package_name:
      - grafana
      - tempo
    package_state: present
  include_role:
    name: safe_yum

- name: Start and enable Grafana service
  become: true
  service:
    name: grafana-server
    state: restarted
    enabled: true

- name: Setup Grafana
  include_tasks: setup_grafana.yml
