---
- name: add grafana repository
  become: true
  yum_repository: 
    name: grafana
    description: grafana
    baseurl: https://packages.grafana.com/oss/rpm
    repo_gpgcheck: 1
    enabled: 1
    gpgcheck: 1
    gpgkey: https://packages.grafana.com/gpg.key
    sslverify: 1
    sslcacert: /etc/pki/tls/certs/ca-bundle.crt

- name: install grafana
  become: true
  yum: 
    name: grafana
    state: latest

- name: start grafana
  become: true
  service: 
    name: grafana-server
    state: restarted
    enabled: true
    
