---
- name: Add Grafana GPG key
  become: true
  apt_key:
    url: https://packages.grafana.com/gpg.key
    state: present
    keyring: /etc/apt/trusted.gpg.d/grafana-archive-keyring.gpg

- name: Add Grafana repository
  become: true
  apt_repository:
    repo: 'deb https://packages.grafana.com/oss/deb stable main'
    state: present
    filename: 'grafana'

- name: Update apt cache
  become: true
  apt:
    update_cache: yes

- name: Install Grafana and Tempo
  vars:
    package_name:
      - grafana
      - tempo
    package_state: present
  include_role:
    name: safe_yum

- name: Start and enable Grafana service
  become: true
  service:
    name: grafana-server
    state: restarted
    enabled: true

- name: Setup Grafana
  include_tasks: setup_grafana.yml