---

- name: Ensure db directory exists
  file:
    path: "/opt/oci-hpc/db"
    state: directory
    owner: '{{ ansible_user }}'
    group: '{{ ansible_user }}'

- name: Generate env file
  template: 
    src: get_nodes_from_db.py
    dest: /opt/oci-hpc/bin/get_nodes_from_db.py
    owner: '{{ ansible_user }}'
    group: '{{ ansible_user }}'
    mode: 0775

- name: get All nodes with this controller
  shell: "source /opt/oci-hpc/venv/bin/activate; /opt/oci-hpc/venv/bin/python3 /opt/oci-hpc/bin/get_nodes_from_db.py"
  register: get_cluster_nodes_results

- name: Convert the Python script output to a list of dictionaries
  set_fact:
    query_results: "{{ get_cluster_nodes_results.stdout | from_json }}"

- name: Create an empty dir of all new compute nodes
  set_fact:
    new_compute_info: {}

- name: Create a dictionary from curl results of all new compute nodes
  set_fact:
    new_compute_info: "{{ new_compute_info  | default({}) | combine({item.ip_address: item}) }}"
  loop: "{{ query_results }}"
  when: item.role == "compute" and item.controller_status == "configuring"

- name: Create an empty dir of all new compute nodes
  set_fact:
    new_hosts_info: {}

- name: Create a dictionary from curl results of all new compute nodes
  set_fact:
    new_hosts_info: "{{ new_compute_info  | default({}) | combine({item.ip_address: item}) }}"
  loop: "{{ query_results }}"
  when: item.role != "compute" and item.controller_status == "configuring"

- name: Create an empty dir of all new compute nodes
  set_fact:
    remove_compute_info: {}

- name: Create a dictionary from curl results of all new compute nodes
  set_fact:
    remove_compute_info: "{{ new_compute_info  | default({}) | combine({item.ip_address: item}) }}"
  loop: "{{ query_results }}"
  when: item.role == "compute" and item.controller_status == "terminating"

- name: Create an empty dir of all new compute nodes
  set_fact:
    all_hosts_info: {}

- name: Create a dictionary from curl results of all new compute nodes
  set_fact:
    all_hosts_info: "{{ new_compute_info  | default({}) | combine({item.ip_address: item}) }}"
  loop: "{{ query_results }}"