---
- name: run compute directives
  vars:
    slurm_repos: "epel,ol7_developer_EPEL"
  include_tasks: "common.yml"

- name: run compute directives
  vars:
    slurm_repos: "epel,ol7_developer_EPEL"
  include_tasks: "compute.yml"
- name: cleanup
  include_tasks: cleanup.yml