---
- name: run compute directives
  vars:
    slurm_repos: "ol8_developer_EPEL,ol8_codeready_builder"
  include_tasks: "common.yml"

- name: run compute directives
  vars:
    slurm_repos: "ol8_developer_EPEL,ol8_codeready_builder"
  include_tasks: "compute{{rack_aware_playbook_suffix}}.yml"

- name: cleanup
  include_tasks: cleanup.yml