---
  queues:
    - name: ${queue}
      default: true
      instance_types: 
        - name: default
          default: true
          shape: ${shape}
          change_hostname: ${change_hostname}
          hostname_convention: ${hostname_convention} # Will add -INDEX with the index of the IP in the subnet
          permanent: true
          rdma_enabled: ${rdma_enabled}
          stand_alone: ${stand_alone}
          max_number_nodes: 0
          region: ${region}
          availability_domain: ${ad}
          private_subnet: ${private_subnet}
          private_subnet_id: ${private_subnet_id}
          image_id: ${image}
          target_compartment_id: ${targetCompartment}
          boot_volume_size: ${boot_volume_size}
          use_marketplace_image: ${use_marketplace_image}
          instance_pool_ocpus: ${instance_pool_ocpus}
          instance_pool_memory: ${instance_pool_memory}
          instance_pool_custom_memory: ${instance_pool_custom_memory}
          marketplace_listing: ${marketplace_listing}
          hyperthreading: ${hyperthreading}
          preemptible: ${preemptible}
%{ if ondemand_partition }
    - name: ondemand
      default: false
      instance_types: 
        - name: on-demand
          default: false
          shape: ${shape}
          change_hostname: true
          hostname_convention: GPU-OD # Will add -INDEX with the index of the IP in the subnet
          permanent: false
          rdma_enabled: ${rdma_enabled}
          stand_alone: true
          max_number_nodes: ${ondemand_partition_count}
          region: ${region}
          availability_domain: ${ad}
          private_subnet: ${private_subnet}
          private_subnet_id: ${private_subnet_id}
          image_id: ${image}
          target_compartment_id: ${targetCompartment}
          boot_volume_size: ${boot_volume_size}
          use_marketplace_image: ${use_marketplace_image}
          instance_pool_ocpus: ${instance_pool_ocpus}
          instance_pool_memory: ${instance_pool_memory}
          instance_pool_custom_memory: ${instance_pool_custom_memory}
          marketplace_listing: ${marketplace_listing}
          hyperthreading: ${hyperthreading}
          preemptible: ${preemptible}
%{ endif }
  login:
    - name: login_default
      default: true
      shape: ${login_shape}
      change_hostname: false
      hostname_convention: login # Will add -INDEX with the index of the IP in the subnet
      permanent: true
      rdma_enabled: false
      stand_alone: true
      max_number_nodes: 0
      region: ${region}
      availability_domain: ${login_ad}
      private_subnet: ${public_subnet}
      private_subnet_id: ${public_subnet_id}
      image_id: ${login_image}
      target_compartment_id: ${targetCompartment}
      boot_volume_size: ${login_boot_volume_size}
      use_marketplace_image: ${use_marketplace_image_login}
      instance_pool_ocpus: ${login_instance_pool_ocpus}
      instance_pool_memory: ${login_instance_pool_memory}
      instance_pool_custom_memory: ${login_instance_pool_custom_memory}
      marketplace_listing: ${marketplace_listing_login}
      hyperthreading: false
      preemptible: false