---
- name: install GIT
  vars: 
    package_name: 
      - git
  include_role: 
    name: safe_yum

- name: Development Tools" 
  vars: 
    package_name: 
      - "@Development Tools"
  include_role: 
    name: safe_yum

- name: Check if SPACK directory is present
  stat:
    path: "/config/3rdparty/spack"
  register: spack_present

- name: Clone SPACK
  git: 
    repo: "{{ spack_repo }}"
    dest: "/config/3rdparty/spack"
    update: no
  run_once: true
  when: not spack_present.stat.exists

- name: Add SPACK initialization 
  template: 
    src: templates/spack.j2
    dest: /etc/profile.d/spack.sh
    owner: root
    group: root
    mode: '0755' 
  become: true
