---
- name: install GIT
  vars: 
    package_name: 
      - git
  include_role: 
    name: safe_yum

- name: Development Tools" 
  vars: 
    package_name: 
      - "@Development Tools"
  include_role: 
    name: safe_yum

- name: Clone SPACK
  git: 
    repo: "{{ spack_repo }}"
    dest: "{{ cluster_nfs_path }}/spack"
    update: no
  run_once: true

- name: Add SPACK initialization 
  template: 
    src: templates/spack.j2
    dest: /etc/profile.d/spack.sh
    owner: root
    group: root
    mode: '0755' 
  become: true
