- include_tasks: el.yml
  when: ansible_os_family == 'RedHat'

- include_tasks: debian.yml
  when: ansible_distribution == 'Ubuntu'

- include_tasks: debian.yml
  when: ansible_distribution == 'Debian'
