---
- name: restart slurmctld
  service:
    name: "{{ slurmctld_service }}"
    state: restarted
    daemon_reload: yes
    enabled: yes

- name: restart slurmdbd
  service:
    name: "{{ slurmdbd_service }}"
    state: restarted
    daemon_reload: yes
    enabled: yes

- name: restart slurmrestd
  service:
    name: "{{ slurmrestd_service }}"
    state: restarted
    daemon_reload: yes
    enabled: yes