---
- name: Restart slurmctld
  service:
    name: "{{ slurmctld_service }}"
    state: restarted
    daemon_reload: true
    enabled: true

- name: Restart slurmdbd
  service:
    name: "{{ slurmdbd_service }}"
    state: restarted
    daemon_reload: true
    enabled: true
  when: not slurm_federation | default(false) | bool

- name: Restart slurmrestd
  service:
    name: "{{ slurmrestd_service }}"
    state: restarted
    daemon_reload: true
    enabled: true
