---
- name: Check the oci-cn-auth version
  shell: cat /opt/oci-hpc/oci-cn-auth/.version-oci_cn_auth
  register: version

- name: Download current oci-cn-auth .deb if it is not the current version
  get_url:
    url: "{{download_link}}oci-cn-auth_{{current_version}}_all.deb"
    dest: "/tmp/"
  when: ansible_os_family == 'Debian' and version.stdout != current_version

- name: Install current oci-cn-auth .deb if it is not the current version
  vars: 
    deb_name: 
      - "/tmp/oci-cn-auth_{{current_version}}_all.deb"
    package_state: present
  include_role: 
    name: safe_yum
  when: ansible_os_family == 'Debian' and version.stdout != current_version

- name: Download current oci-cn-auth .rpm if it is not the current version
  get_url:
    url: "{{download_link}}oci-cn-auth-{{current_version}}.el{{ansible_distribution_major_version}}.noarch.rpm"
    dest: "/tmp/"
  when: ansible_os_family == 'RedHat' and version.stdout != current_version

- name: Install current oci-cn-auth .rpm if it is not the current version
  vars: 
    package_name: 
      - "/tmp/oci-cn-auth-{{current_version}}.el{{ansible_distribution_major_version}}.noarch.rpm"
    package_state: present
  include_role: 
    name: safe_yum
  when: ansible_os_family == 'RedHat' and version.stdout != current_version