---
- name: Make sure /opt/oci-hpc/bin/ exists
  become: true
  ansible.builtin.file:
    path: /opt/oci-hpc/bin/
    state: directory
    recurse: true
    mode: "0755"
    owner: "{{ ansible_user }}"
    group: "{{ privilege_group_name }}"

- name: Copy node_ordering_by_rack.py
  block:
    - name: Copy node_ordering_by_rack.py
      become: true
      ansible.builtin.copy:
        src: node_ordering_by_rack.py
        dest: /opt/oci-hpc/bin/
        owner: "{{ ansible_user }}"
        group: "{{ privilege_group_name }}"
        mode: "0755"
  rescue:
    - name: Copy node_ordering_by_rack.py
      become: true
      ansible.builtin.copy:
        src: node_ordering_by_rack.py
        dest: /opt/oci-hpc/bin/
        owner: "{{ ansible_user }}"
        group: "{{ privilege_group_name }}"
        mode: "0755"
      ignore_errors: true
