- name: install pssh and parallel-ssh
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3
  pip:
    name: ['pssh', 'parallel-ssh']
    executable: pip3
    state: latest
  ignore_errors: yes

- name: Make sure /opt/oci-hpc/bin/ exists
  become: true
  file:
    path: /opt/oci-hpc/bin/
    state: directory
    recurse: yes
    mode: '0755'
    owner: "{{ ansible_user }}"
    group: "{{ privilege_group_name }}"

- name: Copy node_ordering_by_rack.py
  block:
    - name: copy node_ordering_by_rack.py
      become: true
      copy:
        src: node_ordering_by_rack.py
        dest: /opt/oci-hpc/bin/
        owner: "{{ ansible_user }}"
        group: "{{privilege_group_name}}"
        mode: '0755'
  rescue:
    - name: copy node_ordering_by_rack.py
      become: true
      copy:
        src: node_ordering_by_rack.py
        dest: /opt/oci-hpc/bin/
        owner: "{{ ansible_user }}"
        group: "{{privilege_group_name}}"
        mode: '0755'
      ignore_errors: yes
  