---
- name: Make sure python OpenSSL and parallel ssh is installed
  vars: 
    package_name: 
      - python-openssl
      - python-cryptography
      - parted
      - pssh
      - pdsh
      - jq
      - python3-pip
    package_state: latest
  include_role: 
    name: safe_yum

- name: Upgrade Pip3
  become: true
  pip:
    name: [pip]
    state: latest
    executable: pip3
  ignore_errors: yes

- name: Install the 'paramiko' package
  become: true
  pip: 
    name: paramiko
    state: latest
    executable: pip3
  ignore_errors: yes