---
- name: Make sure python OpenSSL is installed
  vars: 
    package_name: 
      - python-openssl
      - python-cryptography
      - parted
    package_state: latest
  include_role: 
    name: safe_yum

