---
- name: Make sure python OpenSSL and parallel ssh is installed
  vars: 
    package_name: 
      - python-openssl
      - python-cryptography
      - parted
      - pssh
      - pdsh
    package_state: latest
  include_role: 
    name: safe_yum

