---
- name: Make sure python OpenSSL and parallel ssh is installed
  vars:
    package_name:
      - python-openssl
      - python-cryptography
      - parted
      - pssh
      - pdsh
      - jq
      - python3-pip
    package_state: latest
  ansible.builtin.include_role:
    name: safe_yum

- name: Upgrade Pip3
  become: true
  ansible.builtin.pip:
    name: [pip]
    state: latest
    executable: /usr/bin/pip3
  ignore_errors: true
