---
- name: Make sure python OpenSSL is installed
  vars: 
    package_name: 
      - pyOpenSSL
      - python2-cryptography
      - python3-oci-cli
    package_state: latest
  include_role: 
    name: safe_yum
  ignore_errors: true
