---
- name: Make sure python OpenSSL and parallel ssh is installed
  vars: 
    package_name: 
      - pyOpenSSL
      - python2-cryptography
      - python3-oci-cli
      - pssh
      - pdsh
      - python3-pip
    package_state: latest
  include_role: 
    name: safe_yum
  ignore_errors: true
