---
- name: Make sure python OpenSSL and parallel ssh is installed
  vars: 
    package_name: 
      - pyOpenSSL
      - python2-cryptography
      - python3-oci-cli
      - pssh
      - pdsh
      - python3-pip
    package_state: latest
  include_role: 
    name: safe_yum
  ignore_errors: true

- name: Upgrade Pip3
  become: true
  pip:
    name: [pip]
    state: latest
    executable: pip3
  ignore_errors: yes
  
- name: install oci-cli latest version
  become: true
  pip:
    name: [oci-cli]
    state: latest
    executable: pip3
  ignore_errors: yes
  when: ('controller' in group_names)
