- include_tasks: ol-7.yml
  when: ansible_os_family == 'RedHat' and ansible_distribution == 'OracleLinux' and ansible_distribution_major_version == '7'

- include_tasks: ol-8.yml
  when: ansible_os_family == 'RedHat' and ansible_distribution == 'OracleLinux' and ansible_distribution_major_version == '8'

- include_tasks: centos-7.yml
  when: ansible_os_family == 'RedHat' and ansible_distribution == 'CentOS' and ansible_distribution_major_version == '7'

- include_tasks: ubuntu.yml
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_major_version < '22'

- include_tasks: ubuntu-2204.yml
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_major_version == '22'

- include_tasks: debian.yml
  when: ansible_distribution == 'Debian'