---
- name: Enable ol8_developer_EPEL repo
  shell: yum-config-manager --enable ol8_developer_EPEL

- name: Make sure python OpenSSL and parallel ssh is installed
  vars: 
    package_name:
      #- pyOpenSSL
      #- python2-cryptography
      - python3-oci-cli
      - pssh
      - pdsh
      - python3-pip
    package_state: latest
    package_repo: "ol8_developer_EPEL"
  include_role: 
    name: safe_yum
  ignore_errors: true

- name: install oci-cli latest version
  become: true
  pip:
    name: [oci-cli]
    state: latest
    executable: pip3
  ignore_errors: yes
  when: ('bastion' in group_names)