---
- name: Restart sshd
  listen: Restart login services
  service:
    name: sshd
    state: restarted
    enabled: true
  when: not ( ansible_distribution == 'Ubuntu' and ansible_distribution_major_version | int >= 24 )

- name: Restart sssd
  listen: Restart ns daemons
  service:
    name: sssd
    state: restarted
    enabled: true

- name: Restart nscd
  listen: Restart ns daemons
  systemd:
    name: nscd
    state: restarted
    daemon_reload: true
    enabled: true

- name: restart_nslcd
  listen: Restart ns daemons
  service:
    name: nslcd
    state: restarted
    enabled: true

- name: restart_systemd_logind
  listen: Restart login services
  service:
    name: systemd-logind
    state: restarted
    enabled: true
