---
- name: "Safe Yum install of latest {{ package_name }}"
  block:
    - name: "Yum first try {{ package_name }}"
      vars:
        ansible_python_interpreter: /usr/bin/python3
      become: true
      ansible.builtin.yum:
        enablerepo: "{{ package_repo | default('None') }}"
        name: "{{ package_name }}"
        state: "{{ package_state | default('present') }}"
        update_cache: "{{ package_cache | default('false') | bool }}"
        lock_timeout: 180
        disable_gpg_check: "{{ disable_gpg_check_var | default('false') | bool }}"
      when: package_repo|default('None') != 'None'
      register: yum_sleeper
      retries: 5
      delay: 10
      until: yum_sleeper is not failed

    - name: "Yum first try {{ package_name }}"
      vars:
        ansible_python_interpreter: /usr/bin/python3
      become: true
      ansible.builtin.yum:
        name: "{{ package_name }}"
        state: "{{ package_state | default('present') }}"
        update_cache: "{{ package_cache | default('false') | bool }}"
        lock_timeout: 180
        disable_gpg_check: "{{ disable_gpg_check_var | default('false') | bool }}"
      when: package_repo|default('None') == 'None'
      register: yum_sleeper
      retries: 5
      delay: 10
      until: yum_sleeper is not failed

  rescue:
    # There seem to be a yum process from the cloud-agent that is randomly hanging and is blocking for other tasks.
    - name: Make sure the yum cloud-agent process is destroyed.
      ansible.builtin.shell: "ps -ef | grep /v[a]r/lib/oracle-cloud-agent/plugins/unifiedmonitoring/temp-unified-monitoring.rpm | head -n 1 | awk '{print $2}'"
      register: yum_process

    - name: Kill Yum Process
      ansible.builtin.command: "sudo kill -9 {{ yum_process.stdout }}"
      when: yum_process.stdout != ""
      ignore_errors: true

    - name: "Yum 2nd try {{ package_name }}"
      become: true
      vars:
        ansible_python_interpreter: /usr/bin/python3
      ansible.builtin.yum:
        enablerepo: "{{ package_repo | default('None') }}"
        name: "{{ package_name }}"
        state: "{{ package_state | default('present') }}"
        update_cache: "{{ package_cache | default('false') | bool }}"
        lock_timeout: 90
        disable_gpg_check: "{{ disable_gpg_check_var | default('false') | bool }}"
      register: packages_output
      retries: 5
      delay: 10
      until: packages_output is not failed
      when: package_repo|default('None') != 'None'

    - name: "Yum 2nd try {{ package_name }}"
      vars:
        ansible_python_interpreter: /usr/bin/python3
      become: true
      ansible.builtin.yum:
        name: "{{ package_name }}"
        state: "{{ package_state | default('present') }}"
        update_cache: "{{ package_cache | default('false') | bool }}"
        lock_timeout: 90
      register: packages_output
      retries: 5
      delay: 10
      until: packages_output is not failed
      when: package_repo|default('None') == 'None'
