---
munge_conf_path: "/etc/munge"
slurm_spool_path: "/var/spool/slurmd"
slurm_conf_path: "/etc/slurm"
slurm_log_path: "/var/log/slurm"
slurm_exec: "/usr"
slurm_conf_file: slurm.conf.j2
slurm_job_container_conf_file: job_container.conf.j2
munge_log_path: "/var/log/munge"
munge_run_path: "/var/run/munge"
slurm_db_user: "slurm_accounting"
slurm_db_name: "slurm_accounting"
slurm_gid: 1501
slurm_uid: 1501
munge_gid: 1500
munge_uid: 1500
rack_aware_playbook_suffix: "{% if rack_aware|bool %}-rack-aware{% endif%}"
slurm_jwt_key_path: "{{ slurm_nfs_path }}/spool_{{ cluster_name }}/slurm/jwt_hs256.key"