groups:

- name: node_health
  rules:
  # Node memory and boot volume checks
  - record: node_disk_free_ok
    expr: avg by (hostname, cluster_name) (node_filesystem_avail_bytes{mountpoint="/",device=~"/dev/sd.*"}) >= bool 50 * 1024 * 1024 * 1024

  - record: node_memory_availability_ok
    expr: avg by (hostname, cluster_name) (node_memory_MemAvailable_bytes) >= bool 50 * 1024 * 1024 * 1024

  # GPU throttling checks
  - record: node_gpu_power_violation_ok
    expr: min by (hostname, cluster_name) (increase(DCGM_FI_DEV_POWER_VIOLATION[5m]) == bool 0)

  - record: node_gpu_board_limit_violation_ok  
    expr: min by (hostname, cluster_name) (increase(DCGM_FI_DEV_BOARD_LIMIT_VIOLATION[5m]) == bool 0)

  - record: node_gpu_thermal_violation_ok
    expr: min by (hostname, cluster_name) (increase(DCGM_FI_DEV_THERMAL_VIOLATION[5m]) == bool 0)

  - record: node_gpu_sync_boost_violation_ok
    expr: min by (hostname, cluster_name) (increase(DCGM_FI_DEV_SYNC_BOOST_VIOLATION[5m]) == bool 0)

  - record: node_gpu_reliability_violation_ok
    expr: min by (hostname, cluster_name) (increase(DCGM_FI_DEV_RELIABILITY_VIOLATION[5m]) == bool 0)

  # PCIe error checks
  - record: node_pcie_aer_correctable_errors_ok
    expr: min by (hostname, cluster_name) (increase(pcie_aer_correctable_error_count[5m]) == bool 0)

  - record: node_pcie_aer_fatal_errors_ok
    expr: min by (hostname, cluster_name) (increase(pcie_aer_fatal_error_count[5m]) == bool 0)

  - record: node_pcie_aer_nonfatal_errors_ok
    expr: min by(hostname, cluster_name) (increase(pcie_aer_nonfatal_error_count[5m]) == bool 0)

  - record: node_pcie_bus_inaccessible_ok
    expr: min by (hostname, cluster_name) (pcie_bus_inaccessible_status == bool 0)

  - record: node_pcie_bus_linkwidth_ok
    expr: min by (hostname, cluster_name) (pcie_bus_linkwidth_status == bool 0)

  # Health checks via custom metrics
  - record: node_rttcc_ok
    expr: min by(hostname, cluster_name) (rttcc_status == bool 0)

  - record: node_oca_ver_ok
    expr: oca_version * on(hostname, cluster_name) oca_version

  - record: node_rdma_device_status_ok
    expr: min by(hostname, cluster_name) (rdma_device_status)

  - record: node_check_bus_issue_count_ok
    expr: (check_bus_issue_count == bool 0) * on (hostname, cluster_name) (check_bus_issue_count == bool 0)

  - record: node_rdma_link_flapping_ok
    expr: min by(hostname, cluster_name) (rdma_link_noflap)

  - record: node_ecc_error_check_ok
    expr: (gpu_ecc_error_check) * on (hostname, cluster_name) (gpu_ecc_error_check)

  - record: node_gpu_row_remap_error_check
    expr: (gpu_row_remap_error_check== bool 0) * on (hostname, cluster_name) (gpu_row_remap_error_check== bool 0)

  - record: node_xid_error_check
    expr: (xid_error_check) * on (hostname, cluster_name) (xid_error_check)

  - record: node_up_check
    expr: (up{instance=~".*:9100$"}) * on (hostname, cluster_name) (up{instance=~".*:9100$"})

  # combine them: this will be 1 only if *all* success‑flags are 1
  - record: node_health_status
    expr: |
      (
        node_rttcc_ok or node_up_check
      )
      *
      (
        node_oca_ver_ok or node_up_check
      )
      *
      (
        node_rdma_device_status_ok or node_up_check
      )
      *
      (
        node_check_bus_issue_count_ok or node_up_check
      )
      *
      (
        node_rdma_link_flapping_ok or node_up_check
      )
      *
      (
        node_ecc_error_check_ok or node_up_check
      )
      *
      (
        node_gpu_row_remap_error_check or node_up_check
      )
      *
      (
        node_xid_error_check or node_up_check
      )
      *
      (
        node_gpu_power_violation_ok or node_up_check
      )
      *
      (
        node_gpu_board_limit_violation_ok or node_up_check
      )
      *
      (
        node_gpu_thermal_violation_ok or node_up_check
      )
      *
      (
        node_gpu_sync_boost_violation_ok or node_up_check 
      )
      *
      (
        node_gpu_reliability_violation_ok or node_up_check
      )
      *
      (
        node_pcie_aer_correctable_errors_ok or node_up_check
      )
      *
      (
        node_pcie_aer_fatal_errors_ok or node_up_check
      )
      *
      (
        node_pcie_aer_nonfatal_errors_ok or node_up_check
      )
      *
      (
        node_pcie_bus_inaccessible_ok or node_up_check
      )
      *
      (
        node_pcie_bus_linkwidth_ok or node_up_check
      )
      *
      (
        node_memory_availability_ok or node_up_check
      )
      *
      (
        node_disk_free_ok or node_up_check
      )
