---

- name: Ensure db directory exists
  file:
    path: "/opt/oci-hpc/db"
    state: directory
    owner: '{{ ansible_user }}'
    group: '{{ ansible_user }}'

- name: Generate env file
  template: 
    src: env.j2
    dest: /opt/oci-hpc/db/env

- name: Copy files
  become: true
  copy: 
    src: "initial.sql"
    dest: '/opt/oci-hpc/db/initial.sql'
    force: no
    owner: '{{ ansible_user }}'
    group: '{{ ansible_user }}'

- name: Get root password from /etc/opt/oci-hpc/passwords
  set_fact:
    mysql_root_pwd: "{{ lookup('password',
                          '/etc/opt/oci-hpc/passwords/mysql/root.txt  
                           chars=ascii_letters,digits') }}"

- name: Create database 'clusterDB'
  mysql_db:
    login_user: "root"
    login_password: "{{ mysql_root_pwd }}"
    name: clusterDB
    state: present

- name: Create database user with name 'clusterUser' and password
  mysql_user:
    login_user: "root"
    login_password: "{{ mysql_root_pwd }}"
    name: clusterUser
    password: Cluster1234!
    priv: clusterDB.*:SELECT,INSERT,UPDATE,DELETE
    state: present

- name: Create initial DB
  shell: "source /opt/oci-hpc/db/env; mysql -u root -p{{ mysql_root_pwd }} < /opt/oci-hpc/db/initial.sql"
  ignore_errors: yes

- name: Copying the DB Scraper config
  become: true
  template:
    src: nodes_update.py.j2
    dest: "/opt/oci-hpc/bin/nodes_update.py"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0775'  

- name: Copying the file to manually add a node to the queue
  become: true
  template:
    src: add_nodes_to_queue.py.j2
    dest: "/opt/oci-hpc/bin/add_nodes_to_queue.py"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0775'  

- name: Ensure db directory exists
  file:
    path: "/opt/oci-hpc/db"
    state: directory
    owner: '{{ ansible_user }}'
    group: '{{ ansible_user }}'

- name: Generate env file
  template: 
    src: get_nodes_from_db.py
    dest: /opt/oci-hpc/bin/get_nodes_from_db.py
    owner: '{{ ansible_user }}'
    group: '{{ ansible_user }}'
    mode: 0775

- name: Generate nodes_status file
  template: 
    src: nodes_status.py
    dest: /opt/oci-hpc/bin/nodes_status.py
    owner: '{{ ansible_user }}'
    group: '{{ ansible_user }}'
    mode: 0775

- name: Create systemd service unit file
  template:
    src: templates/systemd/node_updater.service
    dest: /etc/systemd/system/node_updater.service
    mode: '0644'

- name: Create systemd service unit file
  template:
    src: templates/systemd/node_updater.timer
    dest: /etc/systemd/system/node_updater.timer
    mode: '0644'

- name: Reload systemd daemon
  systemd:
    daemon_reload: yes

- name: Start and enable the service
  service:
    name: node_updater.timer
    state: started

- name: Make sure clustershell is installed for node status script
  vars:
    package_name:
      - clustershell
    package_state: latest
  include_role:
    name: safe_yum
  ignore_errors: true

- name: add alias for node status
  lineinfile:
    path: '/home/{{ ansible_user }}/.bashrc'
    line: alias nodes="python3 /opt/oci-hpc/bin/nodes_status.py"
    state: present