---

    
- name: Import MongoDB public GPG key
  ansible.builtin.apt_key:
    url: https://www.mongodb.org/static/pgp/server-6.0.asc
    state: present
    
- name: Add MongoDB repository
  ansible.builtin.apt_repository:
    repo: "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu jammy/mongodb-org/6.0 multiverse"
    state: present
    filename: mongodb-org-6.0
    
- name: Update the apt package index
  ansible.builtin.apt:
    update_cache: yes


- name: Make sure python OpenSSL and parallel ssh is installed
  vars:
    package_name:
      - nmap
      - mongodb-org
  include_role:
    name: safe_yum

- name: install pymongo latest version
  become: true
  pip:
    name: [pymongo]
    state: latest
    executable: /opt/oci-hpc/venv/bin/pip3
  ignore_errors: yes

- name: Copying the Mongo Scraper config
  become: true
  template:
    src: nodes_update.py.j2
    dest: "/opt/oci-hpc/bin/nodes_update.py"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0775'  

- name: Copying the file to manually add a node to the queue
  become: true
  template:
    src: add_nodes_to_queue.py.j2
    dest: "/opt/oci-hpc/bin/add_nodes_to_queue.py"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0775'  

- name: Ensure db directory exists
  file:
    path: "/opt/oci-hpc/db"
    state: directory
    owner: '{{ ansible_user }}'
    group: '{{ ansible_user }}'

- name: Generate env file
  template: 
    src: get_nodes_from_db.py
    dest: /opt/oci-hpc/bin/get_nodes_from_db.py
    owner: '{{ ansible_user }}'
    group: '{{ ansible_user }}'
    mode: 0775
    
- name: Create systemd service unit file
  template:
    src: templates/systemd/node_updater.service
    dest: /etc/systemd/system/node_updater.service
    mode: '0644'

- name: Create systemd service unit file
  template:
    src: templates/systemd/node_updater.timer
    dest: /etc/systemd/system/node_updater.timer
    mode: '0644'

- name: Reload systemd daemon
  systemd:
    daemon_reload: yes

- name: Start and enable the service
  service:
    name: mongod
    state: started
    enabled: yes

- name: Start and enable the service
  service:
    name: node_updater.timer
    state: started