---
- name: Check oracle cloud agent version
  shell: "snap info oracle-cloud-agent | grep installed | awk '{print $2}'"
  register: oca_version
  when: rdma_enabled | bool

- name: Download Snap package
  environment:
    SSL_CERT_FILE: '/etc/pki/tls/certs/ca-bundle.crt'
  ansible.builtin.get_url:
    url: "https://objectstorage.us-phoenix-1.oraclecloud.com/p/KVgO3DVFyTiLdCJLZUNYZlYCF5mcnaTjemmMUmyOB1Ln7Vkii-llp7QoQDiRF66T/n/imagegen/b/agent_test/o/1.37.0/4/oracle-cloud-agent_1.37.2-9_amd64.snap" # yamllint disable-line rule:line-length
    dest: "/tmp/oracle-cloud-agent_1.37.2-9_amd64.snap"
  when:
    - oca_version is version('1.37.2', '<')
    - rdma_enabled | bool

      ## The ansible snap module is not upgrading properly if the package already exists.
      #  - name: Install OCA snap v1.37
      #    vars:
      #      - major_version: "{{version.stdout.split('.')[1] }}"
      #      - minor_version: "{{version.stdout.split('.')[0] }}"
      #    become: true
      #    community.general.snap:
      #      classic: true
      #      dangerous: true
      #      name: "/tmp/oracle-cloud-agent_1.37.0-2_amd64.snap"
      #    when :
      #      - (minor_version | int <= 1) | bool and (minor_version | int < 37) | bool
      #      - rdma_enabled | bool

- name: Snap update
  become: true
  ansible.builtin.command: snap install --classic --dangerous /tmp/oracle-cloud-agent_1.37.2-9_amd64.snap
  when:
    - oca_version is version('1.37.2', '<')
    - rdma_enabled | bool
