---
- block:

# Should be already installed: yum list installed | grep slurm-devel
  - name: install required packages
    vars: 
      package_name: 
        - gcc-c++
        - git
      package_repo: "epel,ol7_developer_EPEL"
    include_role: 
      name: safe_yum

  - name: clone pyxis repo
    git:
      repo: https://github.com/NVIDIA/pyxis.git
      dest: /tmp/pyxis

  - name: compile 
    command: bash -c "sudo make install"
    args:
      chdir: /tmp/pyxis/