---
- name: Create groupname group (gid 9876)
  become: true
  ansible.builtin.group:
    name: "{{ privilege_group_name }}"
    gid: 9876
    state: present

- name: Allow groupname group to have passwordless sudo
  become: true
  ansible.builtin.lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: "^%{{ privilege_group_name }}"
    line: "%{{ privilege_group_name }} ALL=(ALL) NOPASSWD: ALL"
    validate: "visudo -cf %s"
  when: privilege_sudo | bool

- name: "Add opc/ubuntu user to {{ privilege_group_name }} group"
  become: true
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: "{{ privilege_group_name }}"
    append: true
