---
- name: Ensure OpenLDAP has access to the ssl certificates
  user:
    name: 'ldap'
    groups: 'ssl'

- name: Create /etc/opt/oci-hpc/passwords/openldap/
  become: true
  file:
    path: /etc/opt/oci-hpc/passwords/openldap
    state: directory
    owner: opc
    mode: 0770
    group: opc
    recurse: yes

- name: Generate password for DB root and save it to /etc/opt/oci-hpc/passwords
  set_fact:
    tmp_pwd: "{{ lookup('password',
                          '/etc/opt/oci-hpc/passwords/openldap/root.txt  
                           chars=ascii_letters,digits,hexdigits') }}"

- name: Get root password from /etc/opt/oci-hpc/passwords
  set_fact:
   openldap_root_pwd: "{{ lookup('password',
                          '/etc/opt/oci-hpc/passwords/openldap/root.txt  
                           chars=ascii_letters,digits,hexdigits') }}"

- name: Adjust OpenLDAP client TLS configuration
  lineinfile:
    path: '/etc/openldap/ldap.conf'
    line: 'TLS_CACERT   /etc/openldap/certs/cluster-ca.crt'

- name: Add cluster CA certificate to /etc/openldap/certs
  copy:
    src: '{{ openldap_tls_cacrt }}'
    dest: '/etc/openldap/certs/'

- name: Start LDAP 
  service: 
    name: slapd
    state: restarted
    enabled: true

- name: Get password hash
  shell: 
    cmd: "slappasswd -h {SSHA} -s {{ openldap_root_pwd }}"
  register: ldap_password_hash

- name: template ldifs
  template:
    src: "{{ item }}"
    dest: "/tmp/{{ item }}"
  with_items: 
    - db.ldif
    - monitor.ldif 
    - base.ldif

- name: Configure LDAP
  shell: 
    cmd: "ldapmodify -Y EXTERNAL  -H ldapi:/// -f /tmp/{{ item }}"
  with_items: 
    - db.ldif
    - monitor.ldif

- name: Copy DB_CONFIG
  copy: 
    src: /usr/share/openldap-servers/DB_CONFIG.example
    dest: /var/lib/ldap/DB_CONFIG
    owner: ldap
    group: ldap

- name: Load schemas
  shell: 
    cmd: "ldapadd -Y EXTERNAL -H ldapi:/// -f /etc/openldap/schema/{{ item }}"
  register: ldap_result_code
  failed_when: ldap_result_code.rc not in [0,80]
  changed_when: ldap_result_code.rc not in [0,80]
  with_items: 
    - cosine.ldif
    - nis.ldif
    - inetorgperson.ldif

- name: Set up LDAP schemas
  shell: 
    cmd: 'ldapadd -x -H ldaps://localhost -w {{ openldap_root_pwd }} -D "cn=manager,dc=cluster,dc=local" -f /tmp/base.ldif'
  register: ldap_result_code
  failed_when: ldap_result_code.rc not in [0,68,80]
  changed_when: ldap_result_code.rc not in [0,68,80]

