---
- name: Make sure the /home directory exist
  file:
    path: "/config/mgmt"
    state: directory
    mode: '0755'
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: Copying the file to manually add a node to the queue
  become: true
  template:
    src: "{{item}}"
    dest: "/config/mgmt/{{item}}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0775'  
  with_items: 
    - get_nodes_from_db.py
    - add_nodes_to_queue.py
    - mgmt.py

- name: copy mgmt utils files
  copy: 
    src: "{{item}}"
    dest: "/config/mgmt/{{item}}"
    owner: "{{ansible_user}}"
    group: "{{ansible_user}}"
    mode: '0755'
  with_items: 
    - mgmt_shared_logging.py
    - mgmt_utils.py

- name: Make sure clustershell is installed for node status script
  vars:
    package_name:
      - clustershell
    package_state: latest
  include_role:
    name: safe_yum
  ignore_errors: true

- name: install clustershell
  become: true
  pip:
    name: ['clustershell']
    executable: /config/venv/bin/pip3
    state: latest
  ignore_errors: yes

- name: add alias for node status
  lineinfile:
    path: '/home/{{ ansible_user }}/.bashrc'
    line: alias mgmt="/config/venv/bin/python3 /config/mgmt/mgmt.py"
    state: present