---

- name: Ensure db directory exists
  file:
    path: "/opt/oci-hpc/db"
    state: directory
    owner: '{{ ansible_user }}'
    group: '{{ ansible_user }}'

- name: Generate env file
  template: 
    src: env.j2
    dest: /opt/oci-hpc/db/env

- name: Copy files
  become: true
  copy: 
    src: "initial.sql"
    dest: '/opt/oci-hpc/db/initial.sql'
    force: no
    owner: '{{ ansible_user }}'
    group: '{{ ansible_user }}'

- name: Get root password from /etc/opt/oci-hpc/passwords
  set_fact:
    mysql_root_pwd: "{{ lookup('password',
                          '/etc/opt/oci-hpc/passwords/mysql/root.txt  
                           chars=ascii_letters,digits') }}"

- name: Create database 'clusterDB'
  mysql_db:
    login_user: "root"
    login_password: "{{ mysql_root_pwd }}"
    name: clusterDB
    state: present

- name: Create database user with name 'clusterUser' and password
  mysql_user:
    login_user: "root"
    login_password: "{{ mysql_root_pwd }}"
    name: clusterUser
    password: Cluster1234!
    priv: clusterDB.*:SELECT,INSERT,UPDATE,DELETE
    state: present

- name: Create initial DB
  shell: "source /opt/oci-hpc/db/env; mysql -u root -p{{ mysql_root_pwd }} < /opt/oci-hpc/db/initial.sql"
  ignore_errors: yes  

- name: Ensure db directory exists
  file:
    path: "/opt/oci-hpc/db"
    state: directory
    owner: '{{ ansible_user }}'
    group: '{{ ansible_user }}'

- name: Create systemd service unit file
  template:
    src: templates/systemd/mgmt.service
    dest: /etc/systemd/system/mgmt.service
    mode: '0644'

- name: Create systemd service unit file
  template:
    src: templates/systemd/mgmt.timer
    dest: /etc/systemd/system/mgmt.timer
    mode: '0644'

- name: Reload systemd daemon
  systemd:
    daemon_reload: yes

- name: Start and enable the service
  service:
    name: mgmt.timer
    state: started

- name: Make sure the /home directory exist
  file:
    path: "/config/mgmt"
    state: directory
    mode: '0755'
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

# - name: Git checkout
#   ansible.builtin.git:
#     repo: 'https://github.com/oracle-quickstart/oci-cluster-management'
#     dest: "/config/mgmt"

- name: Make sure clustershell is installed for node status script
  vars:
    package_name:
      - clustershell
      #- python3-ansible-runner
    package_state: latest
  include_role:
    name: safe_yum
  ignore_errors: true

- name: install clustershell
  become: true
  pip:
    name: ['clustershell', 'sqlalchemy', 'rich', 'click', 'ansible_runner']
    executable: /config/venv/bin/pip3
    state: latest
  ignore_errors: yes

- name: add alias for node status
  lineinfile:
    path: '/home/{{ ansible_user }}/.bashrc'
    line: alias mgmt="/config/venv/bin/python3 /config/mgmt/manage.py"
    state: present

- name: import the queues.conf into the DB
  shell: "/config/venv/bin/python3 /config/mgmt/manage.py configurations create from-file --file /opt/oci-hpc/conf/queues.conf"
