---
- name: Copy mgmt utility
  become: true
  ansible.builtin.template:
    src: templates/mgmt_remote.j2
    dest: "/usr/local/bin/mgmt"
    owner: "{{ cluster_admin_user }}"
    group: "{{ cluster_admin_user }}"
    mode: "0775"
  run_once: true

- name: Install mgmt bash completion
  become: true
  ansible.builtin.template:
    src: templates/mgmt.bash_completion.j2
    dest: "/etc/bash_completion.d/mgmt"
    owner: root
    group: root
    mode: "0644"
  run_once: true
