CREATE TABLE IF NOT EXISTS clusterDB.nodes (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    ip_address VARCHAR(128) UNIQUE,
    controller_status ENUM('configuring', 'terminating', 'waiting_for_info', 'configured', 'terminated', 'reconfiguring'),
    started_time VARCHAR(128),
    status ENUM('starting', 'terminating', 'terminated', 'running', 'unreachable'),
    availability_domain VARCHAR(128),
    first_time_reachable VARCHAR(128),
    cluster_name VARCHAR(128),
    compartment_id VARCHAR(128),
    tenancy_id VARCHAR(128),
    compute_status ENUM('configuring', 'configured', 'starting','terminating'),
    controller_name VARCHAR(128),
    fss_mount VARCHAR(128),
    gpu_memory_fabric VARCHAR(128),
    hostname VARCHAR(128) UNIQUE,
    hpc_island VARCHAR(128),
    image_id VARCHAR(128),
    last_time_reachable VARCHAR(128),
    oci_name VARCHAR(128),
    ocid VARCHAR(128) UNIQUE,
    rack_id VARCHAR(128),
    rail_id VARCHAR(128),
    network_block_id VARCHAR(128),
    memory_cluster_name VARCHAR(128),
    memory_fabric_id VARCHAR(128),
    role VARCHAR(128),
    serial VARCHAR(128),
    shape VARCHAR(128),
    terminated_time VARCHAR(128),
    update_count INT,
    slurm_state VARCHAR(128),
    slurm_partition VARCHAR(128),
    slurm_reservation VARCHAR(128),
    slurm_up_time INT,
    oci_host_id VARCHAR(128)
);

CREATE TABLE IF NOT EXISTS clusterDB.terminated_nodes (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    ip_address VARCHAR(128),
    controller_status ENUM('configuring', 'terminating', 'waiting_for_info', 'configured', 'terminated', 'reconfiguring'),
    started_time VARCHAR(128),
    status ENUM('starting', 'terminating', 'terminated', 'running', 'unreachable'),
    availability_domain VARCHAR(128),
    first_time_reachable VARCHAR(128),
    cluster_name VARCHAR(128),
    compartment_id VARCHAR(128),
    tenancy_id VARCHAR(128),
    compute_status ENUM('configuring', 'configured', 'starting','terminating'),
    controller_name VARCHAR(128),
    fss_mount VARCHAR(128),
    gpu_memory_fabric VARCHAR(128),
    hostname VARCHAR(128),
    hpc_island VARCHAR(128),
    image_id VARCHAR(128),
    last_time_reachable VARCHAR(128),
    oci_name VARCHAR(128),
    ocid VARCHAR(128) UNIQUE,
    rack_id VARCHAR(128),
    rail_id VARCHAR(128),
    network_block_id VARCHAR(128),
    memory_cluster_name VARCHAR(128),
    memory_fabric_id VARCHAR(128),
    role VARCHAR(128),
    serial VARCHAR(128),
    shape VARCHAR(128),
    terminated_time VARCHAR(128),
    update_count INT,
    slurm_state VARCHAR(128),
    slurm_partition VARCHAR(128),
    slurm_reservation VARCHAR(128),
    slurm_up_time INT,
    oci_host_id VARCHAR(128)
);


CREATE TABLE IF NOT EXISTS clusterDB.configurations (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `name` VARCHAR(64),
    `partition` VARCHAR(64),
    shape VARCHAR(64),
    role ENUM('compute', 'login'),
    change_hostname BOOLEAN,
    hostname_convention VARCHAR(64),
    permanent BOOLEAN,
    rdma_enabled BOOLEAN,
    stand_alone BOOLEAN,
    region VARCHAR(64),
    availability_domain VARCHAR(64),
    private_subnet_cidr VARCHAR(64),
    private_subnet_id VARCHAR(128),
    image_id VARCHAR(128),
    target_compartment_id VARCHAR(128),
    boot_volume_size INT,
    use_marketplace_image BOOLEAN,
    instance_pool_ocpus INT,
    instance_pool_custom_memory BOOLEAN,
    instance_pool_memory INT,
    marketplace_listing VARCHAR(64),
    hyperthreading BOOLEAN,
    preemptible BOOLEAN
);


CREATE TABLE IF NOT EXISTS clusterDB.healthchecks (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    ocid VARCHAR(128),
    healthcheck_type ENUM('passive', 'active', 'multi-node','slurm','host_api'),
    healthcheck_logs VARCHAR(4096),
    healthcheck_time_change VARCHAR(128),
    healthcheck_last_time VARCHAR(128),
    healthcheck_recommendation VARCHAR(128),
    healthcheck_status VARCHAR(128),
    healthcheck_associated_node VARCHAR(128)
);