CREATE TABLE IF NOT EXISTS clusterDB.nodes (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    ip_address VARCHAR(128) UNIQUE,
    controller_status ENUM('configuring', 'terminating', 'waiting_for_info', 'configured', 'terminated','reconfiguring'),
    startedTime VARCHAR(128),
    status ENUM('starting', 'terminating', 'terminated', 'running', 'unreachable'),
    AD VARCHAR(128),
    FirstTimeReachable VARCHAR(128),
    cluster_name VARCHAR(128),
    compartment  VARCHAR(128),
    tenancy  VARCHAR(128),
    compute_status ENUM('configuring', 'configured'),
    controller_name VARCHAR(128),
    fss_mount VARCHAR(128),
    hostname VARCHAR(128) UNIQUE,
    hpc_island VARCHAR(128),
    lastTimeReachable VARCHAR(128),
    oci_name VARCHAR(128),
    ocid VARCHAR(128) UNIQUE,
    rackID VARCHAR(128),
    railId VARCHAR(128),
    networkBlockId VARCHAR(128),
    memoryFabricId VARCHAR(128),
    role VARCHAR(128),
    serial VARCHAR(128),
    shape VARCHAR(128),
    terminatedTime VARCHAR(128),
    update_count INT,
    healthcheck_recomandation VARCHAR(128),
    last_healthcheck_time VARCHAR(128),
    healthcheck_logs VARCHAR(2048),
    oci_health VARCHAR(128),
    oci_impacted_components BOOLEAN,
    oci_host_id VARCHAR(128)
);

CREATE TABLE IF NOT EXISTS clusterDB.terminated_nodes (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    ip_address VARCHAR(128),
    controller_status ENUM('configuring', 'terminating', 'waiting_for_info', 'configured', 'terminated','reconfiguring'),
    startedTime VARCHAR(128),
    status ENUM('starting', 'terminating', 'terminated', 'running', 'unreachable'),
    AD VARCHAR(128),
    FirstTimeReachable VARCHAR(128),
    cluster_name VARCHAR(128),
    compartment  VARCHAR(128),
    tenancy  VARCHAR(128),
    compute_status ENUM('configuring', 'configured'),
    controller_name VARCHAR(128),
    fss_mount VARCHAR(128),
    hostname VARCHAR(128),
    hpc_island VARCHAR(128),
    lastTimeReachable VARCHAR(128),
    oci_name VARCHAR(128),
    ocid VARCHAR(128) UNIQUE,
    rackID VARCHAR(128),
    railId VARCHAR(128),
    networkBlockId VARCHAR(128),
    memoryFabricId VARCHAR(128),
    role VARCHAR(128),
    serial VARCHAR(128),
    shape VARCHAR(128),
    terminatedTime VARCHAR(128),
    update_count INT,
    healthcheck_recomandation VARCHAR(128),
    last_healthcheck_time VARCHAR(128),
    healthcheck_logs VARCHAR(2048),
    oci_health VARCHAR(128),
    oci_impacted_components BOOLEAN,
    oci_host_id VARCHAR(128)
);


CREATE TABLE IF NOT EXISTS clusterDB.configurations (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `name` VARCHAR(64),
    `partition` VARCHAR(64),
    shape VARCHAR(64),
    change_hostname  BOOLEAN,
    hostname_convention VARCHAR(64),
    permanent BOOLEAN,
    rdma_enabled BOOLEAN,
    stand_alone BOOLEAN,
    region VARCHAR(64),
    ad VARCHAR(64),
    private_subnet_cidr VARCHAR(64),
    private_subnet_id VARCHAR(128),
    image VARCHAR(128),
    targetCompartment VARCHAR(128),
    boot_volume_size INT,
    use_marketplace_image BOOLEAN,
    instance_pool_ocpus INT,
    instance_pool_custom_memory BOOLEAN,
    instance_pool_memory INT,
    marketplace_listing VARCHAR(64),
    hyperthreading BOOLEAN,
    preemptible BOOLEAN
);