- include: centos.yml
  when: ansible_os_family == 'RedHat' and ansible_distribution == 'CentOS'

- include: el.yml
  when: ansible_os_family == 'RedHat' and ansible_distribution == 'OracleLinux'ß

- include: debian.yml
  when: ansible_distribution == 'Ubuntu'

- include: debian.yml
  when: ansible_distribution == 'Debian'
