- include_tasks: centos.yml
  when: ansible_os_family == 'RedHat' and ansible_distribution == 'CentOS'

- include_tasks: el.yml
  when: ansible_os_family == 'RedHat' and ansible_distribution == 'OracleLinux'

- include_tasks: debian.yml
  when: ansible_distribution == 'Ubuntu'

- include_tasks: debian.yml
  when: ansible_distribution == 'Debian'
