- include: centos.yml
  when: ansible_os_family == 'RedHat' and ansible_distribution == 'CentOS'

- include: el.yml
  when: ansible_os_family == 'RedHat' and ansible_distribution == 'OracleLinux' and ansible_distribution_major_version == '7'

- include: el8.yml
  when: ansible_os_family == 'RedHat' and ansible_distribution == 'OracleLinux' and ansible_distribution_major_version == '8'

- include: debian.yml
  when: ansible_distribution == 'Ubuntu'

- include: debian.yml
  when: ansible_distribution == 'Debian'
