---
# Ensure prometheus targets prerequisites
- name: Create user for prometheus
  become: true
  user:
    name: "{{ prometheus_user }}"
    state: present
    createhome: false
    shell: /usr/sbin/nologin
    append: true
  run_once: true
  delegate_to: "{% if groups['monitoring'] | length > 0 %}{{ groups['monitoring'][0] }}{% else %}127.0.0.1{% endif %}"

- name: Create installation folder in etc
  become: true
  file:
    path: "{{ prometheus_dest_dir }}"
    state: directory
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_user }}"
    mode: "0775"
    recurse: true
  run_once: true
  delegate_to: "{% if groups['monitoring'] | length > 0 %}{{ groups['monitoring'][0] }}{% else %}127.0.0.1{% endif %}"

- name: Create targets folder
  become: true
  file:
    path: "{{ prometheus_targets_dir }}"
    state: directory
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_user }}"
    mode: "0775"
    recurse: true
  run_once: true
  delegate_to: "{% if groups['monitoring'] | length > 0 %}{{ groups['monitoring'][0] }}{% else %}127.0.0.1{% endif %}"

- name: Sync targets for the controller node(s)
  become: true
  vars:
    exporter_ports: "{{ controller_ports }}"
  template:
    src: templates/prometheus_target.json.j2
    dest: "{{ prometheus_targets_dir }}/{{ item.value.hostname }}.json"
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_user }}"
    mode: "0775"
  delegate_to: "{% if groups['monitoring'] | length > 0 %}{{ groups['monitoring'][0] }}{% else %}127.0.0.1{% endif %}"
  loop: "{{ all_hosts_info | dict2items | selectattr('value.role', 'equalto', 'controller') | rejectattr('value.controller_status', 'equalto', 'terminating') }}"

- name: Sync targets for the login node(s)
  become: true
  vars:
    exporter_ports: "{{ login_ports }}"
  template:
    src: templates/prometheus_target.json.j2
    dest: "{{ prometheus_targets_dir }}/{{ item.value.hostname }}.json"
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_user }}"
    mode: "0775"
  delegate_to: "{% if groups['monitoring'] | length > 0 %}{{ groups['monitoring'][0] }}{% else %}127.0.0.1{% endif %}"
  loop: "{{ all_hosts_info | dict2items | selectattr('value.role', 'equalto', 'login') | rejectattr('value.controller_status', 'equalto', 'terminating') }}"

- name: Sync targets for the compute node(s)
  become: true
  vars:
    exporter_ports: "{{ compute_ports }}"
  template:
    src: templates/prometheus_target.json.j2
    dest: "{{ prometheus_targets_dir }}/{{ item.value.hostname }}.json"
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_user }}"
    mode: "0775"
  delegate_to: "{% if groups['monitoring'] | length > 0 %}{{ groups['monitoring'][0] }}{% else %}127.0.0.1{% endif %}"
  loop: "{{ all_hosts_info | dict2items | selectattr('value.role', 'equalto', 'compute') | rejectattr('value.controller_status', 'equalto', 'terminating') }}"
