#!/usr/bin/env python3
"""Generate the mgmt Bash completion shim from `mgmt --help` output.

Run this from any environment where `mgmt` is installed and functional, for
example a deployed controller node or a local dev environment with the mgmt
dependencies installed.
"""

from __future__ import annotations

import argparse
import re
import shlex
import subprocess
from collections import OrderedDict
from pathlib import Path


ROOT_KEY = "__root__"
COMMAND_RE = re.compile(r"^\s{2,}([a-zA-Z0-9][a-zA-Z0-9_-]*)(?:\s{2,}.*)?$")
LONG_OPTION_RE = re.compile(r"--[a-zA-Z0-9][a-zA-Z0-9_-]*")


def parse_args():
    parser = argparse.ArgumentParser(description="Generate the mgmt Bash completion shim.")
    parser.add_argument(
        "--mgmt-cmd",
        default="mgmt",
        help="Command used to invoke mgmt, e.g. 'mgmt' or 'ssh ubuntu@host mgmt'.",
    )
    parser.add_argument(
        "--output",
        default="playbooks/roles/mgmt/templates/mgmt.bash_completion.j2",
        help="Destination path for the generated completion template.",
    )
    return parser.parse_args()


def run_help(base_cmd: str, path_words: tuple[str, ...]) -> str:
    cmd = shlex.split(base_cmd) + list(path_words) + ["--help"]
    result = subprocess.run(cmd, capture_output=True, text=True, check=True)
    return result.stdout


def split_sections(help_text: str) -> dict[str, list[str]]:
    sections: dict[str, list[str]] = OrderedDict()
    current = None
    for line in help_text.splitlines():
        stripped = line.strip()
        if stripped.endswith(":") and stripped[:-1] in {"Usage", "Options", "Commands"}:
            current = stripped[:-1]
            sections[current] = []
            continue
        if current:
            sections[current].append(line)
    return sections


def parse_commands(help_text: str) -> list[str]:
    commands = []
    for line in split_sections(help_text).get("Commands", []):
        match = COMMAND_RE.match(line)
        if match:
            commands.append(match.group(1))
    return commands


def parse_options(help_text: str) -> tuple[list[str], list[str]]:
    options = []
    value_options = []

    for line in split_sections(help_text).get("Options", []):
        if not line.lstrip().startswith("-"):
            continue
        left = re.split(r"\s{2,}", line.strip(), maxsplit=1)[0]
        long_options = LONG_OPTION_RE.findall(left)
        if not long_options:
            continue

        for option in long_options:
            if option not in options:
                options.append(option)

        if len(long_options) == 1:
            option = long_options[0]
            remainder = left.split(option, 1)[1].strip()
            if remainder and not remainder.startswith("/"):
                value_options.append(option)

    return options, value_options


def collect_help_tree(base_cmd: str) -> OrderedDict[str, dict[str, list[str]]]:
    queue = [tuple()]
    seen = set()
    data: OrderedDict[str, dict[str, list[str]]] = OrderedDict()

    while queue:
        path_words = queue.pop(0)
        key = " ".join(path_words) if path_words else ROOT_KEY
        if key in seen:
            continue
        seen.add(key)

        help_text = run_help(base_cmd, path_words)
        commands = parse_commands(help_text)
        options, value_options = parse_options(help_text)
        data[key] = {
            "commands": commands,
            "options": options,
            "value_options": value_options,
        }
        for command in commands:
            queue.append(path_words + (command,))

    return data


def bash_list(values: list[str]) -> str:
    return " ".join(values)


def render_completion(data: OrderedDict[str, dict[str, list[str]]]) -> str:
    header = """{% raw %}
# This file is generated by scripts/generate_mgmt_bash_completion.py.
# Do not edit it by hand.
#
# Example regeneration command from a deployed controller:
#   scripts/generate_mgmt_bash_completion.py --mgmt-cmd "mgmt" --output playbooks/roles/mgmt/templates/mgmt.bash_completion.j2

declare -A _MGMT_SUBCOMMANDS=(
"""
    lines = [header]
    for key, entry in data.items():
        lines.append(f'    ["{key}"]="{bash_list(entry["commands"])}"')
    lines.append(")")
    lines.append("")
    lines.append("declare -A _MGMT_OPTIONS=(")
    for key, entry in data.items():
        lines.append(f'    ["{key}"]="{bash_list(entry["options"])}"')
    lines.append(")")
    lines.append("")
    lines.append("declare -A _MGMT_VALUE_OPTIONS=(")
    for key, entry in data.items():
        lines.append(f'    ["{key}"]="{bash_list(entry["value_options"])}"')
    lines.append(")")
    lines.append(
        """

_mgmt_click_completion() {
    local IFS=$'\\n'
    local response
    local completion
    local type
    local value
    local -a click_words
    local click_cword

    click_words=("${_MGMT_WORDS[@]}")
    click_cword="${_MGMT_CWORD}"
    if [[ -z "${_MGMT_RAW_CURRENT}" ]] && [[ "${COMP_LINE}" != *" " ]] && [[ "${_MGMT_CURRENT}" == *"=" || "${_MGMT_CURRENT}" == *,* ]]; then
        click_words+=("")
        click_cword=$((${#click_words[@]} - 1))
    fi

    response=$(
        env \\
            COMP_WORDS="${click_words[*]}" \\
            COMP_CWORD="${click_cword}" \\
            COMP_POINT="${COMP_POINT:-0}" \\
            COMP_TYPE="${COMP_TYPE:-0}" \\
            _MGMT_COMPLETE=bash_complete \\
            "$1"
    )

    COMPREPLY=()
    for completion in $response; do
        IFS=',' read -r type value <<< "${completion}"
        case "${type}" in
            dir)
                compopt -o dirnames
                ;;
            file)
                compopt -o default
                ;;
        esac
        COMPREPLY+=("${value}")
    done

    return 0
}

_mgmt_compgen_words() {
    local current="$1"
    shift
    COMPREPLY=( $(compgen -W "$*" -- "${current}") )
}

_mgmt_filter_used_options() {
    local filtered=()
    local candidate
    local used

    for candidate in "${COMPREPLY[@]}"; do
        used=0
        if [[ "${candidate}" == --* ]]; then
            for word in "${_MGMT_WORDS[@]}"; do
                if [[ "${word}" == "${candidate}" ]]; then
                    used=1
                    break
                fi
            done
        fi
        if (( used == 0 )); then
            filtered+=("${candidate}")
        fi
    done

    COMPREPLY=("${filtered[@]}")
}

_mgmt_configure_compopt() {
    local candidate

    compopt +o nospace >/dev/null 2>&1 || true
    for candidate in "${COMPREPLY[@]}"; do
        if [[ "${candidate}" == *= ]]; then
            compopt -o nospace >/dev/null 2>&1 || true
            return
        fi
    done
}

_mgmt_key_for_path() {
    if (( $# == 0 )); then
        printf '%s' "__root__"
    else
        printf '%s' "$*"
    fi
}

_mgmt_option_requires_value() {
    local key="$1"
    local option="$2"
    [[ " ${_MGMT_VALUE_OPTIONS[$key]} " == *" ${option} "* ]]
}

_mgmt_prepare_words() {
    if declare -F _init_completion >/dev/null 2>&1; then
        local cur prev words cword
        _init_completion -n =,: || return
        _MGMT_RAW_CURRENT="${cur}"
        _MGMT_CURRENT="${cur}"
        _MGMT_PREV="${prev}"
        _MGMT_WORDS=("${words[@]}")
        _MGMT_CWORD="${cword}"
    elif declare -F _get_comp_words_by_ref >/dev/null 2>&1; then
        local cur prev words cword
        _get_comp_words_by_ref -n =,: cur prev words cword
        _MGMT_RAW_CURRENT="${cur}"
        _MGMT_CURRENT="${cur}"
        _MGMT_PREV="${prev}"
        _MGMT_WORDS=("${words[@]}")
        _MGMT_CWORD="${cword}"
    else
        _MGMT_RAW_CURRENT="${COMP_WORDS[COMP_CWORD]}"
        _MGMT_CURRENT="${COMP_WORDS[COMP_CWORD]}"
        _MGMT_PREV="${COMP_WORDS[COMP_CWORD-1]}"
        _MGMT_WORDS=("${COMP_WORDS[@]}")
        _MGMT_CWORD="${COMP_CWORD}"
    fi

    if [[ "${COMP_LINE}" == *" " ]] && (( ${#_MGMT_WORDS[@]} > 0 )) && (( _MGMT_CWORD == ${#_MGMT_WORDS[@]} - 1 )) && [[ -n "${_MGMT_CURRENT}" ]]; then
        _MGMT_WORDS+=("")
        _MGMT_CWORD=$((${#_MGMT_WORDS[@]} - 1))
        _MGMT_PREV="${_MGMT_CURRENT}"
        _MGMT_CURRENT=""
    fi
}

_mgmt_adjust_reply_for_raw_current() {
    local logical_current="$1"
    local raw_current="$2"
    local prefix
    local adjusted=()
    local candidate

    if [[ "${COMP_LINE}" == *" " ]]; then
        return
    fi

    if [[ "${logical_current}" == *"="* || "${logical_current}" == *","* ]]; then
        prefix="${logical_current%${logical_current##*[=,]}}"
    elif [[ "${logical_current}" != "${raw_current}" && -n "${raw_current}" ]]; then
        prefix="${logical_current%"${raw_current}"}"
    elif [[ "${logical_current}" != "${raw_current}" ]]; then
        prefix="${logical_current}"
    else
        return
    fi

    for candidate in "${COMPREPLY[@]}"; do
        if [[ -n "${prefix}" && "${candidate}" == "${prefix}"* ]]; then
            adjusted+=("${candidate#${prefix}}")
        else
            adjusted+=("${candidate}")
        fi
    done

    COMPREPLY=("${adjusted[@]}")
}

_mgmt_normalize_split_words() {
    local -a normalized=()
    local idx=0
    local new_index=-1
    local word

    for (( idx=0; idx<${#_MGMT_WORDS[@]}; idx++ )); do
        word="${_MGMT_WORDS[idx]}"

        if [[ "${word}" == "=" || "${word}" == "," ]]; then
            if (( ${#normalized[@]} == 0 )); then
                normalized+=("${word}")
                new_index=0
            else
                normalized[new_index]+="${word}"
            fi
            if (( idx == _MGMT_CWORD )); then
                _MGMT_CWORD="${new_index}"
            fi
            continue
        fi

        if (( ${#normalized[@]} > 0 )) && [[ "${normalized[new_index]}" == *= || "${normalized[new_index]}" == *, ]]; then
            normalized[new_index]+="${word}"
            if (( idx == _MGMT_CWORD )); then
                _MGMT_CWORD="${new_index}"
            fi
            continue
        fi

        normalized+=("${word}")
        ((new_index++))
        if (( idx == _MGMT_CWORD )); then
            _MGMT_CWORD="${new_index}"
        fi
    done

    _MGMT_WORDS=("${normalized[@]}")
    _MGMT_CURRENT="${_MGMT_WORDS[_MGMT_CWORD]}"
    if (( _MGMT_CWORD > 0 )); then
        _MGMT_PREV="${_MGMT_WORDS[_MGMT_CWORD-1]}"
    else
        _MGMT_PREV=""
    fi
}

_mgmt_resolve_path() {
    local key="__root__"
    local path_words=()
    local word
    local candidate_key
    local skip_next=0

    for (( i=1; i<_MGMT_CWORD; i++ )); do
        word="${_MGMT_WORDS[i]}"
        [[ -z "${word}" ]] && continue

        if (( skip_next )); then
            skip_next=0
            continue
        fi

        if [[ "${word}" == --* ]]; then
            if _mgmt_option_requires_value "${key}" "${word}" || _mgmt_option_requires_value "__root__" "${word}"; then
                skip_next=1
            fi
            continue
        fi

        candidate_key="$(_mgmt_key_for_path "${path_words[@]}" "${word}")"
        if [[ " ${_MGMT_SUBCOMMANDS[$key]} " == *" ${word} "* ]]; then
            path_words+=("${word}")
            key="${candidate_key}"
        fi
    done

    printf '%s' "${key}"
}

_mgmt_completion() {
    COMPREPLY=()
    local current prev key subcommands options logical_current
    _mgmt_prepare_words
    _mgmt_normalize_split_words
    current="${_MGMT_CURRENT}"
    prev="${_MGMT_PREV}"
    logical_current="${current}"
    if [[ "${COMP_LINE}" == *" " ]] && [[ -n "${current}" ]]; then
        prev="${current}"
        current=""
    fi
    key="$(_mgmt_resolve_path)"
    subcommands="${_MGMT_SUBCOMMANDS[$key]}"
    options="${_MGMT_OPTIONS[$key]}"

    if _mgmt_option_requires_value "${key}" "${prev}" || _mgmt_option_requires_value "__root__" "${prev}"; then
        _mgmt_click_completion "$1"
        if (( ${#COMPREPLY[@]} > 0 )); then
            _mgmt_adjust_reply_for_raw_current "${logical_current}" "${_MGMT_RAW_CURRENT}"
            _mgmt_configure_compopt
            return 0
        fi
    fi

    if [[ "${current}" == -* ]]; then
        _mgmt_compgen_words "${current}" ${options}
        _mgmt_filter_used_options
        _mgmt_configure_compopt
        return 0
    fi

    if [[ -n "${subcommands}" ]]; then
        _mgmt_compgen_words "${current}" ${subcommands}
        if (( ${#COMPREPLY[@]} > 0 )); then
            _mgmt_configure_compopt
            return 0
        fi
    fi

    if [[ -z "${current}" && -n "${options}" ]]; then
        _mgmt_compgen_words "${current}" ${options}
        _mgmt_filter_used_options
        _mgmt_configure_compopt
        return 0
    fi

    _mgmt_click_completion "$1"
    if (( ${#COMPREPLY[@]} > 0 )); then
        _mgmt_adjust_reply_for_raw_current "${logical_current}" "${_MGMT_RAW_CURRENT}"
        _mgmt_filter_used_options
        _mgmt_configure_compopt
        return 0
    fi
}

complete -o nosort -F _mgmt_completion mgmt
{% endraw %}
""".rstrip()
    )
    lines.append("")
    return "\n".join(lines)


def main():
    args = parse_args()
    data = collect_help_tree(args.mgmt_cmd)
    output_path = Path(args.output)
    output_path.write_text(render_completion(data), encoding="utf-8")


if __name__ == "__main__":
    main()
