---
- name: change Node Status
  become: true
  command: "scontrol update nodename={{ cluster_name }}-node-{{groups['compute'].index(inventory_hostname)+1}} state=future reason=terminating"
  ignore_errors: force