#%Module1.0#####################################################################
#
# Copyright 2003-2019 Intel Corporation.
# 
# This software and the related documents are Intel copyrighted materials, and
# your use of them is governed by the express license under which they were
# provided to you (License). Unless the License provides otherwise, you may
# not use, modify, copy, publish, distribute, disclose or transmit this
# software or the related documents without Intel's prior written permission.
# 
# This software and the related documents are provided as is, with no express
# or implied warranties, other than those that are expressly stated in the
# License.
#
##
## Intel(R) MPI Library modulefile
##

proc ModulesHelp { } {
        global dotversion
        puts stderr " Intel(R) MPI Library"
}

module-whatis       "Sets up the Intel(R) MPI Library environment"

set                 topdir                 /opt/intel/compilers_and_libraries_2019.4.243

setenv              I_MPI_ROOT             $topdir/linux/mpi
setenv              I_MPI_FABRICS          shm:ofi
#setenv              I_MPI_FALLBACK         0
setenv              I_MPI_HYDRA_IFACE      enp94s0f0
prepend-path        CLASSPATH              $topdir/linux/mpi/intel64/lib/mpi.jar
prepend-path        PATH                   $topdir/linux/mpi/intel64/bin
prepend-path        LD_LIBRARY_PATH        $topdir/linux/mpi/intel64/lib/release:$topdir/linux/mpi/intel64/lib
prepend-path        MANPATH                $topdir/linux/mpi/man

if { [info exists ::env(I_MPI_OFI_LIBRARY_INTERNAL) ] } {
    set i_mpi_ofi_library_internal $::env(I_MPI_OFI_LIBRARY_INTERNAL)
} else {
    set i_mpi_ofi_library_internal "yes"
}

switch -regexp -- $i_mpi_ofi_library_internal {
    0|no|off|disable {
    }
    default {
        setenv              FI_PROVIDER_PATH       $topdir/linux/mpi/intel64/libfabric/lib/prov

        prepend-path        PATH                   $topdir/linux/mpi/intel64/libfabric/bin
        prepend-path        LD_LIBRARY_PATH        $topdir/linux/mpi/intel64/libfabric/lib
        prepend-path        LIBRARY_PATH           $topdir/linux/mpi/intel64/libfabric/lib
    }
}

