---
- name: create temporary /etc/hosts file
  template: 
    dest: /tmp/hosts.etc
    src: templates/etc-hosts.j2
  delegate_to: 127.0.0.1
  run_once: true

- name: create /etc/hosts on all servers
  become: true
  blockinfile:
    dest: /etc/hosts
    content: "{{ lookup('file', '/tmp/hosts.etc') }}"
    state: present
    
