- name: Create systemd unit dirs
  become: true
  file:
    name: '/opt/oci-hpc/healthchecks'
    state: directory
    owner: '{{ ansible_user }}'
    group: '{{ ansible_user }}'

- name: Copy files
  become: true
  copy: 
    src: '{{ item }}'
    dest: '/opt/oci-hpc/healthchecks/{{ item }}'
    force: no
    owner: '{{ ansible_user }}'
    group: '{{ ansible_user }}'
  with_items: 
    - check_gpu_setup.py
    - gpu_bw_test.py
    - rdma_link_flapping.py
    - xid_checker.py
    - shared_logging.py

- name: Download oci-mesh-pinger
  get_url:
    url: "{{mp_download_link}}"
    dest: "/tmp/"
  when: ('controller' in group_names)

- name: untar meshpinger
  unarchive:
    src: "/tmp/{{mp_filename}}"
    dest: "/opt/oci-hpc/healthchecks"
  when: ('controller' in group_names)

- name: Copy files
  become: true
  copy: 
    src: '{{ item }}'
    dest: '/opt/oci-hpc/healthchecks/{{ item }}'
    force: no
    owner: '{{ ansible_user }}'
    group: '{{ ansible_user }}'
    mode: 0755
  with_items: 
    - run_meshpinger.sh
  when: ('controller' in group_names)

- name: Make sure meshpinger dependencies are installed. 
  vars: 
    package_name: 
      - fping
      - jq
      - lshw
      - ethtool
    package_state: latest
  include_role: 
    name: safe_yum
  ignore_errors: true
  