---
- block:

  - name: Set DPKG architecture
    set_fact:
      dpkg_arch: "{{ 'amd64' if ansible_architecture == 'x86_64' else ansible_architecture }}"

  - name: install required packages
    apt: 
      deb: '{{ item }}'
    with_items: 
      - "https://github.com/NVIDIA/enroot/releases/download/v3.4.0/enroot_3.4.0-1_{{ dpkg_arch }}.deb"
      - "https://github.com/NVIDIA/enroot/releases/download/v3.4.0/enroot+caps_3.4.0-1_{{ dpkg_arch }}.deb"



  - name: set user.max_user_namespaces using sysctl
    ansible.posix.sysctl:
      name: user.max_user_namespaces
      value: '15076'
      sysctl_file: /etc/sysctl.d/81-enroot.conf
      reload: yes

  - name: set user.max_mnt_namespaces using sysctl
    ansible.posix.sysctl:
      name: user.max_mnt_namespaces
      value: '1'
      sysctl_file: /etc/sysctl.d/81-enroot.conf
      reload: yes

  - name: set kernel.unprivileged_userns_clone using sysctl
    ansible.posix.sysctl:
      name: kernel.unprivileged_userns_clone
      value: '1'
      sysctl_file: /etc/sysctl.d/81-enroot.conf
      reload: yes


  - name: Download enroot-check
    get_url:
      url: "https://github.com/NVIDIA/enroot/releases/download/v3.4.0/enroot-check_3.4.0_{{ ansible_architecture }}.run"
      dest: "/tmp"
      mode: '0755'
      owner: "{{ ansible_user }}"
      group: "{{ ansible_user }}"

  - name: execute enroot-check_*.run
    command: bash -c "/tmp/enroot-check_*.run --verify"


  - name: update ENROOT_RUNTIME_PATH
    lineinfile: 
      dest: /etc/enroot/enroot.conf
      state: present
      regexp: '^#ENROOT_RUNTIME_PATH.*'
      line: 'ENROOT_RUNTIME_PATH        {{enroot_top_path}}/enroot_runtime/user-$(id -u)'
      backup: yes

  - name: update ENROOT_DATA_PATH
    lineinfile: 
      dest: /etc/enroot/enroot.conf
      state: present
      regexp: '^#ENROOT_DATA_PATH.*'
      line: 'ENROOT_DATA_PATH        {{enroot_top_path}}/enroot_data/user-$(id -u)'
      backup: yes

  - name: update ENROOT_CACHE_PATH
    lineinfile:
      dest: /etc/enroot/enroot.conf
      state: present
      regexp: '^#ENROOT_CACHE_PATH.*'
      line: 'ENROOT_CACHE_PATH        {{enroot_top_path}}/enroot_cache'
      backup: yes

  - name: update ENROOT_TEMP_PATH
    lineinfile:
      dest: /etc/enroot/enroot.conf
      state: present
      regexp: '^#ENROOT_TEMP_PATH.*'
      line: 'ENROOT_TEMP_PATH        {{enroot_top_path}}/enroot_tmp'
      backup: yes


  - name: set permissions on {{enroot_top_path}}
    become: true
    file:
      path: "{{enroot_top_path}}"
      state: directory
      owner: "{{ ansible_user }}"
      mode: 0777
      group: "{{privilege_group_name}}"
      recurse: no


  - name: Make sure all {{enroot_top_path}} directories exist
    file:
      path: "{{enroot_top_path}}/{{item}}"
      state: directory
      mode: '0775'
      owner: "{{ ansible_user }}"
      group: "{{privilege_group_name}}"
      recurse: no
    with_items: 
      - enroot_data
      - enroot_tmp
      - enroot_cache
      - enroot_runtime

