---
- ansible.builtin.set_fact:
    enroot_top_path_checked: "/etc/enroot/"
  when: " not 'nvme0n1' in ansible_facts[\"devices\"]"

- ansible.builtin.set_fact:
    enroot_top_path_checked: "{{ enroot_top_path }}"
  when: "'nvme0n1' in ansible_facts[\"devices\"]"

- name: Ensure prolog directory exists
  become: true
  ansible.builtin.file:
    path: "{{ slurm_conf_path }}/prolog.d"
    state: directory
    owner: root
    group: root

- name: Copy files
  become: true
  become_method: sudo
  ansible.builtin.template:
    src: pyxis.sh.j2
    dest: "{{ slurm_conf_path }}/prolog.d/pyxis.sh"
    owner: root
    group: root
    mode: "0755"
    force: true
    backup: true

- name: Install required packages
  vars:
    package_name:
      - gcc-c++
      - git
  ansible.builtin.include_role:
    name: safe_yum
  when: ansible_facts['os_family'] == 'RedHat'

- name: Install required packages
  vars:
    package_name:
      - gcc
      - git
      - make
  ansible.builtin.include_role:
    name: safe_yum
  when: ansible_facts['os_family'] == 'Debian'

- name: Check if pyxis directory is present
  ansible.builtin.stat:
    path: "/config/3rdparty/pyxis/{{ ansible_facts['distribution'] }}_{{ ansible_facts['distribution_version'] }}_{{ ansible_facts['architecture'] }}"
  register: pyxis_present

- name: Clone pyxis repo
  ansible.builtin.git:
    repo: https://github.com/NVIDIA/pyxis.git
    dest: "/config/3rdparty/pyxis/{{ ansible_facts['distribution'] }}_{{ ansible_facts['distribution_version'] }}_{{ ansible_facts['architecture'] }}"
  ignore_errors: true
  when: not pyxis_present.stat.exists

- name: Compile
  ansible.builtin.command: bash -c "sudo make install"
  args:
    chdir: "/config/3rdparty/pyxis/{{ ansible_facts['distribution'] }}_{{ ansible_facts['distribution_version'] }}_{{ ansible_facts['architecture'] }}"
  ignore_errors: true

- name: Create plugstack.conf
  become: true
  ansible.builtin.copy:
    dest: "{{ slurm_conf_path }}/plugstack.conf"
    content: |
      required /usr/local/lib/slurm/spank_pyxis.so
    mode: "0775"
    owner: "{{ controller_username }}"
    group: "{{ privilege_group_name }}"
