--- 

- name: install required packages
  vars: 
    package_name: 
      - libev 
      - libev-devel 
      - libevent-devel 
      - hwloc 
  include_role: 
    name: safe_yum
  when: ansible_os_family == 'RedHat'


- name: Download Slurm RPMs
  block:
    - name: Download on each node
      block: 
      - name: Check if the RPMs exist in tmp
        stat: 
          path: "{{ download_path }}/slurm_rpms/{{item}}"
        register: pmix_dwld_tmp
        with_items: "{{pmix_download_packages}}"
      - name: First try downloading RPMs in tmp
        get_url:
          url: "https://objectstorage.eu-frankfurt-1.oraclecloud.com/p/lQBJduG5m6xQWauRMPkouaOoliEHbbDIqgfQXou050XAcDav2UveFlRjvFv-0JIn/n/hpc_limited_availability/b/source/o/pmix/{{ item.item }}"        
          dest: "{{ download_path }}/slurm_rpms"
        when: ( not item.stat.exists )
        with_items: "{{pmix_dwld_tmp.results}}"
      when: download_path == '/tmp'

    - name: Download in shared location
      block:   
      - name: Check if the RPMs exist
        stat: 
          path: "{{ download_path }}/slurm_rpms/{{item}}"
        register: pmix_dwld
        delegate_to: 127.0.0.1
        run_once: true
        with_items: "{{pmix_download_packages}}"
      - name: First try downloading RPMs
        get_url:
          url: "https://objectstorage.eu-frankfurt-1.oraclecloud.com/p/lQBJduG5m6xQWauRMPkouaOoliEHbbDIqgfQXou050XAcDav2UveFlRjvFv-0JIn/n/hpc_limited_availability/b/source/o/pmix/{{ item.item }}"        
          dest: "{{ download_path }}/slurm_rpms"
        when: ( not item.stat.exists )
        delegate_to: 127.0.0.1
        run_once: true  
        with_items: "{{pmix_dwld.results}}"
      when: download_path != '/tmp'
      
  rescue:
    - name: Second try downloading RPMs
      get_url:
        url: "https://objectstorage.eu-frankfurt-1.oraclecloud.com/p/tgnPgvPv68JpWqLklTNY86rBsJ0z7Ebp3zs7Ud4X2_R8TZFgpm26kh08QHKI3dXU/n/hpc/b/source/o/pmix/{{item}}"
        dest: "{{ download_path }}/slurm_rpms"
      when: download_path != '/tmp'
      delegate_to: 127.0.0.1
      run_once: true
      with_items: "{{pmix_download_packages}}"
    - name: Second try downloading RPMs in tmp
      get_url:
        url: "https://objectstorage.eu-frankfurt-1.oraclecloud.com/p/tgnPgvPv68JpWqLklTNY86rBsJ0z7Ebp3zs7Ud4X2_R8TZFgpm26kh08QHKI3dXU/n/hpc/b/source/o/pmix/{{item}}"
        dest: "{{ download_path }}/slurm_rpms"
      when: download_path == '/tmp'
      with_items: "{{pmix_download_packages}}"
  when: ansible_os_family == 'RedHat'

- name: install PMIx packages RedHat
  vars:
    package_name: '{{ pmix_packages }}'
    disable_gpg_check_var: True
  include_role:
    name: safe_yum
  when: ansible_os_family == 'RedHat'