---
- name: Edit /etc/security/access.conf
  become: true
  blockinfile:
    dest: /etc/security/access.conf
    block: |
      +:root:ALL
      +:wheel:ALL
      +:opc:ALL
      -:ALL:ALL
  when: ansible_os_family == 'RedHat'

- name: Edit /etc/security/access.conf
  become: true
  blockinfile:
    dest: /etc/security/access.conf
    block: |
      +:root:ALL
      +:wheel:ALL
      +:ubuntu:ALL
      -:ALL:ALL
  when: ansible_distribution == 'Ubuntu'

- name: Copy sshd file
  become: true
  copy:
    src: sshd
    dest: /etc/pam.d/sshd
  when: ansible_os_family == 'RedHat'

- name: Add required pam account permission
  become: true
  lineinfile:
    path: /etc/pam.d/sshd
    line: "account    required      /usr/local/lib/security/pam_slurm_adopt.so"
    state: present
    backup: yes
    insertafter: EOF
  when: ansible_distribution == 'Ubuntu'

- name: Comment pam_systemd.so in /etc/pam.d/common-session
  become: true
  lineinfile:
    path: /etc/pam.d/common-session
    regexp: 'pam_systemd.so$'
    line: "#session        optional        pam_systemd.so"
    state: present
    backup: yes
  when: ansible_distribution == 'Ubuntu'

- name: Comment pam_systemd.so in /etc/pam.d/runuser-l
  become: true
  lineinfile:
    path: /etc/pam.d/runuser-l
    regexp: 'pam_systemd.so$'
    line: "#-session       optional        pam_systemd.so"
    state: present
    backup: yes
  when: ansible_distribution == 'Ubuntu'

- name: Comment pam_systemd.so in /etc/pam.d/systemd-user
  become: true
  lineinfile:
    path: /etc/pam.d/systemd-user
    regexp: 'pam_systemd.so$'
    line: "#session optional pam_systemd.so"
    state: present
    backup: yes
  when: ansible_distribution == 'Ubuntu'

- name: Comment pam_access.so in /etc/pam.d/common-auth
  become: true
  lineinfile:
    path: /etc/pam.d/common-auth
    regexp: 'pam_access.so$'
    line: "#account required    pam_access.so"
    state: present
    backup: yes
  when: ansible_distribution == 'Ubuntu'

- name: Stop logind
  become: true
  systemd:
    name: systemd-logind
    state: stopped
    enabled: no
    masked: yes
