---
- name: Ensure AutoDetect=nvml is present after "#GRES.conf" in gres.conf
  become: true
  ansible.builtin.lineinfile:
    path: "{{ slurm_conf_path }}/gres.conf"
    line: "AutoDetect=nvml"
    insertafter: '^#GRES\.conf'

- name: Add explicit AMD GPU node blocks to gres.conf (with markers)
  become: true
  ansible.builtin.blockinfile:
    block: "{{ lookup('template', 'gres.conf.j2') }}"
    path: "{{ slurm_conf_path }}/gres.conf"
    marker: "### {mark} {{ item.value.hostname }}"
  when: item.value.shape in ["BM.GPU.MI300X.8", "BM.GPU.MI355X-v0.8", "BM.GPU.MI355X.8", "BM.GPU.MI355X-v1.8"]
  with_items: "{{ new_compute_info | dict2items }}"

- name: Populate nodes_to_add with cluster_name as key and list of hostnames as value
  ansible.builtin.set_fact:
    nodes_to_add: "{{ nodes_to_add | default({}) | combine({item.value.cluster_name: (nodes_to_add[item.value.cluster_name] | default([])) + [item.value.hostname]})
      }}"
  with_items: "{{ new_compute_info | dict2items }}"

- name: Transform input_dict to group by cluster_name
  ansible.builtin.set_fact:
    clusters: {}

- name: Transform input_dict to group by cluster_name
  ansible.builtin.set_fact:
    clusters: >-
      {{
        clusters | combine({
          item.value.cluster_name:
          (clusters[item.value.cluster_name] | default([])) + [item.value.hostname]
        })
      }}
  with_items: "{{ new_compute_info | dict2items }}"

- name: Get nodes from Cluster Switch
  block:
    - name: Get nodes from topology.conf
      ansible.builtin.shell: "cat {{ slurm_conf_path }}/topology.conf | grep \"SwitchName={{item}}\""
      register: cluster_switch
      with_items: "{{clusters}}"

    - name: Get cluster_hostlist
      ansible.builtin.command: "scontrol show hostname {{item.stdout.split('Nodes=')[1]}}"
      register: cluster_hostlist
      with_items: "{{cluster_switch.results}}"

    - name: Create new cluster_hostlist
      ansible.builtin.command: "scontrol show hostlistsorted {{item.stdout_lines | union(clusters[item.item.item]) | join(',') }}"
      register: cluster_hostlist_condensed_results
      with_items: "{{cluster_hostlist.results}}"

    - name: Create new cluster_hostlist
      ansible.builtin.command: "scontrol show hostlistsorted {{item.stdout_lines | union(clusters[item.item.item]) | join(',') }}"
      register: cluster_hostlist_condensed_results
      with_items: "{{cluster_hostlist.results}}"

    - name: Add nodes to Switch
      become: true
      ansible.builtin.lineinfile:
        path: "{{ slurm_conf_path }}/topology.conf"
        regexp: "SwitchName={{ item.item.item.item }}\\sNodes.*"
        line: "SwitchName={{ item.item.item.item }} Nodes={{ item.stdout }}"
        state: present
      with_items: "{{cluster_hostlist_condensed_results.results}}"
      run_once: true
      delegate_to: 127.0.0.1
      notify: Reconfigure slurm

  rescue:
    - name: Create existing cluster list
      ansible.builtin.command: "scontrol show hostlistsorted {{ clusters[item] | join(',') }}"
      register: cluster_hostlist_condensed_results
      with_items: "{{ clusters }}"
    - name: Add nodes to Switch
      become: true
      ansible.builtin.lineinfile:
        path: "{{ slurm_conf_path }}/topology.conf"
        regexp: "SwitchName={{ item.item }}\\sNodes.*"
        line: "SwitchName={{ item.item }} Nodes={{ item.stdout }}"
        state: present
      with_items: "{{ cluster_hostlist_condensed_results.results }}"
      run_once: true
      delegate_to: 127.0.0.1
      notify: Reconfigure slurm

- name: Run handlers
  ansible.builtin.meta: flush_handlers
- name: Reconfigure slurm
  become: true
  ansible.builtin.command: "scontrol reconfigure"
  register: result
  until: result is not failed
  retries: 5
  delay: 5
