---
- name: change Node Status
  become: true
  command: "scontrol update nodename={{ ansible_hostname }} state=future reason=terminating"
  ignore_errors: true
  ignore_unreachable: True
  delegate_to: 127.0.0.1

- name: Remove to the gres.conf file on the controller.
  become: true
  blockinfile:
    path: "{{ slurm_conf_path }}/gres.conf"
    marker: "### {mark} {{ansible_hostname}}"
  delegate_to: 127.0.0.1

- name: Get nodes from Cluster Switch
  block:
    - name: Get nodes from topology.conf
      shell: "cat {{ slurm_conf_path }}/topology.conf | grep \"SwitchName={{cluster_name}}\""
      register: cluster_switch_condensed
      run_once: true
      delegate_to: 127.0.0.1
    - name: Get actual cluster list
      command: "scontrol show hostname {{cluster_switch_condensed.stdout.split('Nodes=')[1] }}"
      register: cluster_switch
      run_once: true
      delegate_to: 127.0.0.1
    - name: Create existing cluster list
      set_fact:
        cluster_list: "{{cluster_switch.stdout_lines}}"
  rescue:
    - name: Create existing cluster list
      set_fact:
        cluster_list: []

- name: Get hostnames
  set_fact:
    nodes_to_add_temp: "{{hostvars[item]['ansible_hostname']}}"
  with_items: "{{ play_hosts | difference(groups['controller']) | difference(groups['slurm_backup'])  | difference(groups['login']) | difference(groups['monitoring']) }}"
  run_once: true
  register: nodes_to_add_temp_results

- name: Make a list
  set_fact: nodes_to_add="{{nodes_to_add_temp_results.results | map(attribute='ansible_facts.nodes_to_add_temp') | list}}"
  run_once: true

- name: Get new cluster_list
  command: "scontrol show hostlistsorted {{cluster_list | difference(nodes_to_add) | join(',') }}"
  register: new_cluster_list
  run_once: true
  delegate_to: 127.0.0.1
  when: cluster_list | difference(nodes_to_add) | length > 0

- name: remove nodes from Switch
  become: true
  lineinfile:
    path: "{{ slurm_conf_path }}/topology.conf"
    regexp: "SwitchName={{cluster_name}}\\sNodes.*"
    line: "SwitchName={{cluster_name}} Nodes={{new_cluster_list.stdout}}"
    state: present
  run_once: true
  delegate_to: 127.0.0.1
  when: cluster_list | difference(nodes_to_add) | join(',') != ''

- name: remove cluster from Switch
  become: true
  lineinfile:
    path: "{{ slurm_conf_path }}/topology.conf"
    regexp: "SwitchName={{cluster_name}}\\sNodes.*"
    state: absent
  run_once: true
  delegate_to: 127.0.0.1
  when: cluster_list | difference(nodes_to_add) | join(',') == ''

- name: change Node Status
  become: true
  command: "scontrol delete nodename={{ ansible_hostname }}"
  ignore_errors: true
  ignore_unreachable: True
  delegate_to: 127.0.0.1

- name: Reconfigure Slurm for topology
  become: true
  command: "scontrol reconfigure"
  delegate_to: 127.0.0.1
  run_once: true
  ignore_errors: true