---

#- name: Download Packages
  #block:    
- name: Create Slurm directory
  file:
    path: "{{ download_path }}/slurm_rpms"
    state: directory
- name: Download slurm RPMs.
  get_url:
    url: "https://objectstorage.eu-frankfurt-1.oraclecloud.com/p/VnkLhYXOSNVilVa9d24Riz1fz4Ul-KTXeK4HCKoyqv0ghW3gry3Xz8CZqloqphLw/n/hpc/b/source/o/slurm/{{ item }}"
    dest: "{{ download_path }}/slurm_rpms"
  with_items:
    - "slurm-{{slurm_version}}.el7.x86_64.rpm"
    - "slurm-contribs-{{slurm_version}}.el7.x86_64.rpm"
    - "slurm-devel-{{slurm_version}}.el7.x86_64.rpm"
    - "slurm-example-configs-{{slurm_version}}.el7.x86_64.rpm"
    - "slurm-libpmi-{{slurm_version}}.el7.x86_64.rpm"
    - "slurm-openlava-{{slurm_version}}.el7.x86_64.rpm"
    - "slurm-pam_slurm-{{slurm_version}}.el7.x86_64.rpm"
    - "slurm-perlapi-{{slurm_version}}.el7.x86_64.rpm"
    - "slurm-slurmctld-{{slurm_version}}.el7.x86_64.rpm"
    - "slurm-slurmd-{{slurm_version}}.el7.x86_64.rpm"
    - "slurm-slurmdbd-{{slurm_version}}.el7.x86_64.rpm"
    - "slurm-torque-{{slurm_version}}.el7.x86_64.rpm"
  run_once: true

#  rescue:
#    - name: Repository
#      become: true
#      yum_repository:
#        name: oci-hpc
#        description: oci-hpc
#        baseurl: https://objectstorage.us-ashburn-1.oraclecloud.com/n/hpc/b/rpms/o/
#        gpgcheck: no
#        enabled: yes
#        retries: 3