---
- name: download slurm Packages
  include_tasks: download.yml
  when: ('bastion' in group_names) and not destroy and initial| bool

- name: include common tasks
  include_tasks: common.yml
  when: (not destroy) and ((initial) or (not initial and ('compute' in group_names)))|bool

- name: run server directives
  include_tasks: server.yml
  when: ('bastion' in group_names) and not destroy and initial| bool

- name: run compute directives
  include_tasks: compute.yml
  when: ('compute' in group_names) and not destroy | bool

- name: cleanup
  include_tasks: cleanup.yml
  when: ('compute' in group_names) and not destroy | bool

- name: destroy
  include_tasks: destroy.yml
  when: ('compute' in group_names) and destroy | bool