---
#- name: download slurm Packages
#  include_tasks: download.yml
#  when: ('bastion' in group_names) and (not destroy|bool) and (initial|bool) and (cluster_nfs|bool)

#- name: download slurm Packages
#  include_tasks: download.yml
#  when: (not destroy|bool) and (not cluster_nfs|bool)

- name: include common tasks
  vars: 
    slurm_repos: "epel,ol7_developer_EPEL"
  include_tasks: common.yml
  when: (not destroy|bool) and ((initial|bool) or (not initial|bool and ('compute' in group_names)))

- name: run server directives ol8 bastion
  vars:
    slurm_repos: "ol8_developer_EPEL,ol8_codeready_builder"
  include_tasks: server.yml
  when: ('bastion' in group_names) and (not destroy|bool) and (initial| bool) and ansible_distribution_major_version == '8'

- name: run server directives ol7 bastion
  vars: 
    slurm_repos: "epel,ol7_developer_EPEL"
  include_tasks: server.yml
  when: ('bastion' in group_names) and (not destroy|bool) and (initial| bool) and ansible_distribution_major_version == '7'

- name: run compute directives
  vars: 
    slurm_repos: "epel,ol7_developer_EPEL"
  include_tasks: "compute{{rack_aware_playbook_suffix}}.yml"
  when: ('compute' in group_names) and (not destroy|bool)

- name: run login server directives
  vars: 
    slurm_repos: "epel,ol7_developer_EPEL"
  include_tasks: login.yml
  when: ('login' in group_names) and (not destroy|bool) and (initial| bool)

- name: run backup server directives
  vars: 
    slurm_repos: "epel,ol7_developer_EPEL"
  include_tasks: backup_server.yml
  when: ('slurm_backup' in group_names) and (not destroy|bool) and (initial| bool)

- name: cleanup
  include_tasks: cleanup.yml
  when: ('compute' in group_names) and (not destroy|bool)

- name: destroy
  include_tasks: destroy{{rack_aware_playbook_suffix}}.yml
  when: ('compute' in group_names or 'compute_to_destroy' in group_names) and (destroy|bool)

- name: move topology.conf on backup slurm controller
  include_tasks: move-topology.yml
  when: ('slurm_backup' in group_names) and (not initial| bool)
