---
- name: Install SLURM login packages
  vars:
    package_name: "{{ slurm_login_packages }}"
    package_repo: "{{ slurm_repos }}"
    disable_gpg_check_var: true
  ansible.builtin.include_role:
    name: safe_yum

- name: Render systemd units for sackd
  become: true
  ansible.builtin.template:
    src: "systemd/{{ item }}.service.j2"
    dest: "/lib/systemd/system/{{ item }}.service"
    backup: true
  with_items:
    - sackd
  when: ansible_facts['os_family'] == 'Debian'

- name: Create systemd unit dirs for sackd and munge
  become: true
  ansible.builtin.file:
    name: "/etc/systemd/system/{{ item }}.service.d"
    state: directory
  with_items:
    - munge
    - sackd

- name: Render systemd units for sackd and munge
  become: true
  ansible.builtin.template:
    src: "systemd/{{ item }}.service.d/unit.conf.j2"
    dest: "/etc/systemd/system/{{ item }}.service.d/unit.conf"
    backup: true
  with_items:
    - munge
    - sackd

- name: Create munge dir
  become: true
  ansible.builtin.file:
    name: "{{ munge_conf_path }}"
    state: directory
    owner: munge
    group: munge
    mode: "0700"

- name: Copy munge key
  become: true
  ansible.builtin.copy:
    src: /config/key/munge.key
    dest: /etc/munge/munge.key
    owner: munge
    group: munge
    mode: "0400"
  notify: Restart munge
  register: job_result
  until: job_result is not failed
  retries: 10
  delay: 30

- name: Restart munge
  become: true
  ansible.builtin.service:
    name: munge
    state: restarted
    enabled: true

- name: Start sackd
  become: true
  ansible.builtin.service:
    name: sackd
    state: restarted
    enabled: true
  retries: 10
  delay: 30
  register: job_result
  until: job_result is not failed
