---
- name: Remove from the gres.conf file on the controller
  become: true
  ansible.builtin.blockinfile:
    path: "{{ slurm_conf_path }}/gres.conf"
    marker: "### {mark} {{ item.value.hostname }}"
    state: absent
  delegate_to: 127.0.0.1
  when: item.value.shape in ["BM.GPU.MI300X.8", "BM.GPU.MI355X-v0.8", "BM.GPU.MI355X.8", "BM.GPU.MI355X-v1.8"]
  with_items: "{{ remove_compute_info | dict2items }}"

- name: Remove deleted nodes from Slurm
  become: true
  ansible.builtin.command: "scontrol delete nodename={{ item }}"
  ignore_errors: true
  with_items: "{{ remove_compute_info | dict2items | map(attribute='value.hostname') | list }}"
  when: ('controller' in group_names)

- name: Regenerate topology.yaml after removing compute nodes
  vars:
    reconfigure_slurm_state: true
  ansible.builtin.include_tasks: generate-topology.yml

- name: Run handlers
  ansible.builtin.meta: flush_handlers
