---
- name: Remove from the gres.conf file on the controller.
  become: true
  ansible.builtin.blockinfile:
    path: "{{ slurm_conf_path }}/gres.conf"
    marker: "### {mark} {{ item.value.hostname }}"
    state: absent
  delegate_to: 127.0.0.1
  when: item.value.shape in ["BM.GPU.MI300X.8", "BM.GPU.MI355X-v0.8", "BM.GPU.MI355X.8", "BM.GPU.MI355X-v1.8"]
  with_items: "{{ remove_compute_info | dict2items }}"

- name: Create a list of hostnames to remove
  ansible.builtin.set_fact:
    hostnames_list: "{{ remove_compute_info | dict2items | map(attribute='value.hostname') | list }}"

- name: Get SwitchLine
  ansible.builtin.shell: "scontrol show hostname `scontrol show topology {{item}}  | rev | cut -d \"=\" -f 1 | rev`"
  register: current_switch
  run_once: true
  delegate_to: 127.0.0.1
  with_items: "{{hostnames_list}}"

- name: GetNodes
  ansible.builtin.set_fact:
    nodes_on_switch: "{{ nodes_on_switch | default({}) | combine({item.item: item.stdout_lines}) }}"
  with_items: "{{current_switch.results}}"
  run_once: true
  delegate_to: 127.0.0.1
  when: ( item.stdout_lines | length ) > 0

- name: GetNodes
  ansible.builtin.set_fact:
    nodes_on_switch: "{{ nodes_on_switch | default({}) | combine({item.item: []}) }}"
  with_items: "{{current_switch.results}}"
  run_once: true
  delegate_to: 127.0.0.1
  when: ( item.stdout_lines | length ) == 0

- name: Get SwitchNames
  ansible.builtin.shell: "scontrol show topology {{item}} | awk '{print $1}' | cut -d \"=\" -f 2"
  register: current_switchName
  run_once: true
  delegate_to: 127.0.0.1
  with_items: "{{hostnames_list}}"

- name: Get Switchname
  ansible.builtin.set_fact:
    switchnames: "{{ switchnames | default({}) | combine({item.item: item.stdout}) }}"
  with_items: "{{current_switchName.results}}"
  run_once: true
  delegate_to: 127.0.0.1
  when: ( item.stdout_lines | length ) > 0

- name: Get Switchname
  ansible.builtin.set_fact:
    switchnames: "{{ switchnames | default({}) | combine({item.item: \"\"}) }}"
  with_items: "{{current_switchName.results}}"
  run_once: true
  delegate_to: 127.0.0.1
  when: ( item.stdout_lines | length ) == 0

- name: Remove line from topology
  ansible.builtin.lineinfile:
    path: "{{ slurm_conf_path }}/topology.conf"
    regexp: "SwitchName={{ switchnames[item] }}\\sNodes=.*"
    state: absent
  with_items: "{{hostnames_list}}"
  ignore_unreachable: true
  when: ( ( nodes_on_switch[item] | length ) < 2 ) and ( switchnames[item] | length ) > 1
  run_once: true
  delegate_to: 127.0.0.1

- name: Generate nodes_on_switch_condensed
  ansible.builtin.command: "scontrol show hostlistsorted {{nodes_on_switch[item] | difference(hostnames_list) | join(',')}}"
  register: switch_condensed
  with_items: "{{hostnames_list}}"
  ignore_unreachable: true
  when: ( ( nodes_on_switch[item] | difference(hostnames_list) | length ) > 1 ) and ( switchnames[item] | length ) > 1
  run_once: true
  delegate_to: 127.0.0.1

- name: Get condensed_Nodes
  ansible.builtin.set_fact:
    nodes_on_switch_condensed: "{{ nodes_on_switch_condensed | default({}) | combine({item.item: item.stdout}) }}"
  with_items: "{{switch_condensed.results}}"
  run_once: true
  delegate_to: 127.0.0.1
  ignore_errors: true

- name: Remove line from topology
  ansible.builtin.lineinfile:
    path: "{{ slurm_conf_path }}/topology.conf"
    regexp: "SwitchName={{ switchnames[item] }}\\sNodes.*"
    line: "SwitchName={{ switchnames[item] }} Nodes={{ nodes_on_switch_condensed[item] }}"
    state: present
  with_items: "{{hostnames_list}}"
  ignore_errors: true
  when: ( ( nodes_on_switch_condensed[item] | length ) > 1 )
  run_once: true
  delegate_to: 127.0.0.1

- name: Change Node Status
  become: true
  ansible.builtin.command: "scontrol delete nodename={{ item }}"
  ignore_errors: true
  ignore_unreachable: true
  with_items: "{{hostnames_list}}"
  delegate_to: 127.0.0.1
  when: ('controller' in group_names)

- name: Move topology.conf on backup servers
  become: true
  ansible.builtin.copy:
    dest: "{{ slurm_conf_path }}/topology.conf"
    src: "{{ slurm_conf_path }}/topology.conf"
    force: true
  register: topology_copied
  until: topology_copied is not failed
  retries: 10
  delay: 5
  when: ('slurm_backup' in group_names)

- name: Reconfigure slurm
  become: true
  ansible.builtin.command: "scontrol reconfigure"
  register: result
  until: result is not failed
  retries: 5
  delay: 5
