---
- name: Remove from the gres.conf file on the controller.
  become: true
  ansible.builtin.blockinfile:
    path: "{{ slurm_conf_path }}/gres.conf"
    marker: "### {mark} {{ item.value.hostname }}"
    state: absent
  delegate_to: 127.0.0.1
  when: item.value.shape in ["BM.GPU.MI300X.8", "BM.GPU.MI355X-v0.8", "BM.GPU.MI355X.8", "BM.GPU.MI355X-v1.8"]
  with_items: "{{ remove_compute_info | dict2items }}"

- name: Remove nodes from current topology before adding them
  block:
    - name: debug
      ansible.builtin.debug:
        var: remove_compute_info
    - name: Create a list of hostnames to remove
      ansible.builtin.set_fact:
        hostnames_list: "{{ remove_compute_info | dict2items | map(attribute='value.hostname') | list }}"
    - name: debug
      ansible.builtin.debug:
        var: hostnames_list

 # get Info from the Rack Switches
    - name: Get RackLine
      ansible.builtin.shell: "scontrol show hostname `scontrol show topology {{item}} | grep Level=0 | rev | cut -d \"=\" -f 1 | rev`"
      register: current_switch
      run_once: true
      with_items: "{{hostnames_list}}"

    - name: GetNodes
      ansible.builtin.set_fact:
        rem_nodes_on_switch: "{{ rem_nodes_on_switch | default({}) | combine({item.item: item.stdout_lines}) }}"
      with_items: "{{current_switch.results}}"
      run_once: true
      when: ( item.stdout_lines | length ) > 0

    - name: GetNodes
      ansible.builtin.set_fact:
        rem_nodes_on_switch: "{{ rem_nodes_on_switch | default({}) | combine({item.item: []}) }}"
      with_items: "{{current_switch.results}}"
      run_once: true
      when: ( item.stdout_lines | length ) == 0

    - name: Get SwitchNames
      ansible.builtin.shell: "scontrol show topology {{item}} | grep Level=0 | awk '{print $1}' | cut -d \"=\" -f 2"
      register: current_switchName
      run_once: true
      with_items: "{{hostnames_list}}"

    - name: Get Switchname
      ansible.builtin.set_fact:
        rem_switchnames_dict: "{{ rem_switchnames_dict | default({}) | combine({item.item: item.stdout}) }}"
      with_items: "{{current_switchName.results}}"
      run_once: true
      when: ( item.stdout_lines | length ) > 0

    - name: Get Switchname
      ansible.builtin.set_fact:
        rem_switchnames_dict: "{{ rem_switchnames_dict | default({}) | combine({item.item: \"\"}) }}"
      with_items: "{{current_switchName.results}}"
      run_once: true
      when: ( item.stdout_lines | length ) == 0

    - name: Build a dict of the racks including nodes to remove
      ansible.builtin.set_fact:
        rem_racks_dict: "{{ rem_racks_dict | default({}) | combine({rem_switchnames_dict[item]: rem_nodes_on_switch[item]}) }}"
      with_items: "{{hostnames_list}}"
      run_once: true

    - name: create an empty rem_racks_dict list
      ansible.builtin.set_fact:
        rem_racks_dict: "{{ rem_racks_dict | default({}) }}"
      run_once: true

    - name: Build a list of unique rem_switchnames
      ansible.builtin.set_fact:
        rem_switchnames: "{{ rem_racks_dict.keys() | default([]) | list | unique }}"
      run_once: true

 # get Info from the Network Block Switches

    - name: Get Network Block line
      ansible.builtin.shell: "scontrol show hostname `scontrol show topology {{item}} | grep Level=1 | rev | cut -d \"=\" -f 1 | rev`"
      register: current_nb
      run_once: true
      with_items: "{{hostnames_list}}"

    - name: GetSwitches
      ansible.builtin.set_fact:
        rem_switches_on_nb: "{{ rem_switches_on_nb | default({}) | combine({item.item: item.stdout_lines}) }}"
      with_items: "{{current_nb.results}}"
      run_once: true
      when: ( item.stdout_lines | length ) > 0

    - name: GetSwitches
      ansible.builtin.set_fact:
        rem_switches_on_nb: "{{ rem_switches_on_nb | default({}) | combine({item.item: []}) }}"
      with_items: "{{current_nb.results}}"
      run_once: true
      when: ( item.stdout_lines | length ) == 0

    - name: Get NetworkBlock Name
      ansible.builtin.shell: "scontrol show topology {{item}} | grep Switches= | grep Level=1 | awk '{print $1}' | cut -d \"=\" -f 2"
      register: current_NetworkBlockName
      run_once: true
      with_items: "{{hostnames_list}}"

    - name: Get NetworkBlock Name
      ansible.builtin.set_fact:
        rem_rem_networkblocknames_dict: "{{ rem_rem_networkblocknames_dict | default({}) | combine({item.item: item.stdout}) }}"
      with_items: "{{current_NetworkBlockName.results}}"
      run_once: true
      when: ( item.stdout_lines | length ) > 0

    - name: Get NetworkBlock Name
      ansible.builtin.set_fact:
        rem_rem_networkblocknames_dict: "{{ rem_rem_networkblocknames_dict | default({}) | combine({item.item: \"\"}) }}"
      with_items: "{{current_NetworkBlockName.results}}"
      run_once: true
      when: ( item.stdout_lines | length ) == 0

    - name: Build a dict of the nbs including nodes to remove
      ansible.builtin.set_fact:
        rem_nb_dict: "{{ rem_nb_dict | default({}) | combine({rem_rem_networkblocknames_dict[item]: rem_switches_on_nb[item]}) }}"
      with_items: "{{hostnames_list}}"
      run_once: true

    - name: create an empty rem_nb_dict list
      ansible.builtin.set_fact:
        rem_nb_dict: "{{ rem_nb_dict | default({}) }}"
      run_once: true

    - name: Build a list of unique rem_switchnames
      ansible.builtin.set_fact:
        rem_networkblocknames: "{{ rem_nb_dict.keys() | default([]) | list | unique }}"
      run_once: true

 # get Info from the Cluster Switches

    - name: Get Cluster line
      ansible.builtin.shell: "scontrol show hostname `scontrol show topology {{item}} | grep Level=2 | rev | cut -d \"=\" -f 1 | rev`"
      register: current_cluster
      run_once: true
      with_items: "{{hostnames_list}}"

    - name: GetNBs
      ansible.builtin.set_fact:
        nb_on_cluster: "{{ nb_on_cluster | default({}) | combine({item.item: item.stdout_lines}) }}"
      with_items: "{{current_cluster.results}}"
      run_once: true
      when: ( item.stdout_lines | length ) > 0

    - name: GetNBs
      ansible.builtin.set_fact:
        nb_on_cluster: "{{ nb_on_cluster | default({}) | combine({item.item: []}) }}"
      with_items: "{{current_cluster.results}}"
      run_once: true
      when: ( item.stdout_lines | length ) == 0

    - name: Get Cluster Name
      ansible.builtin.shell: "scontrol show topology {{item}} | grep Switches= | grep Level=2 | awk '{print $1}' | cut -d \"=\" -f 2"
      register: current_ClusterName
      run_once: true
      with_items: "{{hostnames_list}}"

    - name: Get Cluster Name
      ansible.builtin.set_fact:
        rem_clusternames_dict: "{{ rem_clusternames_dict | default({}) | combine({item.item: item.stdout}) }}"
      with_items: "{{current_ClusterName.results}}"
      run_once: true
      when: ( item.stdout_lines | length ) > 0

    - name: Get Cluster Name
      ansible.builtin.set_fact:
        rem_clusternames_dict: "{{ rem_clusternames_dict | default({}) | combine({item.item: \"\"}) }}"
      with_items: "{{current_ClusterName.results}}"
      run_once: true
      when: ( item.stdout_lines | length ) == 0

    - name: Build a dict of the clusters including nodes to remove
      ansible.builtin.set_fact:
        rem_cluster_dict: "{{ rem_cluster_dict | default({}) | combine({rem_clusternames_dict[item]: nb_on_cluster[item]}) }}"
      with_items: "{{hostnames_list}}"
      run_once: true

    - name: create an empty rem_cluster_dict
      ansible.builtin.set_fact:
        rem_cluster_dict: "{{ rem_cluster_dict | default({}) }}"
      run_once: true

    - name: Build a list of unique rem_switchnames
      ansible.builtin.set_fact:
        rem_clusternames: "{{ rem_cluster_dict.keys() | list | unique }}"
      run_once: true

    - name: debug rem_switchnames
      ansible.builtin.debug:
        var: rem_switchnames

    - name: debug rem_racks_dict
      ansible.builtin.debug:
        var: rem_racks_dict

    - name: debug rem_networkblocknames
      ansible.builtin.debug:
        var: rem_networkblocknames

    - name: debug rem_nb_dict
      ansible.builtin.debug:
        var: rem_nb_dict

    - name: debug rem_clusternames
      ansible.builtin.debug:
        var: rem_clusternames

    - name: debug rem_cluster_dict
      ansible.builtin.debug:
        var: rem_cluster_dict

# Find which Racks need to be removed
# List all racks from the hosts to remove and check if theyre are nodes left

    - name: Create empty list
      ansible.builtin.set_fact:
        switchname_to_remove: []
      run_once: true

    - name: Create a list of rem_switchnames to remove
      ansible.builtin.set_fact:
        switchname_to_remove: "{{ switchname_to_remove | default([]) + [item] | unique }}"
      with_items: "{{rem_switchnames}}"
      when: ( ( rem_racks_dict[item] | difference(hostnames_list) | length ) < 1 )
      run_once: true

    - name: Remove line from topology
      become: true
      ansible.builtin.lineinfile:
        path: "{{ slurm_conf_path }}/topology.conf"
        regexp: "SwitchName={{ item }}\\sNodes=.*"
        state: absent
      with_items: "{{switchname_to_remove}}"
      run_once: true
      notify: Reconfigure slurm

    - name: Generate rem_nodes_on_switch_condensed
      ansible.builtin.command: "scontrol show hostlistsorted {{rem_racks_dict[item] | difference(hostnames_list) | join(',')}}"
      register: switch_condensed
      with_items: "{{rem_switchnames}}"
      when: ( ( rem_racks_dict[item] | difference(hostnames_list) | length ) > 0 )
      run_once: true

    - name: Get condensed_Nodes
      ansible.builtin.set_fact:
        rem_nodes_on_switch_condensed: "{{ rem_nodes_on_switch_condensed | default({}) | combine({item.item: item.stdout}) }}"
      with_items: "{{switch_condensed.results}}"
      when: ( ( rem_racks_dict[item.item] | difference(hostnames_list) | length ) > 0 )
      run_once: true
      ignore_errors: true

    - name: debug rem_nodes_on_switch_condensed
      ansible.builtin.debug:
        var: rem_nodes_on_switch_condensed
      when: rem_nodes_on_switch_condensed is defined
    - name: Remove node from line
      become: true
      ansible.builtin.lineinfile:
        path: "{{ slurm_conf_path }}/topology.conf"
        regexp: "SwitchName={{ item }}\\sNodes.*"
        line: "SwitchName={{ item }} Nodes={{ rem_nodes_on_switch_condensed[item] }}"
        state: present
      with_items: "{{rem_switchnames}}"
      ignore_errors: true
      when: ( ( rem_racks_dict[item] | difference(hostnames_list) | length ) > 0 )
      run_once: true
      notify: Reconfigure slurm

# Find which Network Blocks need to be removed
# List all Network Blocks from the hosts to remove and check if theyre are racks left

    - name: Create empty list
      ansible.builtin.set_fact:
        rem_networkblocknames_to_remove: []
      run_once: true

    - name: Create a list of rem_networkblocknames to remove
      ansible.builtin.set_fact:
        rem_networkblocknames_to_remove: "{{ rem_networkblocknames_to_remove | default([]) + [item] | unique }}"
      with_items: "{{rem_networkblocknames}}"
      when: ( ( rem_nb_dict[item] | difference(switchname_to_remove) | length ) < 1 )
      run_once: true

    - name: Remove line from topology
      become: true
      ansible.builtin.lineinfile:
        path: "{{ slurm_conf_path }}/topology.conf"
        regexp: "SwitchName={{ item }}\\sSwitches=.*"
        state: absent
      with_items: "{{rem_networkblocknames_to_remove}}"
      run_once: true
      notify: Reconfigure slurm

    - name: Get condensed_Nodes
      ansible.builtin.set_fact:
        racks_on_nb_condensed: "{{ racks_on_nb_condensed | default({}) | combine({item: rem_nb_dict[item] | difference(switchname_to_remove) | join(',')}) }}"
      with_items: "{{rem_networkblocknames}}"
      when: ( ( rem_nb_dict[item] | difference(switchname_to_remove) | length ) > 0 )
      run_once: true
      ignore_errors: true

    - name: debug racks_on_nb_condensed
      ansible.builtin.debug:
        var: racks_on_nb_condensed

    - name: Remove node from line
      become: true
      ansible.builtin.lineinfile:
        path: "{{ slurm_conf_path }}/topology.conf"
        regexp: "SwitchName={{ item }}\\sSwitches.*"
        line: "SwitchName={{ item }} Switches={{ racks_on_nb_condensed[item] }}"
        state: present
      with_items: "{{rem_networkblocknames}}"
      ignore_errors: true
      when: ( ( rem_nb_dict[item] | difference(switchname_to_remove) | length ) > 0 )
      run_once: true
      notify: Reconfigure slurm

# Find which Network Blocks need to be removed
# List all Network Blocks from the hosts to remove and check if theyre are racks left

    - name: Create empty list
      ansible.builtin.set_fact:
        clusternames_to_remove: []
      run_once: true

    - name: Create a list of clusternames to remove
      ansible.builtin.set_fact:
        clusternames_to_remove: "{{ clusternames_to_remove | default([]) + [item] | unique }}"
      with_items: "{{rem_clusternames}}"
      when: ( ( rem_cluster_dict[item] | difference(rem_networkblocknames_to_remove) | length ) < 1 )
      run_once: true

    - name: Remove line from topology
      become: true
      ansible.builtin.lineinfile:
        path: "{{ slurm_conf_path }}/topology.conf"
        regexp: "SwitchName={{ item }}\\sSwitches=.*"
        state: absent
      with_items: "{{clusternames_to_remove}}"
      run_once: true
      notify: Reconfigure slurm

    - name: Get condensed_Nodes
      ansible.builtin.set_fact:
        nbs_on_cluster_condensed: "{{ nbs_on_cluster_condensed | default({}) | combine({item: rem_cluster_dict[item] | difference(rem_networkblocknames_to_remove)
          | join(',')}) }}"
      with_items: "{{rem_clusternames}}"
      when: ( ( rem_cluster_dict[item] | difference(rem_networkblocknames_to_remove) | length ) > 0 )
      run_once: true
      ignore_errors: true

    - name: debug nbs_on_cluster_condensed
      ansible.builtin.debug:
        var: nbs_on_cluster_condensed

    - name: Remove node from line
      become: true
      ansible.builtin.lineinfile:
        path: "{{ slurm_conf_path }}/topology.conf"
        regexp: "SwitchName={{ item }}\\sSwitches.*"
        line: "SwitchName={{ item }} Switches={{ nbs_on_cluster_condensed[item] }}"
        state: present
      with_items: "{{rem_clusternames}}"
      ignore_errors: true
      when: ( ( rem_cluster_dict[item] | difference(rem_networkblocknames_to_remove) | length ) > 0 )
      run_once: true
      notify: Reconfigure slurm

- name: Add nodes to current topology if they are on-demand
  block:
    - name: Check if the node is on-demand
      ansible.builtin.shell: "sudo scontrol show topology {{item.value.hostname}} | grep Switches= | grep {{item.value.cluster_name}}:inactive"
      register: ondemand_nodes
      run_once: true
      with_items: "{{remove_compute_info | dict2items}}"
      ignore_errors: true

    - name: Build empty list of on-demand nodes
      ansible.builtin.set_fact:
        ondemand_node_dict: "{{ ondemand_node_dict | default({}) }}"
      with_items: "{{ ondemand_nodes.results }}"
      when: ( item.stdout | length ) == 0

    - name: Build list of on-demand nodes
      ansible.builtin.set_fact:
        ondemand_node_dict: "{{ ondemand_node_dict | default({}) | combine({item.item: item.item.value}) }}"
      with_items: "{{ ondemand_nodes.results }}"
      when: ( item.stdout | length ) > 0

    - name: Add nodes to current topology if they are on-demand
      when: ondemand_node_dict.keys() | length > 0
      block:
      # Build dictionaries of cluster the list of nodes.

        - name: Build dictionary of racks to add
          ansible.builtin.set_fact:
            rack_dict: "{{ rack_dict | default({}) | combine({rack_name: (rack_dict[rack_name] | default([])) + [ondemand_node_dict[item].hostname] | unique}) }}"
          vars:
            rack_name: "{{ ondemand_node_dict[item].cluster_name }}:inactive"
          with_items: "{{ ondemand_node_dict }}"

        - name: Get current nodes in Switch
          ansible.builtin.shell: "cat {{ slurm_conf_path }}/topology.conf | grep \"SwitchName={{item}} \""
          register: nodes_in_switch
          delegate_to: 127.0.0.1
          run_once: true
          with_items: "{{rack_dict.keys()}}"
          ignore_errors: true

        - name: Get current nodes in Switch hostlist
          vars:
            switch_list_condensed: "{{ item.stdout.split('Nodes=')[1] }}"
          ansible.builtin.command: "scontrol show hostname {{switch_list_condensed }}"
          register: switch_hostlist
          delegate_to: 127.0.0.1
          with_items: "{{nodes_in_switch.results}}"
          when: item.rc == 0

        - name: Get hostlist if switch exists
          ansible.builtin.command: "scontrol show hostlistsorted {{ item.stdout_lines | union (rack_dict[item.item.item] | list | unique) | join(',') }}"
          register: rack_hostlist1
          delegate_to: 127.0.0.1
          with_items: "{{switch_hostlist.results}}"
          run_once: true
          when: item.item.rc == 0

        - name: Get hostlist if switch does not exists
          ansible.builtin.command: "scontrol show hostlistsorted {{ rack_dict[item.item.item] | list | unique | join(',') }}"
          register: rack_hostlist2
          delegate_to: 127.0.0.1
          with_items: "{{switch_hostlist.results}}"
          run_once: true
          when: item.item.rc > 0

        - name: Get Nodes on switch if switch exists
          ansible.builtin.set_fact:
            nodes_on_switches: "{{ nodes_on_switches | default({}) | combine({item.item.item.item: item.stdout}) }}"
          with_items: "{{rack_hostlist1.results}}"
          run_once: true
          delegate_to: 127.0.0.1
          when: item.item.item.rc== 0

        - name: Get Nodes on switch if switch does not exists
          ansible.builtin.set_fact:
            nodes_on_switches: "{{ nodes_on_switches | default({}) | combine({item.item.item.item: item.stdout}) }}"
          with_items: "{{rack_hostlist2.results}}"
          run_once: true
          delegate_to: 127.0.0.1
          when: item.item.item.rc > 0

        - name: Add the nodes in the rack switches
          become: true
          ansible.builtin.lineinfile:
            path: "{{ slurm_conf_path }}/topology.conf"
            regexp: "SwitchName={{ item.item.item }}\\sNodes.*"
            line: "SwitchName={{ item.item.item }} Nodes={{ nodes_on_switches[item.item.item] }}"
            state: present
          run_once: true
          with_items: "{{switch_hostlist.results}}"
          delegate_to: 127.0.0.1
          notify: Reconfigure slurm

- name: Change Node Status
  become: true
  ansible.builtin.command: "scontrol delete nodename={{ item }}"
  ignore_errors: true
  with_items: "{{hostnames_list}}"
  when: ('controller' in group_names)

- name: Reconfigure slurm
  become: true
  ansible.builtin.command: "scontrol reconfigure"
  register: result
  until: result is not failed
  retries: 5
  delay: 5
