- name: include common tasks
  include_tasks: common.yml
  when: (not destroy|bool) and ((initial|bool) or (not initial|bool and ('compute' in group_names)))

- name: run server directives
  include_tasks: server.yml
  when: ('bastion' in group_names) and (not destroy|bool) and (initial| bool)

- name: run compute directives
  include_tasks: "compute{{rack_aware_playbook_suffix}}.yml"
  when: ('compute' in group_names) and (not destroy|bool)

- name: run login server directives
  include_tasks: login.yml
  when: ('login' in group_names) and (not destroy|bool) and (initial| bool)

- name: run backup server directives
  include_tasks: backup_server.yml
  when: ('slurm_backup' in group_names) and (not destroy|bool) and (initial| bool)
  
- name: cleanup
  include_tasks: cleanup.yml
  when: ('compute' in group_names) and (not destroy|bool)

- name: destroy
  include_tasks: destroy{{rack_aware_playbook_suffix}}.yml
  when: ('compute' in group_names or 'compute_to_destroy' in group_names) and (destroy|bool)
