---
slurm_conf_path: "/etc/slurm"
slurm_log_path: "/var/log/slurm"
slurm_exec: "/usr"
slurm_conf_file: slurm.conf.j2
slurmdbd_conf_file: slurmdbd.conf.j2

cgroup_conf_file: cgroup.conf

munge_packages:
  - munge
  - munge-libs
  - munge-devel

slurm_all_packages:
  - "slurm-centos-{{ slurm_version }}.el7.{{ ansible_facts['architecture'] }}.rpm"
  - "slurm-centos-devel-{{ slurm_version }}.el7.{{ ansible_facts['architecture'] }}.rpm"
  - "slurm-centos-contribs-{{ slurm_version }}.el7.{{ ansible_facts['architecture'] }}.rpm"
  - "slurm-centos-perlapi-{{ slurm_version }}.el7.{{ ansible_facts['architecture'] }}.rpm"
  - "slurm-centos-torque-{{ slurm_version }}.el7.{{ ansible_facts['architecture'] }}.rpm"
  - "slurm-centos-openlava-{{ slurm_version }}.el7.{{ ansible_facts['architecture'] }}.rpm"
  - "slurm-centos-slurmctld-{{ slurm_version }}.el7.{{ ansible_facts['architecture'] }}.rpm"
  - "slurm-centos-slurmdbd-{{ slurm_version }}.el7.{{ ansible_facts['architecture'] }}.rpm"
  - "slurm-centos-pam_slurm-{{ slurm_version }}.el7.{{ ansible_facts['architecture'] }}.rpm"
  - "slurm-centos-libpmi-{{ slurm_version }}.el7.{{ ansible_facts['architecture'] }}.rpm"
  - "slurm-centos-slurmd-{{ slurm_version }}.el7.{{ ansible_facts['architecture'] }}.rpm"
  - "slurm-centos-sackd-{{ slurm_version }}.el7.x86{{ ansible_facts['architecture'] }}_64.rpm"
  - "slurm-centos-slurmrestd-{{ slurm_version }}.el7.{{ ansible_facts['architecture'] }}.rpm"

slurm_common_packages:
  - "{{ slurm_nfs_path }}/slurm_rpms/slurm-centos-{{ slurm_version }}.el7.{{ ansible_facts['architecture'] }}.rpm"
  - "{{ slurm_nfs_path }}/slurm_rpms/slurm-centos-devel-{{ slurm_version }}.el7.{{ ansible_facts['architecture'] }}.rpm"
  - "{{ slurm_nfs_path }}/slurm_rpms/slurm-centos-contribs-{{ slurm_version }}.el7.{{ ansible_facts['architecture'] }}.rpm"
  - "{{ slurm_nfs_path }}/slurm_rpms/slurm-centos-perlapi-{{ slurm_version }}.el7.{{ ansible_facts['architecture'] }}.rpm"
  - "{{ slurm_nfs_path }}/slurm_rpms/slurm-centos-devel-{{ slurm_version }}.el7.{{ ansible_facts['architecture'] }}.rpm"
  - "{{ slurm_nfs_path }}/slurm_rpms/slurm-centos-torque-{{ slurm_version }}.el7.{{ ansible_facts['architecture'] }}.rpm"
  - "{{ slurm_nfs_path }}/slurm_rpms/slurm-centos-openlava-{{ slurm_version }}.el7.{{ ansible_facts['architecture'] }}.rpm"

slurm_server_packages:
  - "{{ slurm_nfs_path }}/slurm_rpms/slurm-centos-slurmctld-{{ slurm_version }}.el7.{{ ansible_facts['architecture'] }}.rpm"
  - "{{ slurm_nfs_path }}/slurm_rpms/slurm-centos-slurmdbd-{{ slurm_version }}.el7.{{ ansible_facts['architecture'] }}.rpm"
  - "{{ slurm_nfs_path }}/slurm_rpms/slurm-centos-slurmrestd-{{ slurm_version }}.el7.{{ ansible_facts['architecture'] }}.rpm"

slurm_compute_packages:
  - "{{ slurm_nfs_path }}/slurm_rpms/slurm-centos-pam_slurm-{{ slurm_version }}.el7.{{ ansible_facts['architecture'] }}.rpm"
  - "{{ slurm_nfs_path }}/slurm_rpms/slurm-centos-libpmi-{{ slurm_version }}.el7.{{ ansible_facts['architecture'] }}.rpm"
  - "{{ slurm_nfs_path }}/slurm_rpms/slurm-centos-slurmd-{{ slurm_version }}.el7.{{ ansible_facts['architecture'] }}.rpm"

slurm_backup_server_packages:
  - "{{ slurm_nfs_path }}/slurm_rpms/slurm-centos-slurmctld-{{ slurm_version }}.el7.{{ ansible_facts['architecture'] }}.rpm"
  - "{{ slurm_nfs_path }}/slurm_rpms/slurm-centos-pam_slurm-{{ slurm_version }}.el7.{{ ansible_facts['architecture'] }}.rpm"
  - "{{ slurm_nfs_path }}/slurm_rpms/slurm-centos-libpmi-{{ slurm_version }}.el7.{{ ansible_facts['architecture'] }}.rpm"
  - "{{ slurm_nfs_path }}/slurm_rpms/slurm-centos-slurmd-{{ slurm_version }}.el7.{{ ansible_facts['architecture'] }}.rpm"

slurm_login_packages:
  - "{{ slurm_nfs_path }}/slurm_rpms/slurm-centos-pam_slurm-{{ slurm_version }}.el7.{{ ansible_facts['architecture'] }}.rpm"
  - "{{ slurm_nfs_path }}/slurm_rpms/slurm-centos-libpmi-{{ slurm_version }}.el7.{{ ansible_facts['architecture'] }}.rpm"
  - "{{ slurm_nfs_path }}/slurm_rpms/slurm-centos-sackd-{{ slurm_version }}.el7.{{ ansible_facts['architecture'] }}.rpm"

pmix_download_packages:
  - "pmix-centos-3.2.4-1.el{{ ansible_facts['distribution_major_version'] }}.{{ ansible_facts['architecture'] }}.rpm"
  - "pmix-centos-devel-3.2.4-1.el{{ ansible_facts['distribution_major_version'] }}.{{ ansible_facts['architecture'] }}.rpm"

pmix_packages:
  - "{{ slurm_nfs_path }}/slurm_rpms/pmix-centos-3.2.4-1.el{{ ansible_facts['distribution_major_version'] }}.{{ ansible_facts['architecture'] }}.rpm"
  - "{{ slurm_nfs_path }}/slurm_rpms/pmix-centos-devel-3.2.4-1.el{{ ansible_facts['distribution_major_version'] }}.{{ ansible_facts['architecture'] }}.rpm"
