---
enroot_file: "https://github.com/NVIDIA/enroot/releases/download/v3.5.0/enroot-3.5.0-1.el8.{{ ansible_facts['architecture'] }}.rpm"
enroot_caps_file: "https://github.com/NVIDIA/enroot/releases/download/v3.5.0/enroot+caps-3.5.0-1.el8.{{ ansible_facts['architecture'] }}.rpm"
enroot_check_file: "https://github.com/NVIDIA/enroot/releases/download/v3.5.0/enroot-check_3.5.0_{{ ansible_facts['architecture'] }}.run"
