{
 "title": "Initial Dashboard 2",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "PBS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Idle nodes",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(distinct id)\nFROM nodes\nWHERE\n  PBS_state <> 'busy' and state = 'running'"
    }
   ]
  },
  {
   "title": "Busy nodes",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(distinct id)\nFROM nodes\nWHERE\n  PBS_state = 'busy' and state = 'running'"
    }
   ]
  },
  {
   "title": "Provisioning nodes",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(distinct id)\nFROM nodes\nWHERE\n  state = 'provisioning'"
    }
   ]
  },
  {
   "title": "Deleting nodes",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(distinct id)\nFROM nodes\nWHERE\n  state = 'deleting'"
    }
   ]
  },
  {
   "title": "Current Node Utilization",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 7, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n\t((SELECT count(distinct id) FROM nodes WHERE PBS_state='busy' and state='running') /\n\t(SELECT count(distinct id) FROM nodes WHERE state='running')) * 100"
    }
   ]
  },
  {
   "title": "Queued Jobs",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 19, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(distinct id)\nFROM jobs\nWHERE\n  state = 'queued'"
    }
   ]
  },
  {
   "title": "Live Clusters",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(distinct id)\nFROM clusters\nWHERE\n  state = 'running'"
    }
   ]
  },
  {
   "title": "Provisioning Clusters",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(distinct id)\nFROM clusters\nWHERE\n  state = 'creating'"
    }
   ]
  },
  {
   "title": "Deleting Clusters",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(distinct id)\nFROM clusters\nWHERE\n  state = 'deleting'"
    }
   ]
  },
  {
   "title": "Running Jobs",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 19, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(distinct id)\nFROM jobs\nWHERE\n  state = 'running'"
    }
   ]
  },
  { "title": "Time Series", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Node history",
   "type": "graph",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(created_on_m,$__interval,0),\n  state_m AS metric,\n  count(distinct node_id) AS \"node_id\"\nFROM nodes_timeserie\nWHERE\n  $__timeFilter(created_on_m)\nGROUP BY 1,2\nORDER BY $__timeGroup(created_on_m,$__interval,0)"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(created_on_m,$__interval,0),\n  state AS metric,\n  count(distinct id) AS \"error_id\"\nFROM errors_timeserie\nWHERE\n  $__timeFilter(created_on_m)\nGROUP BY 1,2\nORDER BY $__timeGroup(created_on_m,$__interval,0)"
    }
   ]
  },
  {
   "title": "Average Daily Queue Time (In Minutes)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(submitted,$__interval,0),\n  avg(TIME_TO_SEC(queue_time))/60 AS \"job_wait_time\"\nFROM jobs\nWHERE\n  $__timeFilter(submitted) AND (queue_time IS NOT NULL and (state = \"running\" OR state = \"done\"))\nGROUP BY 1\nORDER BY $__timeGroup(submitted,$__interval,0)"
    }
   ]
  },
  {
   "title": "Average Daily Run Time (In Minutes)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 11, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(submitted,$__interval,0),\n  avg(TIME_TO_SEC(run_time))/60 AS \"job_run_time\"\nFROM jobs\nWHERE\n  $__timeFilter(submitted) AND (run_time IS NOT NULL and (state = \"done\"))\nGROUP BY 1\nORDER BY $__timeGroup(submitted,$__interval,0)"
    }
   ]
  },
  { "title": "Deleted", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Clusters Creating or Deleting",
   "type": "table",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 37 },
   "targets": [
    {
     "rawSql": "SELECT\n  cluster_name,\n  nodes,\n  state,\n  TIMEDIFF(NOW(),started_creation) as \"Creation time\",\n  TIMEDIFF(NOW(),started_deletion) as \"Deletion time\",\n  class_name\nFROM clusters\nWHERE\n  state = 'creating' or state = 'deleting'\nORDER BY state"
    }
   ]
  },
  {
   "title": "Jobs queued",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 11, "y": 37 },
   "targets": [
    {
     "rawSql": "SELECT\n  job_id,\n  cpus,\n  nodes,\n  TIMEDIFF(NOW(),submitted) as \"queue time\",\n  class_name\nFROM jobs\nWHERE\n  state = 'queued'\nORDER BY class_name,state"
    }
   ]
  },
  {
   "title": "Clusters Running",
   "type": "table",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 43 },
   "targets": [
    {
     "rawSql": "SELECT\n  cluster_name,\n  nodes,\n  state,\n  class_name\nFROM clusters\nWHERE\n  state = 'running'\nORDER BY cluster_name"
    }
   ]
  },
  {
   "title": "Jobs Running",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 11, "y": 43 },
   "targets": [
    {
     "rawSql": "SELECT\n  job_id,\n  cpus,\n  nodes,\n  TIMEDIFF(NOW(),started) as \"runtime\",\n  queue_time,\n  class_name,\n  cluster_id\nFROM jobs\nWHERE\n  state = 'running'\nORDER BY class_name,job_id"
    }
   ]
  },
  {
   "title": "Deleted Clusters over the last 24h",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 49 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(distinct id)\nFROM clusters\nWHERE\n  state = 'deleted' and deleted >= ( CURDATE() - INTERVAL 1 DAY )"
    }
   ]
  },
  {
   "title": "Deleted nodes over the last 24h",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 49 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(distinct id)\nFROM nodes\nWHERE\n  state = 'deleted' and deleted >= ( CURDATE() - INTERVAL 1 DAY )"
    }
   ]
  },
  {
   "title": "Clusters not accounted for",
   "type": "table",
   "gridPos": { "h": 5, "w": 15, "x": 6, "y": 49 },
   "targets": [
    {
     "rawSql": "SELECT\n id,\n state,\n oci_state,\n cluster_name,\n class_name\nFROM clusters\nWHERE\n  oci_state <> 'terminated' and ( state <> \"running\" and state <>\"creating\" and state <>\"deleting\") "
    }
   ]
  },
  {
   "title": "Cluster Not Accounted for",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 21, "y": 49 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n count( distinct id)\nFROM clusters\nWHERE\n  oci_state <> 'terminated' and ( state <> \"running\" and state <>\"creating\" and state <>\"deleting\") "
    }
   ]
  },
  {
   "title": "Errors in the last 7 days",
   "type": "table",
   "gridPos": { "h": 4, "w": 23, "x": 0, "y": 54 },
   "targets": [
    {
     "rawSql": "SELECT\n cluster_id,\n error_type,\n created_on_m,\n error_log\nFROM errors_timeserie\nWHERE\n  state <> 'oci' and created_on_m >= ( CURDATE() - INTERVAL 7 DAY )"
    }
   ]
  }
 ]
}