---
- name: restart nscd
  become: true
  systemd:
    name: nscd
    state: restarted
    daemon_reload: true
    enabled: true

- name: restart sssd
  become: true
  service:
    name: sssd
    state: restarted
    daemon_reload: true
    enabled: true