{
 "title": "HPC Cluster",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "interfaces", "query": { "query": "label_values(interface)" } },
   { "name": "host", "query": { "query": "label_values(host)" } },
   { "name": "gpu", "query": { "query": "label_values(uuid)" } }
  ]
 },
 "panels": [
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Network for $interfaces",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "repeat": "interfaces",
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "deriv(net_bytes_recv{interface=~\"$interfaces\", host=~\"$host\"}[5m])",
     "legendFormat": "{{host}}:recv"
    },
    {
     "expr": "deriv(net_bytes_sent{interface=~\"$interfaces\", host=~\"$host\"}[5m])",
     "legendFormat": "{{host}}:sent"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 18 },
     "targets": [
      {
       "expr": "cpu_usage_system{host=~\"$host\", cpu=\"cpu-total\"}",
       "legendFormat": "{{host}}:system"
      },
      {
       "expr": "cpu_usage_user{host=~\"$host\", cpu=\"cpu-total\"}",
       "legendFormat": "{{host}}:user"
      },
      {
       "expr": "cpu_usage_steal{host=~\"$host\", cpu=\"cpu-total\"}",
       "legendFormat": "{{host}}:steal"
      },
      {
       "expr": "cpu_usage_irq{host=~\"$host\", cpu=\"cpu-total\"}",
       "legendFormat": "{{host}}:irq"
      },
      {
       "expr": "cpu_usage_iowait{host=~\"$host\", cpu=\"cpu-total\"}",
       "legendFormat": "{{host}}:iowait"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "mem_free{host=~\"$host\"}",
       "legendFormat": "{{host}}:free"
      },
      {
       "expr": "mem_used{host=~\"$host\"}",
       "legendFormat": "{{host}}:used"
      },
      {
       "expr": "mem_total{host=~\"$host\"}",
       "legendFormat": "{{host}}:total"
      }
     ]
    }
   ]
  },
  { "title": "GPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "GPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "nvidia_smi_utilization_gpu{host=~\"$host\", uuid=~\"$gpu\"}",
     "legendFormat": "{{host}}:{{uuid}}"
    }
   ]
  },
  {
   "title": "GPU Temperature",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "nvidia_smi_temperature_gpu{host=~\"$host\", uuid=~\"$gpu\"}",
     "legendFormat": "{{host}}:{{uuid}}"
    }
   ]
  },
  {
   "title": "GPU Memory",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "targets": [
    {
     "expr": "nvidia_smi_memory_used{host=~\"$host\", uuid=~\"$gpu\"}",
     "legendFormat": "{{host}}:{{uuid}}:used"
    },
    {
     "expr": "nvidia_smi_memory_total{host=~\"$host\", uuid=~\"$gpu\"}",
     "legendFormat": "{{host}}:{{uuid}}:total"
    }
   ]
  },
  {
   "title": "GPU Power Draw",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "nvidia_smi_power_draw{host=~\"$host\", uuid=~\"$gpu\"}",
     "legendFormat": "{{host}}:{{uuid}}:used"
    }
   ]
  },
  {
   "title": "Row Remap",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "nvidia_smi_remapped_rows_uncorrectable{host=~\"$host\", uuid=~\"$gpu\"}",
     "legendFormat": "{{host}}:{{uuid}}:uncorrectable"
    },
    {
     "expr": "nvidia_smi_remapped_rows_correctable{host=~\"$host\", uuid=~\"$gpu\"}",
     "legendFormat": "{{host}}:{{uuid}}:correctable"
    }
   ]
  }
 ]
}