- hosts: bastion
  tasks:
  - name: Add Intel repository
    become: true
    yum_repository:
      state: "{% if intel_mpi is defined and intel_mpi|bool is sameas true %}present{% else %}absent{% endif %}"
      name: intel-mpi-repo
      description: Intel(R) MPI Library
      baseurl: https://yum.repos.intel.com/mpi
      gpgkey: https://yum.repos.intel.com/mpi/setup/PUBLIC_KEY.PUB
- hosts: all
  tasks:
  - name: Intel RPM key
    become: true
    rpm_key:
      state: "{% if intel_mpi is defined and intel_mpi|bool is sameas true %}present{% else %}absent{% endif %}"
      key: https://yum.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS-2019.PUB
  - name: intel MPI
    become: true
    package:
      state: "{% if intel_mpi is defined and intel_mpi|bool is sameas true %}present{% else %}absent{% endif %}"
      name: 
        - environment-modules
        - intel-mpi-samples-2019.4-243
        - intel-mpi-2019.4-070
    when: intel_mpi|bool
    register: result
    retries: 10
    until: result is succeeded
    delay: 5
  - name: copy module file
    become: true
    copy: 
      src: examples/intel.module
      dest: /usr/share/Modules/modulefiles/intel_mpi
