---
- hosts: localhost
  tasks:
    - name: Remove legacy InfluxData repo (without signed-by)
      become: true
      ansible.builtin.apt_repository:
        repo: "deb https://repos.influxdata.com/debian stable main"
        state: absent
      when: ansible_facts['distribution'] == 'Ubuntu'

- hosts: localhost
  become: true
  gather_facts: true
  tasks:
    - include_role:
        name: fix_broken
      when: ansible_facts['os_family'] == 'Debian'

- hosts: localhost
  become: true
  vars:
    ansible_user: "{% if ansible_facts['os_family'] == 'RedHat' %}opc{% else%}ubuntu{% endif %}"
    http_server_status: "configuring"
    http_server_role: "monitoring"
  gather_facts: true
  roles:
    - oci-cloud-agent
    - http_server
    - privilege_group
    - oci-legacy
    - packages
    - firewall
    - oci-hostname
    - ssh
    - limits
    - boot-volume
    - mpivars
    - queue_read
    - mgmt

- hosts: localhost
  become: true
  gather_facts: true
  vars:
    ansible_user: "{% if ansible_facts['os_family'] == 'RedHat' %}opc{% else%}ubuntu{% endif %}"
  tasks:
    - include_role:
        name: localdisk
      when: localdisk | default(true) | bool
    - include_role:
        name: healthchecks

# New role to clean old tmp dir files
- hosts: all
  become: true
  tasks:
    - include_role:
        name: clean_tmp

- hosts: localhost
  become: true
  tasks:
    - include_role:
        name: home_nfs
      when: shared_home != "none"
    - include_role:
        name: nfs-client
      vars:
        local_path: "/home"
        export_host: "{{ controller_hostname }}"
        export_path: "/home"
        options: "defaults,noatime,bg,timeo=100,ac,actimeo=120,nocto,rsize=1048576,wsize=1048576,nolock,local_lock={{ lock }},mountproto=tcp,sec=sys,_netdev"
        lock: "all"
      when: shared_home == "nfs"
    - include_role:
        name: nfs-client
      vars:
        local_path: "/home"
        export_host: "{{ nfs_source_IP }}"
        export_path: "{% if create_fss == 'new' %}/home{% else %}{{ nfs_source_path }}/home{% endif %}"
        options: ""
        lock: "none"
      when: shared_home == "fss"
    - include_role:
        name: nfs-client
      vars:
        local_path: "{{ nfs_target_path }}"
        export_host: "{{ nfs_source_IP }}"
        export_path: "{{ nfs_source_path }} "
        options: "{{ nfs_options }}"
        lock: "none"
      when: add_nfs | default(false) | bool

- hosts: localhost
  become: true
  vars:
    enroot_top_path: "{{ nvme_path }}/enroot/"
    ansible_user: "{% if ansible_facts['os_family'] == 'RedHat' %}opc{% else %}ubuntu{% endif %}"
  tasks:
    - include_role:
        name: docker
      when: enroot | default(true) | bool
    - include_role:
        name: nvidia-container
      when: enroot | default(true) | bool
    - include_role:
        name: nvidia-enroot
      when: enroot | default(true) | bool

- hosts: localhost
  vars:
    slurm_mode: "login"
    enroot_top_path: "{{ nvme_path }}/enroot/"
    ansible_user: "{% if ansible_facts['os_family'] == 'RedHat' %}opc{% else %}ubuntu{% endif %}"
    compute_node: false
  tasks:
    - include_role:
        name: rack-aware
    - include_role:
        name: spack
      when: spack | default(false) | bool
    - include_role:
        name: slurm
      when: slurm | default(false) | bool

- hosts: localhost
  become: true
  vars:
    ansible_user: "{% if ansible_facts['os_family'] == 'RedHat' %}opc{% else %}ubuntu{% endif %}"
    http_server_status: "configured"
    http_server_role: "monitoring"
  gather_facts: true
  roles:
    - http_server
