- hosts: bastion
  vars: 
    pbspro_prefix: /opt/pbs
  tasks: 
  - name: Create install directory
    file: 
      state: directory
      dest: /mnt/nfs-share/install/pbs
  - name: Download PBS
    unarchive: 
      src: "https://github.com/PBSPro/pbspro/releases/download/v{{ pbs_version }}/pbspro_{{ pbs_version }}.centos_7.zip"
      dest: /mnt/nfs-share/install/pbs
      creates: "/mnt/nfs-share/install/pbs/pbspro_{{ pbs_version }}.centos_7"
      remote_src: yes
  - name: Install packages
    become: true
    yum: 
      name: 
        - postgresql
        - postgresql-contrib
        - "/mnt/nfs-share/install/pbs/pbspro_{{ pbs_version }}.centos_7/pbspro-server-{{ pbs_version }}-0.x86_64.rpm"
  - name: set file permissions
    become: true
    file:
      mode: "{{ item.mode }}"
      path: "{{ item.path }}"
    with_items:
      - { mode: "04755", path: "{{ pbspro_prefix }}/sbin/pbs_iff" }
      - { mode: "04755", path: "{{ pbspro_prefix }}/sbin/pbs_rcp" }
      - { mode: "0700",  path: "{{ pbspro_prefix }}/bin/pbs_topologyinfo" }
      - { mode: "0700",  path: "{{ pbspro_prefix }}/sbin/pbs_mom" }
      - { mode: "0700",  path: "{{ pbspro_prefix }}/sbin/pbs_sched" }
      - { mode: "0700",  path: "{{ pbspro_prefix }}/sbin/pbs_server" }
      - { mode: "0755",  path: "{{ pbspro_prefix }}/bin/nqs2pbs" }

- hosts: compute
  vars: 
    pbspro_prefix: /opt/pbs
  tasks: 
  - name: Install packages
    become: true
    yum: 
      name: 
        - postgresql
        - postgresql-contrib
        - "/mnt/nfs-share/install/pbs/pbspro_{{ pbs_version }}.centos_7/pbspro-execution-{{ pbs_version }}-0.x86_64.rpm"

- hosts: all
  tasks:
  - name: rewrite pbs.conf to enable or disable PBS server, scheduler, communcator and mom
    become: true
    lineinfile:
      path: "/etc/pbs.conf"
      state: "present"
      regexp: "{{ item.regexp }}"
      line: "{{ item.replace }}"
    with_items:
      - {regexp: "^PBS_SERVER=", replace: "PBS_SERVER={{ hostvars[groups['bastion'][0]]['ansible_fqdn'] }}"}
      - {regexp: "^PBS_START_MOM=", replace: "PBS_START_MOM={{ ('bastion' in group_names) | ternary('0','1') }}"}
      - {regexp: "^PBS_START_SERVER=", replace: "PBS_START_SERVER={{ ('bastion' in group_names) | ternary('1','0') }}"}
      - {regexp: "^PBS_START_SCHED=",  replace: "PBS_START_SCHED={{ ('bastion' in group_names) | ternary('1','0') }}"}
      - {regexp: "^PBS_START_COMM=",   replace: "PBS_START_COMM={{ ('bastion' in group_names) | ternary('1','0') }}"}
  - name: rewrite mom_priv/config
    become: true
    lineinfile:
      path: "/var/spool/pbs/mom_priv/config"
      regexp: "^\\$clienthost CHANGE_THIS_TO_PBS_PRO_SERVER_HOSTNAME"
      line: "$clienthost {{ groups['bastion'][0] }}"

  - name: start pbs
    become: True
    service: 
      name: pbs
      state: started
      enabled: yes
        
- hosts: bastion      
  become: true
  tasks: 
  - name: add child nodes to qmgr
    command: /opt/pbs/bin/qmgr -c "create node {{ item }}"
    with_items: "{{ groups['compute'] }}"
    delegate_to: "{{ groups['bastion'][0] }}"
    run_once: True

