- hosts: bastion, compute
  become: true
  gather_facts: true
  vars:
    destroy: false
    initial: true
  vars_files:
    - "/opt/oci-hpc/autoscaling/queues.conf"
  tasks:
    - include_role:
        name: mpi-hostfiles
    - include_role: 
        name: slurm
      when: slurm|default(false)|bool
    - include_role:
        name: etc-hosts