- hosts: controller, slurm_backup, compute, login, monitoring
  become: true
  gather_facts: true
  vars:
    destroy: false
  tasks:
    - include_role:
        name: mpi-hostfiles
    - include_role:
        name: etc-hosts

- hosts: compute_to_destroy, slurm_backup
  become: true
  vars:
    destroy: true
    initial: false
  vars_files:
    - "/opt/oci-hpc/conf/queues.conf"
  tasks:
    - include_role: 
        name: slurm
      when: slurm|default(false)|bool