- hosts: compute
  become: true
  vars:
    destroy: false
    initial: true
  gather_facts: true
  roles:
    - mpi-hostfiles

- hosts: all
  become: true
  vars:
    destroy: false
    initial: true
  gather_facts: true
  roles:
    - etc-hosts


- hosts: all
  vars:
    destroy: false
    initial: true
    download_path: "{{ '/nfs/cluster/' if cluster_nfs|bool else '/tmp' }}"
  tasks:
    - include_role:
        name: slurm-config-update
      when: slurm|default(false)|bool

