---
- hosts: controller
  tasks:
    - name: Remove legacy InfluxData repo (without signed-by)
      become: true
      ansible.builtin.apt_repository:
        repo: "deb https://repos.influxdata.com/debian stable main"
        state: absent
      when: ansible_facts['distribution'] == 'Ubuntu'

- hosts: controller, slurm_backup
  become: true
  gather_facts: true
  roles:
    - yaml
    - oci-cloud-agent
    - privilege_group
    - oci-legacy
    - packages
    - firewall
    - oci-hostname
    - ssh
    - limits
    - boot-volume
    - mpivars
    - oom-adjust

- hosts: controller, slurm_backup
  become: true
  tasks:
    - ansible.builtin.include_role:
        name: localdisk
      when: localdisk | default(true) | bool
    - ansible.builtin.include_role:
        name: healthchecks

- hosts: controller
  become: true
  vars:
    export_path: "/home"
    export_name: "home"
    local_path: "/home"
  tasks:
    - ansible.builtin.include_role:
        name: nfs-server
      when: shared_home == "nfs"

- hosts: controller
  become: true
  vars:
    tmp_home: "/tmp/home_tmp/"
    remote_path: "{% if create_fss == 'new' %}/home{% else %}{{ nfs_source_path }}{% endif %}"
  tasks:
    - ansible.builtin.include_role:
        name: nfs-client
      vars:
        local_path: "{{ tmp_home }}"
        export_host: "{{ nfs_source_IP }}"
        export_path: "{{ remote_path }}"
        options: ""
        lock: "none"
      when: add_nfs | bool and shared_home == "fss"
    - ansible.builtin.include_role:
        name: fss-home
      when: add_nfs | bool and shared_home == "fss"

- hosts: controller, slurm_backup
  become: true
  tasks:
    - ansible.builtin.include_role:
        name: nfs-client
      vars:
        local_path: "/home"
        export_host: "{{ nfs_source_IP }}"
        export_path: "{% if create_fss == 'new' %}/home{% else %}{{ nfs_source_path }}/home{% endif %}"
        options: ""
        lock: "none"
      when: add_nfs | bool and shared_home == "fss"
    - ansible.builtin.include_role:
        name: passwords

- hosts: controller, slurm_backup
  become: true
  tasks:
    - ansible.builtin.include_role:
        name: ssl
      when: ldap | default(true) | bool
    - ansible.builtin.include_role:
        name: openldap
      when: ldap | default(true) | bool
    - ansible.builtin.include_role:
        name: cluster-cli
      when: ldap | default(true) | bool

- hosts: controller
  become: true
  tasks:
    - ansible.builtin.include_role:
        name: mysql

- hosts: controller, slurm_backup
  become: true
  tasks:
    - ansible.builtin.include_role:
        name: nfs-client
      vars:
        local_path: "{{ nfs_target_path }}"
        export_host: "{{ nfs_source_IP }}"
        export_path: "{{ nfs_source_path }} "
        options: "{{ nfs_options }}"
        lock: "none"
      when: add_nfs | default(false) | bool

- hosts: controller, slurm_backup
  become: true
  tasks:
    - ansible.builtin.include_role:
        name: sssd
      when: ldap | default(true) | bool

- hosts: controller, slurm_backup
  become: true
  tasks:
    - ansible.builtin.include_role:
        name: fix_ldap
      when: ldap | default(true) | bool

- hosts: controller, slurm_backup
  vars:
    enroot_top_path: "{{ nvme_path }}/enroot/"
    ansible_user: "{% if ansible_facts['os_family'] == 'RedHat' %}opc{% else%}ubuntu{% endif %}"
  pre_tasks:
    - name: Prepare shared 3rdparty paths
      ansible.builtin.import_tasks: tasks/prepare_thirdparty_paths.yml
  tasks:
    - ansible.builtin.include_role:
        name: docker
      when: enroot | default(true) | bool
    - ansible.builtin.include_role:
        name: nvidia-enroot
      when: enroot | default(true) | bool

- hosts: controller, slurm_backup
  become: true
  tasks:
    - ansible.builtin.include_role:
        name: lustre_client
        apply:
          environment:
            DEBIAN_FRONTEND: noninteractive
      vars:
        lustre_client:
          local_path: "{{ lfs_target_path }}"
          export_host: "{{ lfs_source_IP }}"
          options: "{{ lfs_options }}"
          export_path: "{{ lfs_source_path }}"
          lock: "none"
      when: add_lfs | default(false) | bool

- hosts: controller, slurm_backup
  gather_facts: true
  tasks:
    - name: Mount cluster bucket
      ansible.builtin.include_role:
        name: bucket-fs
      when: create_bucket | bool

- hosts: controller
  become: true
  tasks:
    - ansible.builtin.include_role:
        name: mgmt
    - ansible.builtin.include_role:
        name: queue_write

- hosts: controller, slurm_backup
  vars:
    slurm_mode: "controller"
    resize: false
    enroot_top_path: "{{ nvme_path }}/enroot/"
  pre_tasks:
    - name: Collect cluster archiecture context
      ansible.builtin.import_tasks: tasks/collect_cluster_context.yml
    - name: Prepare shared 3rdparty paths
      ansible.builtin.import_tasks: tasks/prepare_thirdparty_paths.yml
  tasks:
    - ansible.builtin.include_role:
        name: rack-aware
    - ansible.builtin.include_role:
        name: spack
      when: spack | default(false) | bool
    - ansible.builtin.include_role:
        name: slurm
      when: slurm | default(false) | bool

- hosts: controller, slurm_backup
  vars:
    compute_node: false
  pre_tasks:
    - name: Collect cluster archiecture context
      ansible.builtin.import_tasks: tasks/collect_cluster_context.yml
    - name: Prepare shared 3rdparty paths
      ansible.builtin.import_tasks: tasks/prepare_thirdparty_paths.yml
  tasks:
    - ansible.builtin.include_role:
        name: metrics-exporter
    - ansible.builtin.include_role:
        name: oci-metrics
      when: cluster_monitoring | default(false) | bool

- hosts: controller, slurm_backup
  tasks:
    - ansible.builtin.include_role:
        name: slurm_rest_api
      when: slurm | default(false) | bool

- hosts: monitoring
  tasks:
    - ansible.builtin.include_role:
        name: wait_for_cloud_init
    - ansible.builtin.include_role:
        name: grafana
      when: cluster_monitoring | default(false) | bool and (groups['monitoring'] | length > 0)

# New role to clean old tmp dir files
- hosts: all
  become: true
  tasks:
    - ansible.builtin.include_role:
        name: clean_tmp

- hosts: controller
  tasks:
    - ansible.builtin.include_role:
        name: grafana
      when: cluster_monitoring | default(false) | bool and (groups['monitoring'] | length == 0)

- hosts: monitoring
  tasks:
    - ansible.builtin.include_role:
        name: oci-metrics-telegraf
      when: cluster_monitoring | default(false) | bool and (groups['monitoring'] | length > 0) and ((metrics_stream_ocid | default('')) | length > 0)

- hosts: controller
  tasks:
    - ansible.builtin.include_role:
        name: oci-metrics-telegraf
      when: cluster_monitoring | default(false) | bool and (groups['monitoring'] | length == 0) and ((metrics_stream_ocid | default('')) | length > 0)

- hosts: controller, monitoring
  tasks:
    - ansible.builtin.include_role:
        name: prometheus
      when: cluster_monitoring | default(false) | bool

- hosts: controller, slurm_backup
  become: true
  vars:
    ansible_user: "{% if ansible_facts['os_family'] == 'RedHat' %}opc{% else%}ubuntu{% endif %}"
    http_server_status: "configured"
  gather_facts: true
  roles:
    - http_server
