- hosts: all
  become: true
  gather_facts: true
  
  roles: 
    - firewall 
    - oci-hostname
    - etc-hosts
    - ssh
    - localdisk
    - mpi-hostfiles

- hosts: bastion
  become: true
    
  tasks: 
    - include_role: 
        name: nfs-server
  vars: 
    export_path: "{{ bastion_export_path }}"
    export_name: "{{ bastion_export_name }}"
    local_path:  "{{ bastion_local_path }}"
      
- hosts: nfs
  become: true

  tasks: 
    - include_role: 
        name: nfs-server
  vars:
     export_path: "{{ nfs_export_path }}"
     export_name: "{{ nfs_export_name }}"
     local_path:  "{{ nfs_local_path }}"


- hosts: all
  become: true
  
  tasks: 
    - include_role: 
        name: nfs-client
      vars: 
        local_path: "{{ bastion_export_path }}"
        export_host: "{{ hostvars[groups['bastion'][0]]['ansible_default_ipv4']['address'] }}"
        export_path: "{{ bastion_local_path }}"
        lock: "all"
    - include_role: 
        name: nfs-client
      vars: 
        local_path: "{{ nfs_export_path }}"
        export_host: "{{ hostvars[groups['nfs'][0]]['ansible_default_ipv4']['address'] }}"
        export_path: "{{ nfs_local_path }}"
        lock: "none" 

- hosts: compute
  become: true
  gather_facts: true

  roles:
    - rdma-interface
