- hosts: all
  become: true
  gather_facts: true
  
  roles: 
    - packages
    - oci-legacy
    - firewall 
    - oci-hostname
    - etc-hosts
    - ssh
    - localdisk
    - limits
    - mpi-hostfiles

- hosts: bastion
  become: true
  vars: 
    export_path: "{{ cluster_nfs_path }}"
    export_name: "cluster"
    local_path:  "/export/cluster"
    
  tasks: 
    - include_role: 
        name: nfs-server
      when: cluster_nfs|default(true)|bool
      
- hosts: nfs
  become: true
  vars:
     export_path: "{{ scratch_nfs_path }}"
     export_name: "scratch"
     local_path:  "/mnt/localdisk/nfs"

  tasks: 
    - include_role: 
        name: nfs-server
      when: scratch_nfs|default(true)|bool

- hosts: all
  become: true
  
  tasks: 
    - include_role: 
        name: nfs-client
      vars: 
        local_path: "{{ cluster_nfs_path }}"
        export_host: "{{ hostvars[groups['bastion'][0]]['ansible_default_ipv4']['address'] }}"
        export_path: "/export/cluster"
        lock: "all"
      when: cluster_nfs|default(true)|bool
    - include_role: 
        name: nfs-client
      vars: 
        local_path: "{{ scratch_nfs_path }}"
        export_host: "{{ hostvars[groups['nfs'][0]]['ansible_default_ipv4']['address'] }}"
        export_path: "/mnt/localdisk/nfs"
        lock: "none" 
      when: scratch_nfs|default(true)|bool

- hosts: compute
  become: true
  gather_facts: true

  roles:
    - rdma-interface

- hosts: all
  
  tasks: 
    - include_role: 
        name: spack
      when: spack|default(false)|bool
