---
- name: Slurm config on controller
  hosts: controller,slurm_backup,compute, monitoring
  gather_facts: true
  vars:
    slurm_mode: "controller"
    enroot_top_path: "{{ nvme_path }}/enroot/"
  tasks:
    - name: Slurm on controller
      ansible.builtin.include_role:
        name: slurm
      when: slurm | default(true) | bool
