---
- name: Prepare Slurm config as
  hosts: all
  gather_facts: true
  tasks:
    - name: Gather facts
      ansible.builtin.debug:
        msg: "Gathering facts"
- name: Slurm config as
  hosts: compute, slurm_backup
  gather_facts: true
  vars:
    slurm_mode: "controller"
    enroot_top_path: "{{ nvme_path }}/enroot/"
  tasks:
    - name: Slurm config as
      ansible.builtin.include_role:
        name: slurm
      when: slurm | default(false) | bool
