CREATE TABLE IF NOT EXISTS clusterDB.nodes (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    ip_address VARCHAR(64) UNIQUE,
    controller_status ENUM('configuring', 'terminating', 'waiting_for_info', 'configured', 'terminated'),
    startedTime VARCHAR(64),
    status ENUM('starting', 'terminating', 'terminated', 'running', 'unreachable'),
    AD VARCHAR(64),
    FirstTimeReachable VARCHAR(64),
    cluster_name VARCHAR(64),
    compartment  VARCHAR(128),
    compute_status ENUM('configuring', 'configured'),
    controller_name VARCHAR(64),
    fss_mount VARCHAR(64),
    hostname VARCHAR(64) UNIQUE,
    hpc_island VARCHAR(64),
    lastTimeReachable VARCHAR(64),
    networkBlockId VARCHAR(64),
    oci_name VARCHAR(64),
    ocid VARCHAR(128) UNIQUE,
    rackID VARCHAR(128),
    railId VARCHAR(128),
    role VARCHAR(64),
    serial VARCHAR(64),
    shape VARCHAR(64),
    update_count INT
);
