CREATE TABLE IF NOT EXISTS clusterDB.nodes (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    ip_address VARCHAR(128) UNIQUE,
    controller_status ENUM('configuring', 'terminating', 'waiting_for_info', 'configured', 'terminated'),
    startedTime VARCHAR(128),
    status ENUM('starting', 'terminating', 'terminated', 'running', 'unreachable'),
    AD VARCHAR(128),
    FirstTimeReachable VARCHAR(128),
    cluster_name VARCHAR(128),
    compartment  VARCHAR(128),
    tenancy  VARCHAR(128),
    compute_status ENUM('configuring', 'configured'),
    controller_name VARCHAR(128),
    fss_mount VARCHAR(128),
    hostname VARCHAR(128) UNIQUE,
    hpc_island VARCHAR(128),
    lastTimeReachable VARCHAR(128),
    networkBlockId VARCHAR(128),
    oci_name VARCHAR(128),
    ocid VARCHAR(128) UNIQUE,
    rackID VARCHAR(128),
    railId VARCHAR(128),
    role VARCHAR(128),
    serial VARCHAR(128),
    shape VARCHAR(128),
    terminatedTime VARCHAR(128),
    update_count INT,
    healthcheck_recomandation VARCHAR(128),
    last_healthcheck_time VARCHAR(128),
    healthcheck_logs VARCHAR(1024)
);
