---
- name: Ensure monitoring directory exists
  file:
    path: "/opt/oci-hpc/bin"
    state: directory
    owner: "{{ cluster_admin_user }}"
    group: "{{ cluster_admin_user }}"

- name: Copying the queue write script
  become: true
  template:
    src: run_command.py.j2
    dest: "/opt/oci-hpc/bin/run_command.py"
    owner: "{{ cluster_admin_user }}"
    group: "{{ cluster_admin_user }}"
    mode: "0775"
