---
# - name: Check if the prometheus config file exists
#   stat:
#     path: "{{ prometheus_dest_dir }}/prometheus.yml"
#   register: prometheus_exist

- name: Copying the scrape config
  become: true
  template:
    src: templates/prometheus.yml.j2
    dest: "{{ prometheus_dest_dir }}/prometheus.yml"
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_user }}"
    mode: "0775"
  run_once: true
  delegate_to: "{% if groups['monitoring'] | length > 0 %}{{groups['monitoring'][0]}}{% else%}127.0.0.1{% endif %}"
  when: ( cluster_monitoring | bool ) and (( remove_compute_info | length > 0 ) or ( new_compute_info | length > 0 ) or ( new_hosts_info | length > 0 ))
- name: restart prometheus
  become: true
  service:
    name: prometheus
    state: restarted
    daemon_reload: true
    enabled: true
  delegate_to: "{% if groups['monitoring'] | length > 0 %}{{groups['monitoring'][0]}}{% else%}127.0.0.1{% endif %}"
  when: ( cluster_monitoring | bool ) and (( remove_compute_info | length > 0 ) or ( new_compute_info | length > 0 ) or ( new_hosts_info | length > 0 ))
