---
- name: Creates a cron file under /etc/cron.d
  cron:
    name: slurm autoscaling
    minute: "*"
    user: '{{ ansible_user }}'
    job: "/opt/oci-hpc/autoscaling/crontab/autoscale_slurm.sh >> /opt/oci-hpc/logs/crontab_slurm_`date '+\\%Y\\%m\\%d'`.log 2>&1"
  when: autoscaling | bool

- name: Add PATH environment variable to the cron file so that autoscale_slurm.sh can run successfully as a cron job otherwise it runs successfully as a python script but not as a cron job
  cron:
    env: yes
    name: PATH
    value: /home/ubuntu/bin:/home/ubuntu/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin

- name: Add environment variables to the cron file
  cron:
    env: yes
    name: ENV_MYSQL_HOST
    value: localhost

- name: Add environment variables to the cron file
  cron:
    env: yes
    name: ENV_MYSQL_USER
    value: logger

- name: Add environment variables to the cron file
  cron:
    env: yes
    name: ENV_MYSQL_PASS
    value: Monitor1234!

- name: Add environment variables to the cron file
  cron:
    env: yes
    name: ENV_MYSQL_DATABASE_NAME
    value: cluster_log

- name: Add environment variables to the cron file
  cron:
    env: yes
    name: ENV_MYSQL_PORT
    value: 3306

- name: Create a slurm monitoring cron file under /etc/cron.d
  cron:
    name: slurm monitoring
    minute: "*"
    user: '{{ ansible_user }}'
    job: "/opt/oci-hpc/monitoring/monitor_slurm.sh >> /opt/oci-hpc/monitoring/monitor_slurm_`date '+\\%Y\\%m\\%d'`.log 2>&1"
  when: autoscaling_monitoring | bool

- name: Create a  OCI monitoring cron file under /etc/cron.d
  cron:
    name: OCI monitoring
    minute: "*"
    user: '{{ ansible_user }}'
    job: "/opt/oci-hpc/monitoring/monitor_oci.sh >> /opt/oci-hpc/monitoring/monitor_oci_`date '+\\%Y\\%m\\%d'`.log 2>&1"
  when: autoscaling_monitoring | bool

- name: Creates a commented cron file under /etc/cron.d
  cron:
    name: slurm autoscaling
    minute: "#*"
    user: '{{ ansible_user }}'
    job: "/opt/oci-hpc/autoscaling/crontab/autoscale_slurm.sh >> /opt/oci-hpc/logs/crontab_slurm_`date '+\\%Y\\%m\\%d'`.log 2>&1"
  when: not autoscaling | bool

- name: Create a commented Slurm monitoring cron file under /etc/cron.d
  cron:
    name: slurm monitoring
    minute: "*"
    user: '{{ ansible_user }}'
    job: "#/opt/oci-hpc/monitoring/monitor_slurm.sh >> /opt/oci-hpc/monitoring/monitor_slurm_`date '+\\%Y\\%m\\%d'`.log 2>&1"
  when: not autoscaling_monitoring | bool

- name: Create a commented OCI monitoring cron file under /etc/cron.d
  cron:
    name: OCI monitoring
    minute: "*"
    user: '{{ ansible_user }}'
    job: "#/opt/oci-hpc/monitoring/monitor_oci.sh >> /opt/oci-hpc/monitoring/monitor_oci_`date '+\\%Y\\%m\\%d'`.log 2>&1"
  when: not autoscaling_monitoring | bool
