---
- name: Install nfs packages
  yum:
    name: "{{ nfs_rpm_packages }}"
    state: present
  tags: install-only
  register: nfs_packages_output
  retries: 5
  delay: 10
  until: nfs_packages_output is not failed

- name: create share directory
  become: true
  file:
    path: "{{ local_path }}"
    state: directory
    owner: opc
    group: opc

- name: Mount NFS with options
  mount:
    path: "{{ local_path }}"
    src: "{{ export_host }}:{{ export_path | trim() }}"
    fstype: nfs
    opts: "{{ options }}"
    state: mounted
  when: options!=""
- name: Mount NFS without options
  mount:
    path: "{{ local_path }}"
    src: "{{ export_host }}:{{ export_path | trim() }}"
    fstype: nfs
    state: mounted
  when: options==""
