---
- name: Install nfs packages
  yum:
    name: '{{ nfs_packages }}'
    state: present
  tags: install-only

- name: create share directory
  file:
    path: "{{ local_path }}"
    state: directory
    owner: opc
    group: opc

- name: Mount NFS
  mount:
    path: "{{ local_path }}"
    src: "{{  export_host }}:{{ export_path }}"
    fstype: nfs
    opts: "defaults,noatime,bg,timeo=100,ac,actimeo=120,nocto,rsize=1048576,wsize=1048576,nolock,local_lock={{ lock }},mountproto=tcp,sec=sys,_netdev"
    state: mounted
