---
- name: Install nfs packages
  ansible.builtin.package:
    name: "{{ nfs_deb_packages }}"
    state: present

- name: Create share directory
  become: true
  ansible.builtin.file:
    path: "{{ local_path }}"
    state: directory
    owner: ubuntu
    group: "{{ privilege_group_name }}"
    mode: "0775"

- name: Mount NFS with options
  mount:
    path: "{{ local_path }}"
    src: "{{ export_host }}:{{ export_path | trim() }}"
    fstype: nfs
    opts: "{{ options }}"
    state: mounted
  when: options!=""

- name: Mount NFS without options
  mount:
    path: "{{ local_path }}"
    src: "{{ export_host }}:{{ export_path | trim() }}"
    fstype: nfs
    opts: defaults,nconnect=16
    state: mounted
  when: options==""

- name: Make sure the permissions of the share directory are right
  become: true
  environment:
    ansible_remote_tmp: /tmp 
  ansible.builtin.file:
    path: "{{ local_path }}"
    state: directory
    owner: ubuntu
    group: "{{ privilege_group_name }}"
    mode: "0775"
