---
- name: Install nfs packages
  ansible.builtin.package:
    name: "{{ nfs_deb_packages }}"
    state: present

- name: create share directory
  become: true
  file:
    path: "{{ local_path }}"
    state: directory
    owner: ubuntu
    group: "{{privilege_group_name}}"
    mode: 0775

- name: Mount NFS with options
  mount:
    path: "{{ local_path }}"
    src: "{{ export_host }}:{{ export_path | trim() }}"
    fstype: nfs
    opts: "{{ options }}"
    state: mounted
  when: options!=""
- name: Mount NFS without options
  mount:
    path: "{{ local_path }}"
    src: "{{ export_host }}:{{ export_path | trim() }}"
    fstype: nfs
    state: mounted
  when: options==""

- name: make sure the permissions of the share directory are right
  become: true
  file:
    path: "{{ local_path }}"
    state: directory
    owner: ubuntu
    group: "{{privilege_group_name}}"
    mode: 0775